mongodb/mongo-php-driver

php_phongo.c
php_phongo_classes.h
src/MongoDB/WriteResult.c
tests/bulk/write-0001.phpt
tests/standalone/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/standalone/writeresult-isacknowledged-002.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/writeConcern/writeconcern-001.phpt
tests/writeConcern/writeconcern-003.phpt

* https://jira.mongodb.org/browse/PHPC-168
* https://jira.mongodb.org/browse/PHPC-170
* https://jira.mongodb.org/browse/PHPC-177

Store WriteConcern in WriteResult to allow reporting of acknowledgement

---

php_phongo.c
php_phongo.h
src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c

https://jira.mongodb.org/browse/PHPC-181

PHPC-181: Const is our friend

---

src/MongoDB/Result.c
tests/standalone/manager-executeQuery-005.phpt

https://jira.mongodb.org/browse/PHPC-201

PHPC-201: Rename Result::setTypemap() to setTypeMap()

---

php_phongo.c
php_phongo_classes.h
src/MongoDB/Result.c

https://jira.mongodb.org/browse/PHPC-214

PHPC-214: Result does not need custom iterator classes

---

bin/prep-release.php

Diff of package.xml generated with previous version and this new one:
--- /tmp/package.xml	2015-04-23 06:49:54.979348152 +0200
+++ ./package.xml	2015-04-23 07:03:23.789496181 +0200
@@ -27,7 +27,7 @@
<active>yes</active>
</lead>
<date>2015-04-23</date>
- <time>06:49:54</time>
+ <time>07:03:23</time>
<version>
<release>0.5.0</release>
<api>0.5.0</api>
@@ -55,7 +55,7 @@
<contents>
<dir name="/">
<file role="doc" name="LICENSE"/>
-   <file role="doc" name="Makefile.frag"/>
+   <file role="src" name="Makefile.frag"/>
<file role="doc" name="README.md"/>
<file role="doc" name="RELEASE-0.1.0"/>
<file role="doc" name="RELEASE-0.1.1"/>
@@ -69,7 +69,7 @@
<file role="doc" name="RELEASE-0.4.0"/>
<file role="doc" name="RELEASE-0.4.1"/>
<file role="doc" name="RELEASE-0.5.0"/>
-   <file role="doc" …

PHPC-258: make all filed needed for test as role="test"

---

tests/standalone/cursor-get_iterator-003.phpt

https://jira.mongodb.org/browse/PHPC-282

PHPC-282: Test for multiple Cursor::toArray() calls

---

tests/cursor/cursor-getmore-005.phpt

https://jira.mongodb.org/browse/PHPC-308

PHPC-308: Skip getmore test until libmongoc issues are resolved

---

php_phongo.c
tests/functional/query-sort-004.phpt

https://jira.mongodb.org/browse/PHPC-317

PHPC-317: Ensure "sort" query option serializes as BSON object

---

src/bson.c
tests/bson/bug0325.phpt

https://jira.mongodb.org/browse/PHPC-325

PHPC-325: bson_to_zval() leaks when buffer contains multiple documents

---

config.m4
src/bson.c
tests/bson/bson-encode-003.phpt

https://jira.mongodb.org/browse/PHPC-330

PHPC-330: Always include __pclass property when unserializing BSON

---

src/BSON/Binary.c
tests/bson/bson-binary-001.phpt

https://jira.mongodb.org/browse/PHPC-333

PHPC-333: Implement MongoDB\BSON\Binary::getData()

---

src/MongoDB/Server.c
tests/server/server-executeBulkWrite-002.phpt
tests/server/server-executeBulkWrite-003.phpt
tests/server/server-executeBulkWrite-004.phpt
tests/server/server-executeBulkWrite-005.phpt

https://jira.mongodb.org/browse/PHPC-271

PHPC-271: Server::executeBulkWrite() should take a write concern

---

config.w32

https://jira.mongodb.org/browse/PHPC-365

PHPC-365: Add src/contrib to Windows build includes

---

tests/bson/bson-binary_error-001.phpt
tests/bson/bson-javascript_error-001.phpt
tests/bson/bson-objectid_error-001.phpt
tests/bson/bson-regex_error-001.phpt
tests/bson/bson-timestamp_error-001.phpt
tests/bson/bson-utcdatetime_error-001.phpt

Based on comments in https://github.com/10gen-labs/mongo-php-driver-prototype/pull/89#discussion_r38105407.

Clean up BSON error tests

---

tests/bson/bson-encode-004.phpt
tests/cursor/cursor-get_iterator-002.phpt

See each individual commit for explanations why.

Disable tests for HHVM

---

php_phongo.c
src/MongoDB/Server.c
tests/server/server-executeCommand-002.phpt
tests/server/server-executeCommand_error-001.phpt
tests/server/server-executeQuery-005.phpt
tests/server/server-executeQuery_error-001.phpt

https://jira.mongodb.org/browse/PHPC-381

PHPC-381: Server::executeQuery/Command() should take a read preference

---

src/MongoDB/WriteConcern.c
tests/writeConcern/writeconcern-ctor_error-001.phpt
tests/writeConcern/writeconcern-ctor_error-002.phpt
tests/writeConcern/writeconcern-ctor_error-003.phpt
tests/writeConcern/writeconcern-ctor_error-004.phpt
tests/writeConcern/writeconcern-getw-001.phpt
tests/writeConcern/writeconcern-getwtimeout-001.phpt

* https://jira.mongodb.org/browse/PHPC-425
* https://jira.mongodb.org/browse/PHPC-426

PHPC-425 and PHPC-426: WriteConcern ctor arg handling and validation

---

php_phongo.c
php_phongo.h
src/MongoDB/Query.c
tests/query/bug0430-001.phpt
tests/query/bug0430-002.phpt
tests/query/bug0430-003.phpt

https://jira.mongodb.org/browse/PHPC-430

PHPC-430: Fix corruption of Query arguments

---

src/MongoDB/WriteResult.c

https://jira.mongodb.org/browse/PHPC-454

PHPC-454: Remove WriteResult::getInfo() method

---

tests/connect/standalone-x509-0001.phpt
tests/connect/standalone-x509-0002.phpt
tests/connect/standalone-x509-0003.phpt
tests/connect/standalone-x509-0004.phpt
tests/connect/standalone-x509-error-0001.phpt

https://jira.mongodb.org/browse/PHPC-407

PHPC-407: Rename X509 error test and fix cert path

---

php_phongo.h
scripts/convert-mo-tests.php
src/MongoDB/BulkWrite.c
src/MongoDB/Manager.c
tests/bulk/write-0002.phpt
tests/cluster/rs/connection/read/primary-available.phpt
tests/cluster/rs/connection/read/primary-not-available.phpt
tests/cluster/rs/connection/write/primary-available.phpt
tests/cluster/rs/connection/write/primary-not-available.phpt
tests/cluster/rs/connection/write/primary-restarted.phpt
tests/cluster/rs/discovery/remove-all-add-members.phpt
tests/cluster/rs/discovery/stepped-down-primary-triggers-refresh.phpt
tests/cluster/sharded/connection/all-mongos-available.phpt
tests/cluster/sharded/connection/no-mongos-available.phpt
tests/cluster/single/connection/read/standalone-available.phpt
tests/cluster/single/connection/read/standalone-not-available.phpt
tests/cluster/single/connection/read/standalone-restarted.phpt
tests/cluster/single/connection/write/standalone-available.phpt
tests/cluster/single/connection/write/standalone-not-available.phpt
tests/cluster/single/connection/write/standalone-restarted.phpt
tests/manager/manager-executeBulkWrite-002.phpt
tests/manager/manager-executeBulkWrite-003.phpt
tests/manager/manager-executeBulkWrite-004.phpt
tests/manager/manager-executeInsert_error-002.phpt
tests/replicaset/bug0155.phpt
tests/standalone/write-error-001.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-444

PHPC-444: Support options array in BulkWrite and executeInsert()

---

config.m4

libmongoc 1.3 is not compatible

---

scripts/presets/standalone-30.json
scripts/start-servers.php
scripts/ubuntu/mongo-orchestration-config.json
scripts/ubuntu/mongo-orchestration.sh
tests/utils/basic.inc

https://jira.mongodb.org/browse/PHPC-450

PHPC-450: Use MongoDB 3.2 stable for testing

---

src/MongoDB/BulkWrite.c
tests/manager/manager-executeBulkWrite-011.phpt

https://jira.mongodb.org/browse/PHPC-443

PHPC-443: Support "bypassDocumentValidation" option in BulkWrite

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-508

PHPC-508: Construct valid stream URI for IPv6 literals

---

src/MongoDB/Manager.c
tests/manager/manager-ctor-002.phpt

https://jira.mongodb.org/browse/PHPC-509

PHPC-509: Default Manager URI to "mongodb://localhost:27017/"

---

src/BSON/ObjectID.c
tests/bson/bson-objectid-002.phpt
tests/bson/bson-objectid-003.phpt

https://jira.mongodb.org/browse/PHPC-538

PHPC-538: ObjectID should not abort on null ctor arg

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-563

PHPC-563: Remove undocumented Manager "hosts" URI option

---

php_phongo.c
tests/manager/manager-getreadconcern-001.phpt

https://jira.mongodb.org/browse/PHPC-523

PHPC-523: Parse readconcernlevel in URI options array

---

config.m4

https://jira.mongodb.org/browse/PHPC-567

PHPC-567: Upgrade libbson and libmongoc to 1.3.3

---

php_phongo.c
src/MongoDB/Manager.c
tests/manager/manager-executeBulkWrite_error-007.phpt
tests/manager/manager-executeCommand_error-001.phpt
tests/manager/manager-executeQuery_error-001.phpt
tests/manager/manager-selectserver_error-001.phpt

https://jira.mongodb.org/browse/PHPC-553

PHPC-553: Suppress PHP warnings during stream init

---

src/BSON/ObjectID.c
tests/bson/bson-objectid-003.phpt
tests/bson/bson-objectid-004.phpt

https://jira.mongodb.org/browse/PHPC-620

PHPC-620: Lowercase hexadecimal strings in ObjectID ctor

---

config.m4

https://jira.mongodb.org/browse/PHPC-657

PHPC-657: Support MONGOC_NO_AUTOMATIC GLOBALS configure flag

---

php_phongo.c
src/MongoDB/WriteConcern.c

https://jira.mongodb.org/browse/PHPC-604
Depends on https://github.com/mongodb/mongo-php-driver/pull/276 ([PHPC-629](https://jira.mongodb.org/browse/PHPC-629)).

PHPC-604: Use mongoc_write_concern_journal_is_set()

---

src/MongoDB/BulkWrite.c

https://jira.mongodb.org/browse/PHPC-663

PHPC-663: Use mongoc_bulk_operation_get_write_concern()

---

src/MongoDB/WriteConcern.c

https://jira.mongodb.org/browse/PHPC-664

PHPC-664: Use mongoc_write_concern_get_w()

---

config.m4

See: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Setting-Output-Variables.html

Consolidate shell variable assignments with AC_SUBST()

---

src/MongoDB/Cursor.c

https://jira.mongodb.org/browse/PHPC-601

PHPC-601: Cursor::getServer() should not access mongoc_cursor_t.client

---

php_phongo.c
src/MongoDB/Cursor.c
src/MongoDB/ReadPreference.c

https://jira.mongodb.org/browse/PHPC-603

PHPC-603: Use mongoc_read_prefs_t getters

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-602

PHPC-602: Create command cursors with mongoc_cursor_new_from_command_reply()

---

src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-606

PHPC-606: Use mongoc_server_description_id()

---

src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-609

PHPC-609: Use mongoc_client_get_uri() in Manager debug handler

---

tests/standalone/bug0487-002.phpt

https://jira.mongodb.org/browse/PHPC-487

Fix expected exception message for PHPC-487 test case

---

config.m4
php_phongo.c
php_phongo.h
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/BulkWrite.c
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/ReadConcern.c
src/MongoDB/Server.c
src/MongoDB/WriteConcern.c
src/MongoDB/WriteResult.c

https://jira.mongodb.org/browse/PHPC-665

PHPC-665: Remove private libmongoc and libbson header includes

---

php_phongo.c
php_phongo.h
php_phongo_classes.h
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/Server.c
src/MongoDB/WriteResult.c
tests/cursor/bug0671-001.phpt
tests/server/bug0671-002.phpt
tests/writeResult/bug0671-003.phpt

https://jira.mongodb.org/browse/PHPC-671

PHPC-671: Avoid mongoc_client_t use-after-free by Cursor and Server

---

phongo_compat.h
php_phongo.c
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/Manager.c
tests/manager/bug0572.phpt

https://jira.mongodb.org/browse/PHPC-572

PHPC-572: Keep stream context options alive for Manager's lifetime

---

tests/cursor/cursor-IteratorIterator-003.phpt
tests/cursor/cursor-IteratorIterator-004.phpt

This includes expectations based on libmongoc behavior, which was recently updated in [CDRIVER-1234](https://jira.mongodb.org/browse/CDRIVER-1234).

Test cursor iteration beyond last document for CDRIVER-1234

---

php_phongo.c
tests/connect/bug0720.phpt

https://jira.mongodb.org/browse/PHPC-720

PHPC-720: Do not persist SSL streams to avoid SSL reinitialization errors

---

php_phongo.c
php_phongo_structs.h
src/BSON/Javascript.c
src/bson.c
tests/bson/bson-javascript-002.phpt
tests/bson/bson-javascript-003.phpt
tests/bson/bson-javascript-set_state-001.phpt

https://jira.mongodb.org/browse/PHPC-739

PHPC-739: Rename "javascript" to "code" in Javascript BSON class

---

src/MongoDB/CursorId.c
tests/functional/cursorid-001.phpt

https://jira.mongodb.org/browse/PHPC-748

PHPC-748: Fix CursorID::__toString() and var_dump() for 32-bit

---

src/BSON/UTCDateTime.c

Noticed both of these issues while compiling on Windows 32-bit.

UTCDateTime build issue fixes

---

.github/PULL_REQUEST_TEMPLATE.md

The standard issue template was sufficient.

Remove PR issue template

---

src/BSON/Binary.c
src/BSON/Decimal128.c
src/BSON/Javascript.c
src/BSON/MaxKey.c
src/BSON/MinKey.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c

https://jira.mongodb.org/browse/PHPC-789
Depends on https://github.com/mongodb/mongo-php-driver/pull/391

PHPC-789: Remove __wakeup from BSON/* classes

---

config.m4

https://jira.mongodb.org/browse/PHPC-757

PHPC-757: Set compiler name and user CFLAGS/LDFLAGS earlier

---

tests/readPreference/bug0146-001.phpt
tests/replicaset/writeresult-getserver-002.phpt
tests/writeResult/writeresult-debug-002.phpt

https://jira.mongodb.org/browse/PHPC-498
These test fixes were missed in mongodb/mongo-php-driver#413.

PHPC-498: Fix expected output for ReadPreference and WriteConcern

---

tests/query/bug0705-001.phpt
tests/query/bug0705-002.phpt

https://jira.mongodb.org/browse/PHPC-705

PHPC-705: Regression tests for superfluous $query wrapping

---

src/MongoDB/Query.c
tests/query/query-ctor-006.phpt

https://jira.mongodb.org/browse/PHPC-805

PHPC-805: Query "partial" option is now "allowPartialResults"

---

tests/writeConcernError/writeconcernerror-debug-001.phpt
tests/writeConcernError/writeconcernerror-debug-002.phpt
tests/writeConcernError/writeconcernerror-getcode-001.phpt
tests/writeConcernError/writeconcernerror-getinfo-001.phpt
tests/writeConcernError/writeconcernerror-getinfo-002.phpt
tests/writeConcernError/writeconcernerror-getmessage-001.phpt
tests/writeError/writeerror-debug-001.phpt
tests/writeError/writeerror-getCode-001.phpt
tests/writeError/writeerror-getIndex-001.phpt
tests/writeError/writeerror-getInfo-001.phpt
tests/writeError/writeerror-getMessage-001.phpt
tests/writeResult/writeresult-debug-002.phpt
tests/writeResult/writeresult-getdeletedcount-001.phpt
tests/writeResult/writeresult-getdeletedcount-002.phpt
tests/writeResult/writeresult-getinsertedcount-001.phpt
tests/writeResult/writeresult-getinsertedcount-002.phpt
tests/writeResult/writeresult-getmatchedcount-001.phpt
tests/writeResult/writeresult-getmatchedcount-002.phpt
tests/writeResult/writeresult-getmodifiedcount-001.phpt
tests/writeResult/writeresult-getmodifiedcount-002.phpt
tests/writeResult/writeresult-getmodifiedcount-003.phpt
tests/writeResult/writeresult-getserver-001.phpt
tests/writeResult/writeresult-getupsertedcount-001.phpt
tests/writeResult/writeresult-getupsertedcount-002.phpt
tests/writeResult/writeresult-getupsertedids-001.phpt
tests/writeResult/writeresult-getwriteconcernerror-001.phpt
tests/writeResult/writeresult-getwriteerrors-001.phpt
tests/writeResult/writeresult-getwriteerrors-002.phpt
tests/writeResult/writeresult-isacknowledged-001.phpt

https://jira.mongodb.org/browse/PHPC-653

PHPC-653: Tests for WriteResult and error classes

---

php_bson.h
php_phongo.c
php_phongo.h
src/bson.c

https://jira.mongodb.org/browse/PHPC-533

PHPC-533: Remove PHONGO_API macro for exported functions

---

src/BSON/Binary.c
src/BSON/Javascript.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bson-binary-compare-001.phpt
tests/bson/bson-binary-compare-002.phpt
tests/bson/bson-javascript-compare-001.phpt
tests/bson/bson-javascript-compare-002.phpt
tests/bson/bson-maxkey-compare-001.phpt
tests/bson/bson-minkey-compare-001.phpt
tests/bson/bson-objectid-compare-001.phpt
tests/bson/bson-objectid-compare-002.phpt
tests/bson/bson-regex-compare-001.phpt
tests/bson/bson-regex-compare-002.phpt
tests/bson/bson-timestamp-compare-001.phpt
tests/bson/bson-utcdatetime-compare-001.phpt

https://jira.mongodb.org/browse/PHPC-654

PHPC-654: Comparison handlers for BSON types

---

config.w32

https://jira.mongodb.org/browse/PHPC-853
https://jira.mongodb.org/browse/PHPC-852

PHPC-852 and PHPC-853: Windows build fixes

---

php_phongo.c
php_phongo.h

https://jira.mongodb.org/browse/PHPC-854

PHPC-854: Client persistence crashes with ZTS (e.g. Apache)

---

php_phongo.c
src/MongoDB/Manager.c
src/MongoDB/ReadPreference.c
tests/manager/bug0851-001.phpt
tests/manager/bug0851-002.phpt
tests/readPreference/bug0851-001.phpt

https://jira.mongodb.org/browse/PHPC-851

PHPC-851: Separate argument zvals before modification

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-885

PHPC-885: Alphabetize Regex flags when instantiating from BSON

---

phongo_compat.h
php_bson.h
src/bson.c
tests/bson/bson-toPHP-004.phpt

https://jira.mongodb.org/browse/PHPC-883

PHPC-883: BSON array keys should be disregarded during visitation

---

php_phongo.c
php_phongo_classes.h
src/BSON/Binary.c
src/BSON/Decimal128.c
src/BSON/Javascript.c
src/BSON/MaxKey.c
src/BSON/MinKey.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c

https://jira.mongodb.org/browse/PHPC-878
https://jira.mongodb.org/browse/PHPC-879
Supersedes https://github.com/mongodb/mongo-php-driver/pull/480.

PHPC-878, PHPC-879: Fetch JSON and Date class entries during MINIT

---

tests/replicaset/bug0898-001.phpt
tests/replicaset/bug0898-002.phpt

https://jira.mongodb.org/browse/PHPC-898
Fixes #516

PHPC-898: readConcern option should not be included in getMore commands

---

php_phongo.c
php_phongo.h
tests/manager/bug0912-001.phpt

https://jira.mongodb.org/browse/PHPC-912
Related to #479 and #527

PHPC-912: Do not destroy persisted clients created by other processes

---

php_phongo.c
tests/manager/manager-ctor-read_preference-004.phpt

https://jira.mongodb.org/browse/PHPC-901

PHPC-901: False slaveOk URI option should be ignored

---

tests/cursor/bug0732-001.phpt

https://jira.mongodb.org/browse/PHPC-732

PHPC-732: Regression test for use-after-free with Cursor wrapped in generator

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-931

PHPC-931: Ensure php_phongo_pclient_t is freed during MSHUTDOWN

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-930

PHPC-930: Log instead of throwing exceptions for critical/error levels

---

src/bson.c

https://jira.mongodb.org/browse/PHPC-933

PHPC-933: Remove unnecessary zend_string_release()

---

bin/prep-release.php

https://jira.mongodb.org/browse/PHPC-928

PHPC-928: Sync release files in PECL package generation script

---

php_phongo_structs.h
src/MongoDB/CursorId.c

https://jira.mongodb.org/browse/PHPC-951

PHPC-951: CursorId is a signed 64-bit integer

---

src/bson-encode.c
tests/cursorid/cursorid-001.phpt
tests/cursorid/cursorid-002.phpt

https://jira.mongodb.org/browse/PHPC-587

PHPC-587: CursorId should serialize to BSON as 64-bit integer

---

config.m4
config.w32
php_bson.h
php_phongo.c
php_phongo_classes.h
src/BSON/TypeWrapper.c
src/MongoDB/Cursor.c
src/bson-encode.c
src/bson.c
tests/bson/bson-fromPHP-007.phpt
tests/bson/bson-fromPHP_error-008.phpt
tests/bson/bson-toPHP-005.phpt
tests/bson/bson-toPHP_error-007.phpt
tests/cursor/cursor-setTypeMap_error-001.phpt
tests/cursor/cursor-setTypeMap_error-002.phpt
tests/cursor/cursor-setTypeMap_error-003.phpt

https://jira.mongodb.org/browse/PHPC-640
https://jira.mongodb.org/browse/PHPC-937
Related:
* https://github.com/mongodb/mongo-hhvm-driver/blob/master/serialization.rst#scalar-types
* https://github.com/mongodb/mongo-hhvm-driver/pull/111

PHPC-640: Implement interfaces for userland BSON type classes

---

php_bson.h
src/MongoDB/Server.c
src/bson.c
tests/server/server-getInfo-001.phpt
tests/server/server-getTags-001.phpt
tests/server/server-getTags-002.phpt

https://jira.mongodb.org/browse/PHPC-692

PHPC-692: Check for phongo_bson_to_zval_ex() failures in Server methods

---

src/MongoDB/BulkWrite.c
src/bson-encode.c
tests/bulk/bulkwrite-insert-004.phpt

https://jira.mongodb.org/browse/PHPC-382
https://jira.mongodb.org/browse/PHPC-471

PHPC-382, PHPC-471: Always return "_id" from BulkWrite::insert()

---

php_phongo.c
php_phongo_structs.h
src/MongoDB/Query.c
tests/cursor/cursor-tailable-003.phpt
tests/query/query-ctor_error-005.phpt
tests/query/query-ctor_error-006.phpt

https://jira.mongodb.org/browse/PHPC-839

PHPC-839: Support maxAwaitTimeMS Query option for tailable await cursors

---

src/MongoDB/WriteResult.c
tests/writeResult/writeresult-getupsertedids-001.phpt
tests/writeResult/writeresult-getupsertedids-002.phpt

https://jira.mongodb.org/browse/PHPC-624

PHPC-624: Support additional types in WriteResult::getUpsertedIds()

---

tests/manager/manager-ctor-read_preference-error-002.phpt

Type appears to have been introduced in 43b06f0ca304e0218b7078eca12fa74b71e08dc1

Fix typo in test title

---

src/MongoDB/ReadConcern.c
src/MongoDB/WriteConcern.c
tests/readConcern/readconcern-isdefault-001.phpt
tests/writeConcern/writeconcern-isdefault-001.phpt

https://jira.mongodb.org/browse/PHPC-976

PHPC-976: isDefault() method for read and write concerns

---

php_phongo.c
php_phongo.h
src/MongoDB/Monitoring.c
tests/apm/bug0950-001.phpt
tests/apm/bug0950-002.phpt

https://jira.mongodb.org/browse/PHPC-950

PHPC-950: Skip APM callbacks if subscriber HashTable is uninitialized

---

src/BSON/Timestamp.c
tests/bson/bson-timestamp-getIncrement-001.phpt
tests/bson/bson-timestamp-getTimestamp-001.phpt

https://jira.mongodb.org/browse/PHPC-985

PHPC-985: Timestamp::getIncrement() and getTimestamp() methods

---

bin/prep-release.php
config.m4

https://jira.mongodb.org/browse/PHPC-349
https://jira.mongodb.org/browse/PHPC-981
Fixes build issues noticed while creating the 1.3.0beta1 PECL package.

PHPC-349 and PHPC-981: Fix package builds for APM

---

tests/readConcern/readconcern-isdefault-001.phpt
tests/writeConcern/writeconcern-isdefault-001.phpt

https://jira.mongodb.org/browse/PHPC-976

PHPC-976: Add more test cases for default read and write concerns

---

tests/bson/bug1006-001.phpt
tests/bson/bug1006-002.phpt

https://jira.mongodb.org/browse/PHPC-1006

PHPC-1006: Fix test name and add extra regression test

---

src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-update-arrayFilters-001.phpt
tests/command/findAndModify-001.phpt
tests/command/update-001.phpt

https://jira.mongodb.org/browse/PHPC-975
Adds test cases, and also upgrades libbson and libmongoc to 1.9.0-dev.

PHPC-975: Array Update Improvements

---

php_phongo.c
php_phongo.h
src/MongoDB/Manager.c
src/MongoDB/Server.c
tests/manager/manager-executeBulkWrite-012.phpt
tests/manager/manager-executeBulkWrite_error-009.phpt
tests/manager/manager-executeCommand-002.phpt
tests/manager/manager-executeCommand-003.phpt
tests/manager/manager-executeCommand_error-002.phpt
tests/manager/manager-executeQuery-003.phpt
tests/manager/manager-executeQuery-004.phpt
tests/manager/manager-executeQuery-005.phpt
tests/manager/manager-executeQuery_error-002.phpt
tests/server/server-executeBulkWrite-006.phpt
tests/server/server-executeBulkWrite-007.phpt
tests/server/server-executeBulkWrite_error-002.phpt
tests/server/server-executeCommand-004.phpt
tests/server/server-executeCommand-005.phpt
tests/server/server-executeCommand_error-001.phpt
tests/server/server-executeQuery-009.phpt
tests/server/server-executeQuery-010.phpt
tests/server/server-executeQuery_error-001.phpt

Requires work that fixes the tests from an earlier commit.

PHPC-1042: Support options array for BulkWrite, Command, and Query execute methods

---

tests/session/session-003.phpt

https://jira.mongodb.org/browse/PHPC-980

PHPC-980: Use correct topology constant in CLEANUP()

---

tests/manager/manager-executeCommand_error-004.phpt

https://jira.mongodb.org/browse/PHPC-1037

PHPC-1037: Bump libbson and libmongoc to 1.9.0

---

config.w32

https://jira.mongodb.org/browse/PHPC-1037

PHPC-1037: Define new constants in config.w32

---

config.m4

https://jira.mongodb.org/browse/PHPC-1037

PHPC-1037: Update pkg-config requirement for 1.9.0

---

tests/causal-consistency/causal-consistency-010.phpt
tests/causal-consistency/causal-consistency-011.phpt
tests/causal-consistency/causal-consistency-012.phpt

https://jira.mongodb.org/browse/PHPC-987

PHPC-987: Additional causal consistency spec tests

---

config.m4

https://jira.mongodb.org/browse/PHPC-1096

 PHPC-1096: Allow building with libmongoc's bundled zlib

---

src/MongoDB/Session.c

These are a few fixes I came up with while writing the Session docs last week.

Fix Session protos

---

php_phongo.c
tests/apm/overview.phpt
tests/standalone/write-error-001.phpt

https://jira.mongodb.org/browse/PHPC-1090

PHPC-1090: Clean up switch statements for exception class selection

---

tests/manager/manager-set-uri-options-002.phpt

https://jira.mongodb.org/browse/PHPC-332

Update Exception expectations for manager-set-uri-options-002

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1091

PHPC-1091: Ensure ExecutionTimeoutException selection only considers server error code

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1143

PHPC-1143: Select ServerException for MONGOC_ERROR_WRITE_CONCERN domain

---

src/MongoDB/Query.c
tests/query/query-ctor-002.phpt
tests/query/query-ctor-003.phpt
tests/query/query-ctor-004.phpt

http://jira.mongodb.org/browse/PHPC-1137
http://jira.mongodb.org/browse/PHPC-1138

PHPC-1137/PHPC-1138 Deprecate maxScan and snapshot options

---

php_phongo.c
src/BSON/functions.c
src/MongoDB/Cursor.c
src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-1160

PHPC-1160: Initialize bson_error_t structs to zero

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1149

PHPC-1149: php_phongo_dispatch_handlers() should break if exception is thrown

---

tests/bulk/bulkwrite-delete_error-004.phpt
tests/bulk/bulkwrite-update-002.phpt
tests/bulk/bulkwrite-update_error-006.phpt
tests/bulk/bulkwrite-update_error-007.phpt

https://jira.mongodb.org/browse/PHPC-1196
This depends on the bump to libmongoc 1.11 in https://github.com/mongodb/mongo-php-driver/pull/860.

PHPC-1196: Test for unsupported collation and arrayFilters Bulk options

---

php_phongo.c
tests/session/transaction-integration-003.phpt

https://jira.mongodb.org/browse/PHPC-1229

PHPC-1229: Populate error labels for bulk write exceptions

---

config.m4
config.w32

https://jira.mongodb.org/browse/PHPC-1251

PHPC-1251: Upgrade libmongoc to 1.12.0

---

CONTRIBUTING.md

https://jira.mongodb.org/browse/PHPC-1250

PHPC-1250: Best practices for SKIPIF and improve Testing docs

---

scripts/autotools/libmongoc/CheckSSL.m4

PHPC-1241: OpenSSL 1.1 not found if pkg-config is not available

---

tests/server/server-executeCommand-007.phpt
tests/server/server-executeQuery-011.phpt

https://jira.mongodb.org/browse/PHPC-691

PHPC-691: Test Server execute methods send RP to mongos

---

.travis.yml

https://jira.mongodb.org/browse/PHPC-1333

PHPC-1333: Use virtualized Xenial image in Travis CI

---

src/MongoDB/ReadPreference.c
tests/readPreference/readpreference-set_state_error-001.phpt
tests/readPreference/readpreference-set_state_error-002.phpt

https://jira.mongodb.org/browse/PHPC-1331

PHPC-1331: Fix typos in ReadPreference exception messages

---

.appveyor.yml
src/contrib/php_array_api.h
tests/bson/bson-toJSON-001.phpt

https://jira.mongodb.org/browse/PHPC-1329
Related: https://github.com/sgolemon/php-array-api/pull/3

PHPC-1329: Fix Windows build failures on AppVeyor

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-869

PHPC-869: Use macOS 10.14 host

---

.travis.yml

https://jira.mongodb.org/browse/PHPC-1333

PHPC-1333: Use distro-specific server binaries

---

tests/retryable-writes/retryable-writes-004.phpt

https://jira.mongodb.org/browse/PHPC-1341

PHPC-1341: Remove XFAIL for w:0 retryable write test

---

php_phongo_structs.h
src/MongoDB/Cursor.c

https://jira.mongodb.org/browse/PHPC-1301

PHPC-1301: Use bool for php_phongo_cursor_t.got_iterator

---

src/MongoDB/Exception/Exception.c
tests/cursor/cursorinterface-002.phpt
tests/exception/exception-001.phpt

https://jira.mongodb.org/browse/PHPC-1307

PHPC-1307: Exception interface extends Throwable

---

tests/manager/manager-executeBulkWrite-012.phpt
tests/server/server-executeBulkWrite-002.phpt
tests/server/server-executeBulkWrite-003.phpt
tests/server/server-executeBulkWrite-005.phpt
tests/server/server-executeBulkWrite-006.phpt

https://jira.mongodb.org/browse/PHPC-1364

PHPC-1364: Remove XFAIL for issue fixed in libmongoc 1.14

---

php_phongo.c
php_phongo.h
tests/bulk/bulkwrite-delete_error-004.phpt
tests/bulk/bulkwrite-update_error-006.phpt
tests/bulk/bulkwrite-update_error-007.phpt
tests/connect/standalone-auth_error-001.phpt
tests/manager/manager-executeBulkWrite_error-005.phpt
tests/manager/manager-executeBulkWrite_error-011.phpt
tests/manager/manager-set-uri-options-001.phpt
tests/utils/skipif.php

https://jira.mongodb.org/browse/PHPC-1373

PHPC-1373: Accessible WriteResult for executeBulkWrite socket error

---

bin/prep-release.php

https://jira.mongodb.org/browse/PHPC-1364

PHPC-1364: Include LIBMONGOC_VERSION_CURRENT in PECL package

---

tests/standalone/connectiontimeoutexception-001.phpt

https://jira.mongodb.org/browse/PHPC-1392

PHPC-1392: Bump socketTimeoutMS to avoid spurious failure

---

tests/standalone/connectiontimeoutexception-001.phpt

https://jira.mongodb.org/browse/PHPC-1392

PHPC-1392: Fix error assertion for server 3.0 through 3.4

---

tests/cursor/cursor-getmore-005.phpt
tests/cursor/cursor-getmore-006.phpt
tests/cursor/cursor-getmore-007.phpt
tests/cursor/cursor-getmore-008.phpt
tests/utils/skipif.php

https://jira.mongodb.org/browse/PHPC-1414

PHPC-1414: Skip tests when mongo orchestration is not available

---

tests/session/session-commitTransaction-001.phpt

https://jira.mongodb.org/browse/PHPC-1319

PHPC-1319: commitTransaction applies w:majority when retrying

---

.evergreen/config.yml
.evergreen/run-orchestration.sh

https://jira.mongodb.org/browse/PHPC-1415

PHPC-1415: Disable retryWrites for non-RS sharded cluster on Evergreen

---

php_phongo.c
tests/manager/manager-ctor-duplicate-option-001.phpt
tests/manager/manager-ctor-duplicate-option-002.phpt
tests/manager/manager-ctor-duplicate-option-003.phpt
tests/manager/manager-ctor-duplicate-option-004.phpt

http://jira.mongodb.org/browse/PHPC-991

PHPC-991: Handle duplicates in URI options array

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1461

PHPC-1461: Remove Community zSeries from 4.0 testing

---

tests/bson/bson-fromPHP-002.phpt
tests/bson/bson-fromPHP-003.phpt
tests/bson/bson-fromPHP_error-003.phpt
tests/bson/bson-utcdatetime-001.phpt
tests/bson/bson-utcdatetime-tostring-001.phpt

https://jira.mongodb.org/browse/PHPC-1470

PHPC-1470: Remove unnecessary timezone settings in tests

---

.travis.scripts/debug-core.sh

This fixes a bug originally introduced by df9c278d3715370ff1bb20b3827763f2bc742b30 in #736.

Fix logic for OS check

---

config.w32

https://jira.mongodb.org/browse/PHPC-1521

PHPC-1521: Only warn when SASL enabled but not available

---

src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-update-004.phpt
tests/bulk/bulkwrite-update_error-003.phpt
tests/bulk/bulkwrite-update_error-008.phpt

https://jira.mongodb.org/browse/PHPC-1462

PHPC-1462: Support hint for update commands

---

src/MongoDB/Query.c
tests/query/query-ctor-002.phpt

https://jira.mongodb.org/browse/PHPC-1525

PHPC-1525: Deprecate oplogReplay query option

---

CREDITS
bin/prep-release.php
template.rc

Update CREDITS, which is used by template.rc (PHP's confutils.js parses it).
Add CONTRIBUTING.md and THIRD_PARTY_NOTICES to PECL package.

Update CREDITS, template.rc, and add contrib/third-party info to package

---

php_phongo.c
tests/manager/manager-ctor-directconnection-error-001.phpt
tests/manager/manager-ctor-directconnection-error-002.phpt

https://jira.mongodb.org/browse/PHPC-1648
Extra commit has code formatting changes that were made when I ran the `make` task.

PHPC-1648: Validate directConnection in URI options array

---

tests/manager/manager-executeBulkWrite-014.phpt
tests/manager/manager-executeCommand-007.phpt
tests/manager/manager-executeQuery-006.phpt
tests/manager/manager-executeQuery-007.phpt
tests/manager/manager-executeReadCommand-002.phpt
tests/manager/manager-executeReadCommand-003.phpt
tests/manager/manager-executeReadWriteCommand-001.phpt
tests/manager/manager-executeReadWriteCommand-002.phpt
tests/manager/manager-executeReadWriteCommand-003.phpt
tests/manager/manager-executeWriteCommand-002.phpt
tests/manager/manager-executeWriteCommand-003.phpt
tests/server/server-executeBulkWrite-009.phpt
tests/server/server-executeCommand-010.phpt
tests/server/server-executeQuery-012.phpt
tests/server/server-executeQuery-013.phpt
tests/server/server-executeReadCommand-002.phpt
tests/server/server-executeReadCommand-003.phpt
tests/server/server-executeReadWriteCommand-002.phpt
tests/server/server-executeReadWriteCommand-003.phpt
tests/server/server-executeWriteCommand-002.phpt
tests/server/server-executeWriteCommand-003.phpt

https://jira.mongodb.org/browse/PHPC-169

PHPC-169: Test read and write concern inheritance

---

src/MongoDB/ReadPreference.c
tests/readPreference/bug1698-001.phpt

https://jira.mongodb.org/browse/PHPC-1698

PHPC-1698: fix prep_tagsets leak for ReadPreference::__set_state

---

.appveyor.yml

PHPC-1695: Run appveyor tests on PHP 8

---

src/BSON/DBPointer.c

PHPC-1775
Extracted from #1199.

PHPC-1775 Use correct size for strncpy in when initialising DBPointer

---

src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-1801

PHPC-1801: Fix arginfo for Manager::selectServer

---

src/BSON/Binary.c
src/BSON/Decimal128.c
src/BSON/Javascript.c
src/BSON/MaxKey.c
src/BSON/MinKey.c
src/BSON/ObjectId.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
src/MongoDB/ReadConcern.c
src/MongoDB/ReadPreference.c
src/MongoDB/ServerApi.c
src/MongoDB/WriteConcern.c

https://jira.mongodb.org/browse/PHPC-1791

PHPC-1791: Specify correct return type in __set_state protos

---

.github/workflows/tests.yml

https://jira.mongodb.org/browse/PHPC-1849

Disable PHP 8.1 until PHPC-1849 is resolved

---

phongo_compat.h
src/BSON/Binary.c
src/BSON/DBPointer.c
src/BSON/Decimal128.c
src/BSON/Int64.c
src/BSON/Javascript.c
src/BSON/MaxKey.c
src/BSON/MinKey.c
src/BSON/ObjectId.c
src/BSON/Regex.c
src/BSON/Symbol.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
src/BSON/Undefined.c
src/MongoDB/BulkWrite.c
src/MongoDB/Cursor.c

https://jira.mongodb.org/browse/PHPC-1858
https://jira.mongodb.org/browse/PHPC-1933

PHPC-1858 and PHPC-1933: Return type info for interface implementations in PHP 8.1 

---

src/MongoDB/ServerDescription.c

https://jira.mongodb.org/browse/PHPC-1934

PHPC-1934: Check for uninitialized intern in ServerDescription get_properties_hash

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1931
Note: I've also updated the regexes for automatic patch builds in the Evergreen project configuration.

PHPC-1931: Add PHP 8.1 and rename OS axis labels

---

tests/replicaset/manager-selectserver-001.phpt
tests/replicaset/writeresult-getserver-002.phpt
tests/server/server-executeBulkWrite-005.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1878

PHPC-1878 and PHPC-2008: Fix tests using local database

---

php_phongo.c
tests/manager/manager-createClientEncryption-error-002.phpt
tests/manager/manager-ctor-auto_encryption-error-003.phpt

https://jira.mongodb.org/browse/PHPC-1912
https://jira.mongodb.org/browse/PHPC-2009
https://jira.mongodb.org/browse/PHPC-2010

PHPC-1912: CSFLE 1.0 KMIP Support

---

tests/bson/bson-fromJSON-003.phpt
tests/bson/bson-toJSON-003.phpt
tests/bson/bson-toPHP-012.phpt

https://jira.mongodb.org/browse/PHPC-1342

PHPC-1342: Regression tests for duplicate keys

---

src/MongoDB/Session.c
tests/session/session-debug-001.phpt
tests/session/session-debug-002.phpt
tests/session/session-debug-003.phpt
tests/session/session-debug-004.phpt
tests/session/session-debug-005.phpt
tests/session/session-debug-006.phpt
tests/session/session-debug-007.phpt
tests/session/session-isDirty-001.phpt

https://jira.mongodb.org/browse/PHPC-2003

PHPC-2003: Implement Session::isDirty()

---

src/MongoDB/Session.c
tests/session/session-debug-004.phpt

https://jira.mongodb.org/browse/PHPC-2032

PHPC-2032: Concise debug output for ended sessions

---

tests/causal-consistency/causal-consistency-001.phpt
tests/causal-consistency/causal-consistency-002.phpt
tests/causal-consistency/causal-consistency-003.phpt
tests/causal-consistency/causal-consistency-004.phpt
tests/causal-consistency/causal-consistency-005.phpt
tests/causal-consistency/causal-consistency-006.phpt
tests/causal-consistency/causal-consistency-007.phpt
tests/causal-consistency/causal-consistency-008.phpt
tests/causal-consistency/causal-consistency-009.phpt
tests/causal-consistency/causal-consistency-010.phpt
tests/causal-consistency/causal-consistency-011.phpt
tests/causal-consistency/causal-consistency-012.phpt

https://jira.mongodb.org/browse/PHPC-2036
Synced with mongodb/specifications@568093ce7f0e1394cf4952c417e1e7dacc5fef53
Adds missing prose test 7 and removes prose test 10. This also adds prose test references to all files.

PHPC-2036: Sync causal consistency tests

---

src/MongoDB/ClientEncryption.c
src/MongoDB/ClientEncryption.h
src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-2038

PHPC-2038: Init zval in phongo_clientencryption_init

---

CONTRIBUTING.md

https://jira.mongodb.org/browse/PHPC-2074

PHPC-2074: Document test suite env vars and revise Mongo Orchestration notes

---

src/MongoDB/ClientEncryption.c
src/phongo_bson_encode.c

https://jira.mongodb.org/browse/PHPC-2088
https://jira.mongodb.org/browse/PHPC-2089

PHPC-2088 and PHPC-2089: Various bson_value_t memory leaks

---

.evergreen/config.yml
.github/workflows/tests.yml

https://jira.mongodb.org/browse/PHPC-2086
Related to https://github.com/mongodb/mongo-php-library/pull/934

PHPC-2086: Add MongoDB 6.0 to GitHub CI matrix

---

src/phongo_execute.c
tests/command/cursor-comment-001.phpt

https://jira.mongodb.org/browse/PHPC-2094

PHPC-2094: Relay command comment when constructing a cursor

---

phongo_version.h
template.rc

https://jira.mongodb.org/browse/PHPC-2078

PHPC-2078: Move phongo_version.h back to repository root

---

.evergreen/config.yml
CONTRIBUTING.md
tests/clientEncryption/clientEncryption-createDataKey-001.phpt
tests/clientEncryption/clientEncryption-createDataKey_error-001.phpt
tests/clientEncryption/clientEncryption-ctor-001.phpt
tests/clientEncryption/clientEncryption-ctor_error-002.phpt
tests/clientEncryption/clientEncryption-decrypt-001.phpt
tests/clientEncryption/clientEncryption-encrypt-001.phpt
tests/cursor/bug1529-001.phpt
tests/manager/manager-createClientEncryption-001.phpt
tests/manager/manager-createClientEncryption-error-002.phpt
tests/manager/manager-ctor-auto_encryption-001.phpt
tests/manager/manager-ctor-auto_encryption-002.phpt
tests/manager/manager-ctor-auto_encryption-error-001.phpt
tests/manager/manager-ctor-auto_encryption-error-002.phpt
tests/manager/manager-ctor-auto_encryption-error-003.phpt
tests/manager/manager-ctor-auto_encryption-error-004.phpt
tests/manager/manager-ctor-disableClientPersistence-006.phpt
tests/manager/manager-ctor-disableClientPersistence-007.phpt
tests/manager/manager-ctor-disableClientPersistence_error-001.phpt
tests/manager/manager-getencryptedfieldsmap-001.phpt
tests/utils/basic.inc
tests/utils/skipif.php
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-2099
Patch build: https://spruce.mongodb.com/version/62b234960ae6060c2a85cd6b/tasks

PHPC-2099: crypt_shared testing

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-2137

PHPC-2137: Bump libmongoc-version in Evergreen config

---

src/BSON/Binary.stub.php
src/BSON/Binary_arginfo.h
src/BSON/Decimal128.stub.php
src/BSON/Decimal128_arginfo.h
src/BSON/Javascript.stub.php
src/BSON/Javascript_arginfo.h
src/BSON/MaxKey.stub.php
src/BSON/MaxKey_arginfo.h
src/BSON/MinKey.stub.php
src/BSON/MinKey_arginfo.h
src/BSON/ObjectId.stub.php
src/BSON/ObjectId_arginfo.h
src/BSON/Regex.stub.php
src/BSON/Regex_arginfo.h
src/BSON/Timestamp.stub.php
src/BSON/Timestamp_arginfo.h
src/BSON/UTCDateTime.stub.php
src/BSON/UTCDateTime_arginfo.h
src/MongoDB/CursorId.stub.php
src/MongoDB/CursorId_arginfo.h
src/MongoDB/ReadConcern.stub.php
src/MongoDB/ReadConcern_arginfo.h
src/MongoDB/ReadPreference.stub.php
src/MongoDB/ReadPreference_arginfo.h
src/MongoDB/ServerApi.stub.php
src/MongoDB/ServerApi_arginfo.h
src/MongoDB/WriteConcern.stub.php
src/MongoDB/WriteConcern_arginfo.h

https://jira.mongodb.org/browse/PHPC-1944

PHPC-1944: Add final modifier to __set_state methods

---

src/BSON/Binary.c
src/BSON/Binary.stub.php
src/BSON/Binary_arginfo.h
tests/bson/bson-binary-002.phpt
tests/bson/bson-binary_error-001.phpt

https://jira.mongodb.org/browse/PHPC-2101

PHPC-2101: Default Binary constructor parameter to TYPE_GENERIC

---

src/BSON/Binary.stub.php
src/BSON/Binary_arginfo.h
src/BSON/Int64.stub.php
src/BSON/Int64_arginfo.h
src/BSON/ObjectId.stub.php
src/BSON/ObjectId_arginfo.h
src/BSON/PersistableEnum.stub.php
src/BSON/PersistableEnum_arginfo.h
src/BSON/Regex.stub.php
src/BSON/Regex_arginfo.h
src/BSON/Timestamp.stub.php
src/BSON/Timestamp_arginfo.h
src/BSON/UTCDateTime.stub.php
src/BSON/UTCDateTime_arginfo.h
src/MongoDB/BulkWrite.stub.php
src/MongoDB/BulkWrite_arginfo.h
src/MongoDB/CursorId.stub.php
src/MongoDB/CursorId_arginfo.h

https://jira.mongodb.org/browse/PHPC-2136

PHPC-2136: Final modifier should precede method visibility in stub files

---

src/MongoDB/ClientEncryption.c
tests/clientEncryption/bug2149.phpt
tests/clientEncryption/clientEncryption-createDataKey_error-003.phpt
tests/clientEncryption/clientEncryption-rewrapManyDataKey_error-001.phpt
tests/clientEncryption/clientEncryption-rewrapManyDataKey_error-002.phpt

https://jira.mongodb.org/browse/PHPC-2148
https://jira.mongodb.org/browse/PHPC-2149
https://jira.mongodb.org/browse/PHPC-2151
These are a few issues I came across while writing the docs for key management API ([PHPC-2093](https://jira.mongodb.org/browse/PHPC-2093)).

Various small CSFLE fixes

---

scripts/autotools/libmongoc/CheckResolv.m4

https://jira.mongodb.org/browse/PHPC-2152
This fixes a bug inadvertently introduced in b581f2a3e43d7f8d22afaaebbb1ab2acb8636209.

PHPC-2152: Link libresolv when detecting res_nsearch

---

config.m4

Else, only test before comma is displayed

protect message to allow comma

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-2153
Patch build: https://spruce.mongodb.com/version/6361e4cc850e6163bafed0cc/tasks

PHPC-2153: Add PHP 8.2 to Evergreen matrix

---

config.m4
src/phongo_client.h

https://jira.mongodb.org/browse/PHPC-2166

PHPC-2166: Add -Wstrict-prototypes dev build flag and fix decl

---

.github/workflows/get-build-dir.bat
.github/workflows/releases.yml
.github/workflows/tests.yml
.github/workflows/wait-for-mongodb.bat
.github/workflows/windows-release-build.yml
CONTRIBUTING.md
tests/apm/commandFailedEvent-001.phpt
tests/apm/commandSucceededEvent-001.phpt
tests/manager/manager-ctor-auto_encryption-001.phpt
tests/utils/skipif.php

https://jira.mongodb.org/browse/PHPC-2143

PHPC-2143: Build Windows DLLs with GitHub Actions

---

src/MongoDB/WriteConcernError.c
tests/writeResult/writeresult-getwriteconcernerror-002.phpt

PHPC-2148: Fix null pointer access for write concern errors without a message

---

.github/workflows/tests.yml
.github/workflows/windows-release-build.yml

PHPC-2185: Windows builds for PHP 7.4

---

tests/clientEncryption/clientEncryption-ctor-002.phpt

PHPC-2188: Test that tlsDisableOCSPEndpointCheck is allowed in CSFLE options

---

src/phongo_bson.c
src/phongo_bson_encode.c
tests/bson/bson-document-fromPHP-004.phpt
tests/bulk/bulkwrite-delete-003.phpt
tests/bulk/bulkwrite-insert-002.phpt
tests/bulk/bulkwrite-update-005.phpt
tests/command/command-ctor-002.phpt
tests/query/query-ctor-007.phpt

https://jira.mongodb.org/browse/PHPC-2210
https://jira.mongodb.org/browse/PHPC-2211

PHPC-2210 and PHPC-2211: Fix direct BSON copy and toJson memory leak

---

src/phongo_bson_encode.c
tests/bulk/bulkwrite-insert-003.phpt

PHPC-2216
Test is named to not conflict with the new test added in #1415.

PHPC-2216: Generate _id field when inserting Document or PackedArray instances

---

.evergreen/config.yml

[PHPC-2226](https://jira.mongodb.org/browse/PHPC-2226)
Same as https://github.com/mongodb/mongo-php-library/commit/b70b2e3ffe573b1c46e776c46a2fb471035744ad

PHPC-2226: Test against MongoDB 7.0

---

src/BSON/Iterator.c

PHPC-2268: Remove duplicate call to bson_iter_key

---

src/phongo_bson_encode.c

Follow-up to PHPC-1000 to take care of https://github.com/mongodb/mongo-php-driver/pull/1449#pullrequestreview-1561537284

PHPC-1000: Add missing exception

---

src/BSON/functions.c
src/MongoDB/Monitoring/functions.c
src/MongoDB/ServerDescription_arginfo.h
src/MongoDB/Session_arginfo.h
src/MongoDB/TopologyDescription_arginfo.h
src/functions_arginfo.h

https://jira.mongodb.org/browse/PHPC-2283

PHPC-2283: Regenerate arginfo using PHP 8.2.10

---

bin/package.xml.in
config.m4
config.w32
scripts/autotools/libmongoc/CheckCompression.m4
scripts/autotools/libmongoc/CheckSSL.m4
scripts/autotools/libmongoc/CheckSasl.m4
scripts/autotools/libmongoc/CheckUtf8Proc.m4
scripts/autotools/m4/php_mongodb.m4
scripts/update-submodule-sources.php

This PR contains various commits for issues within the [PHPC-2256](https://jira.mongodb.org/browse/PHPC-2256) epic:
- https://jira.mongodb.org/browse/PHPC-1017
- https://jira.mongodb.org/browse/PHPC-1218
- https://jira.mongodb.org/browse/PHPC-2155
- https://jira.mongodb.org/browse/PHPC-2225
- https://jira.mongodb.org/browse/PHPC-2309
- https://jira.mongodb.org/browse/PHPC-2311
- https://jira.mongodb.org/browse/PHPC-2312
- https://jira.mongodb.org/browse/PHPC-2314
- https://jira.mongodb.org/browse/PHPC-2315
Fixes for previously merged PRs (also in 1.17):
- https://jira.mongodb.org/browse/PHPC-2300
- https://jira.mongodb.org/browse/PHPC-2302

PHPC-2256: Build configuration improvements

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-2322
Supersedes #1490

Remove ICU and add SRV to phpinfo() output

---

tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-2320

PHPC-2320: Remove pre-7.1 logic in json_canonicalize()

---

.evergreen/config/generated/build/build-libmongoc-8.2.yml
.evergreen/config/templates/build/build-libmongoc.yml
config.m4

This pulls in CDRIVER-4754, which is needed for PHPLIB-1297

Bump libmongoc to 1.26-dev

---

.evergreen/config.yml
.evergreen/config/generate-config.php
.evergreen/config/generated/build/build-libmongoc-8.3.yml
.evergreen/config/generated/build/build-php-8.3.yml
.evergreen/config/generated/test-variant/latest-php-8.3.yml
.evergreen/config/generated/test-variant/replicaset-php-7.4.yml
.evergreen/config/generated/test-variant/replicaset-php-8.0.yml
.evergreen/config/generated/test-variant/replicaset-php-8.1.yml
.evergreen/config/generated/test-variant/replicaset-php-8.2.yml
.evergreen/config/templates/test-variant/latest.yml
.evergreen/config/templates/test-variant/replicaset-only.yml

PHPC-2298
Includes a commit to test variants automatically based on PHP versions.

PHPC-2298: Test with PHP 8.3 on Evergreen

---

.evergreen/config/generated/build/build-libmongoc-8.3.yml
.evergreen/config/templates/build/build-libmongoc.yml
config.m4

https://jira.mongodb.org/browse/PHPC-2378

PHPC-2378: Update libmongoc to 1.27.1

---

.github/workflows/merge-up.yml

With this change, new merge-up pull requests will have auto-merge enabled (using the "merge" strategy). This streamlines the merge-up flow.

Enable auto-merge in merge-up workflow

---

bin/prep-release.php

https://jira.mongodb.org/browse/PHPC-2373

PHPC-2373: Include uthash in PECL package

---

.github/actions/windows/prepare-build/action.yml

https://jira.mongodb.org/browse/PHPC-2388

PHPC-2388: Install VC15 component for PHP 7.4

---

.github/actions/windows/prepare-build/action.yml

https://jira.mongodb.org/browse/PHPC-2388
Testing this out for @derickr (https://github.com/php/setup-php-sdk/pull/1#discussion_r1613559908).

PHPC-2388: Simplify steps for VC15 installation
