mongodb/mongo-php-driver

src/MongoDB/Result.c
tests/standalone/manager-executeCommand-001.phpt
tests/standalone/result-toArray-001.phpt
tests/standalone/result-toArray-002.phpt
tests/standalone/server-executeCommand-001.phpt
tests/utils/tools.php

* https://jira.mongodb.org/browse/PHPC-203
* https://jira.mongodb.org/browse/PHPC-204
----
This introduces a BC break in that toArray() no longer returns the first result document. It must now be manually unwrapped from the return value.

PHPC-203: Result::toArray() should proxy iterator_to_array($this)

---

php_phongo.c
php_phongo_classes.h
tests/readPreference/002.phpt
tests/standalone/cursor-getmore-001.phpt
tests/standalone/cursor-getmore-002.phpt
tests/standalone/cursor-getmore-003.phpt
tests/standalone/cursor-getmore-004.phpt
tests/standalone/cursor-iterator_handlers-001.phpt
tests/standalone/cursor-multiple_iterators-001.phpt
tests/standalone/cursor-multiple_iterators-002.phpt
tests/standalone/manager-executeCommand-001.phpt
tests/standalone/manager-executeQuery-001.phpt
tests/standalone/server-executeCommand-001.phpt

https://jira.mongodb.org/browse/PHPC-240

PHPC-240: Cannot iterate beyond command cursor's first batch

---

src/MongoDB/WriteResult.c

https://jira.mongodb.org/browse/PHPC-278
----
A test isn't included in the PR because we don't presently have 2.4 in the build matrix (see: [PHPC-279](https://jira.mongodb.org/browse/PHPC-279)).

PHPC-278: nModified may be null for legacy writes

---

src/bson.c
tests/bson/bson-encode-002.phpt
tests/bson/bson-encode_error-001.phpt
tests/bson/bson-encode_error-002.phpt
tests/bson/bug0274.phpt

* https://jira.mongodb.org/browse/PHPC-274
* https://jira.mongodb.org/browse/PHPC-275
----
Previously, only BSON\Persistable objects were handled.

PHPC-274: Fix zval_to_bson() encoding of BSON\Serializable objects

---

php_phongo.c
src/MongoDB/WriteConcern.c
tests/bulk/write-0002.phpt
tests/replicaset/writeresult-getserver-002.phpt
tests/standalone/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/standalone/writeresult-isacknowledged-002.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/writeConcern/writeconcern-001.phpt

* https://jira.mongodb.org/browse/PHPC-179
* https://jira.mongodb.org/browse/PHPC-280

PHPC-179 and PHPC-280: WriteConcern journal/fsync handling

---

src/bson.c
tests/bson/bson-encode_error-001.phpt
tests/bson/bson-encode_error-002.phpt

https://jira.mongodb.org/browse/PHPC-283

PHPC-283: UnexpectedValueException and bsonSerialize() cleanup

---

config.m4
src/MongoDB/BulkWrite.c

Notice: check use --atleast 1.1.5 when should be 1.2.0 but .pc in generated file (from git snapshot, 1.2.0-dev still report as 1.1.5-dev...)

PHPC-305: add --with-libmongo option

---

scripts/centos/ldap/install.sh

When building the VMs on Friday, I encountered some errors with selecting a mirror for the epel repository. Ultimately, I noticed that the LDAP VM doesn't actually depend on `python-pip`, which was the only reason we were installing epel. This removes them both.

LDAP VM does not require python-pip (or epel)

---

src/bson.c
tests/bson/bug0334.phpt

https://jira.mongodb.org/browse/PHPC-334

PHPC-334: Don't produce BSON with multiple __pclass fields

---

src/bson.c
tests/bson/bug0341.phpt

https://jira.mongodb.org/browse/PHPC-341

PHPC-341: Ensure bson_t is freed after decoding JSON

---

tests/bson/bug0334-001.phpt
tests/bson/bug0334-002.phpt

This PR builds upon #66 and depends on #64 to pass (re: `array` type map overriding `__pclass`).
----
The original test was problematic for HHVM, since it injects the __pclass value differently. Although changing the bsonSerialize() field order should ensure identical hex_dump() output on HHVM, we'll split the test cases.
See: fddd88ff9d83bc44fe610f832c5862cec0ffb23f

PHPC-334: Split hex_dump() test case

---

.travis.scripts/compile.sh
src/bson.c
tests/bson/bson-toPHP_error-002.phpt
tests/bson/bug0325.phpt
tests/bson/bug0347.phpt

* https://jira.mongodb.org/browse/PHPC-345
* https://jira.mongodb.org/browse/PHPC-347

Fix memory leak and change warnings to exceptions in bson_to_zval() 

---

src/BSON/Javascript.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bson-encode-003.phpt
tests/bson/bson-javascript-002.phpt
tests/bson/bson-regex-002.phpt
tests/bson/bson-timestamp-002.phpt
tests/bson/bson-utcdatetime-002.phpt
tests/bson/bson-utcdatetime-003.phpt
tests/manager/manager-var-dump-001.phpt
tests/server/server-debug.phpt

https://jira.mongodb.org/browse/PHPC-335

PHPC-335: Create debug handlers for BSON type classes

---

tests/bson/bson-binary-001.phpt
tests/bson/bson-binary_error-001.phpt
tests/bson/bson-javascript-001.phpt
tests/bson/bson-javascript_error-001.phpt
tests/bson/bson-objectid-001.phpt
tests/bson/bson-objectid_error-001.phpt
tests/bson/bson-regex-001.phpt
tests/bson/bson-regex_error-001.phpt
tests/bson/bson-timestamp-001.phpt
tests/bson/bson-timestamp_error-001.phpt
tests/bson/bson-utcdatetime-001.phpt
tests/bson/bson-utcdatetime_error-001.phpt

And we also add a cast because of HHVM not allowing current() on an object

Split tests for invalid arguments out into their own files, and ignore them for HHVM

---

src/bson.c

The key names aren't showing up because phongo_bson_append() is being passed a 0 length value.

Object property names missing due to lack of key length

---

src/MongoDB/Manager.c
tests/manager/manager-getservers-001.phpt
tests/manager/manager-getservers-002.phpt
tests/replicaset/manager-getservers-001.phpt

https://jira.mongodb.org/browse/PHPC-361

PHPC-361: Manager::getServers() should omit unknown servers

---

src/bson.c
tests/bson/bson-utcdatetime-001.phpt

https://jira.mongodb.org/browse/PHPC-408

PHPC-408: Ensure object_to_bson() always creates a BSON document

---

php_phongo.c
php_phongo.h
src/MongoDB/Manager.c
tests/manager/manager-getreadpreference-001.phpt
tests/manager/manager-getwriteconcern-001.phpt

https://jira.mongodb.org/browse/PHPC-417

PHPC-417: Return value objects from Manager RP/WC getters

---

src/bson.c
tests/bson/bson-fromPHP-002.phpt
tests/bson/bson-fromPHP-003.phpt
tests/bson/bson-fromPHP_error-002.phpt
tests/bson/bson-fromPHP_error-003.phpt
tests/bson/bson-utcdatetime-001.phpt
tests/bson/bson-utcdatetime-todatetime-001.phpt
tests/bson/bson-utcdatetime-tostring-001.phpt

https://jira.mongodb.org/browse/PHPC-410
Based on #102

PHPC-410: object_to_bson() behavior for non-stdClass and unsupported types

---

php_phongo.c
src/MongoDB/WriteConcern.c
tests/manager/manager-getwriteconcern-001.phpt
tests/replicaset/writeresult-getserver-002.phpt
tests/server/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/writeConcern/writeconcern-debug-001.phpt
tests/writeConcern/writeconcern-debug-002.phpt
tests/writeConcern/writeconcern-getw-001.phpt

https://jira.mongodb.org/browse/PHPC-423

PHPC-423: WriteConcern should report default "w" option as null

---

src/MongoDB/WriteConcern.c
tests/writeConcern/writeconcern-ctor-001.phpt
tests/writeConcern/writeconcern-getfsync-001.phpt
tests/writeConcern/writeconcern-getjournal-001.phpt

https://jira.mongodb.org/browse/PHPC-427

PHPC-427: Do not set WC journal/fsync to false for NULL args

---

src/BSON/Binary.c
src/BSON/Javascript.c
src/BSON/MaxKey.c
src/BSON/MinKey.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
src/MongoDB/Exception/ConnectionTimeoutException.c
src/MongoDB/Exception/DuplicateKeyException.c
src/MongoDB/Exception/ExecutionTimeoutException.c
src/MongoDB/Exception/SSLConnectionException.c
tests/bson/bson-binary_error-002.phpt
tests/bson/bson-binary_error-003.phpt
tests/bson/bson-javascript_error-002.phpt
tests/bson/bson-javascript_error-003.phpt
tests/bson/bson-maxkey_error-001.phpt
tests/bson/bson-maxkey_error-002.phpt
tests/bson/bson-minkey_error-001.phpt
tests/bson/bson-minkey_error-002.phpt
tests/bson/bson-objectid_error-002.phpt
tests/bson/bson-objectid_error-003.phpt
tests/bson/bson-regex_error-002.phpt
tests/bson/bson-regex_error-003.phpt
tests/bson/bson-timestamp_error-002.phpt
tests/bson/bson-timestamp_error-003.phpt
tests/bson/bson-utcdatetime_error-002.phpt
tests/bson/bson-utcdatetime_error-003.phpt

https://jira.mongodb.org/browse/PHPC-310

PHPC-310: Exceptions aren't final; BSON types are and can't be serialized

---

src/bson.c
tests/bson/bson-fromJSON-001.phpt
tests/bson/bson-fromJSON-002.phpt
tests/bson/bson-fromJSON_error-001.phpt
tests/bson/bson-toJSON-001.phpt
tests/bson/bson-toJSON-002.phpt
tests/bson/bson-toJSON_error-001.phpt

https://jira.mongodb.org/browse/PHPC-475

PHPC-475: toJSON and fromJSON should throw on error

---

php_phongo.c
tests/standalone/bug0487-001.phpt
tests/standalone/bug0487-002.phpt

https://jira.mongodb.org/browse/PHPC-487
Fixes #132 and supersedes #134.

PHPC-487: Fix return value comparison in check_closed stream handler

---

.travis.yml
scripts/presets/replicaset-30.json
scripts/start-servers.php
tests/cursor/cursor-destruct-001.phpt
tests/cursor/cursor-getmore-006.phpt
tests/manager/manager-executeQuery-002.phpt
tests/readPreference/bug0146-001.phpt
tests/readPreference/bug0146-002.phpt
tests/replicaset/manager-getservers-001.phpt
tests/server/server-executeCommand-002.phpt
tests/server/server-executeQuery-006.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-450

PHPC-450: Fix test failures for MongoDB 3.2

---

config.m4
config.w32
php_phongo.c
php_phongo.h
php_phongo_classes.h
src/MongoDB/Manager.c
src/MongoDB/Query.c
src/MongoDB/ReadConcern.c
src/MongoDB/WriteConcern.c
tests/manager/manager-getreadconcern-001.phpt
tests/query/query-ctor_error-001.phpt
tests/readConcern/readconcern-constants.phpt
tests/readConcern/readconcern-ctor-001.phpt
tests/readConcern/readconcern-ctor_error-001.phpt
tests/readConcern/readconcern-ctor_error-002.phpt
tests/readConcern/readconcern-getlevel-001.phpt
tests/replicaset/readconcern-001.phpt
tests/replicaset/readconcern-002.phpt

https://jira.mongodb.org/browse/PHPC-448

PHPC-448: Read concern support

---

src/MongoDB/ReadConcern.c

https://jira.mongodb.org/browse/PHPC-448
The first argument is not required.

PHPC-448: Fix arginfo for ReadConcern constructor

---

src/bson.c
tests/bson/bug0528.phpt

https://jira.mongodb.org/browse/PHPC-528
Fixes #182

PHPC-528: Support zval references when appending BSON

---

php_bson.h
php_phongo.c
src/BSON/Javascript.c
src/MongoDB/BulkWrite.c
src/MongoDB/Command.c
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/Query.c
src/MongoDB/ReadPreference.c
src/MongoDB/Server.c
src/MongoDB/WriteResult.c
src/bson.c

https://jira.mongodb.org/browse/PHPC-529
Fixes #173

PHPC-529: Prefix BSON functions to avoid symbol conflicts

---

config.m4

https://jira.mongodb.org/browse/PHPC-534
Supersedes #193 /cc @kaplanlior

PHPC-534: Enable configure without SASL

---

.travis.scripts/compile.sh

https://jira.mongodb.org/browse/PHPC-496
This reverts commit 873122fb78a9c7ca7e869090326a8122cd80354a.

PHPC-496: Revert "Temporary workaround for warning in mongoc"

---

src/BSON/UTCDateTime.c
tests/bson/bson-utcdatetime-int-size.phpt

https://jira.mongodb.org/browse/PHPC-543

Fixed PHPC-543: MongoDB\BSON\UTCDateTime on 32 bit platforms parse argument wrong

---

src/BSON/Binary.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite_error-001.phpt
tests/cursor/cursor_error-001.phpt
tests/cursorid/cursorid_error-001.phpt
tests/manager/manager_error-001.phpt
tests/query/query_error-001.phpt
tests/readConcern/readconcern_error-001.phpt
tests/readPreference/readpreference_error-001.phpt
tests/server/server_error-001.phpt
tests/writeConcern/writeconcern_error-001.phpt

https://jira.mongodb.org/browse/PHPC-519
This is just being done for consistency. The classes are all already final (specified in their MINIT function). We also add some regression tests for extending these classes.

PHPC-519: Add missing modifiers to final class methods

---

src/MongoDB/Query.c
tests/functional/query-sort-003.phpt
tests/functional/query-sort-004.phpt
tests/query/query-debug-001.phpt

https://jira.mongodb.org/browse/PHPC-539

PHPC-539: Include read concern in Query debug output

---

php_phongo.h
src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-582
Depends on #221, so please limit review to the final commit.

PHPC-582: Manager::selectServer() should select exception class based on bson_error_t

---

php_phongo.c
tests/manager/manager-executeBulkWrite_error-007.phpt
tests/manager/manager-executeCommand_error-001.phpt
tests/manager/manager-executeQuery_error-001.phpt
tests/manager/manager-selectserver_error-001.phpt

https://jira.mongodb.org/browse/PHPC-581
Depends on #232, so please limit review to the final commit.

PHPC-581: Use ConnectionTimeoutException for server selection failures

---

php_bson.h
src/MongoDB/BulkWrite.c
src/bson.c
tests/bson/bson-ods-001.phpt
tests/bson/bson-ods-002.phpt
tests/bulk/bulkwrite-delete-001.phpt
tests/bulk/bulkwrite-insert-001.phpt
tests/bulk/bulkwrite-update-001.phpt
tests/bulk/write-0001.phpt
tests/bulk/write-0002.phpt
tests/bulk/write-0003.phpt
tests/command/command-ctor-001.phpt
tests/query/query-ctor-001.phpt
tests/query/query-ctor_error-001.phpt
tests/standalone/bug0545.phpt
tests/standalone/write-error-001.phpt

https://jira.mongodb.org/browse/PHPC-550

PHPC-550: Always encode ODS field when serializing Persistable documents

---

phongo_compat.h
src/BSON/UTCDateTime.c
src/bson.c
tests/bson/bug0544.phpt
tests/bson/bug0592.phpt

https://jira.mongodb.org/browse/PHPC-544
https://jira.mongodb.org/browse/PHPC-592

PHPC-544, PHPC-592: 64-bit platform detection and integer truncation

---

phongo_compat.h
php_phongo.c
php_phongo.h
php_phongo_structs-5.h
php_phongo_structs-7.h
src/BSON/Binary.c
src/BSON/Timestamp.c
src/MongoDB/WriteConcern.c
src/bson.c
tests/bson/bson-binary_error-004.phpt
tests/bson/bson-timestamp-003.phpt
tests/bson/bson-timestamp-004.phpt
tests/bson/bson-timestamp_error-004.phpt
tests/bson/bson-timestamp_error-005.phpt
tests/writeConcern/writeconcern-ctor_error-005.phpt

This PR depends on #241 (i.e. [PHPC-544](https://jira.mongodb.org/browse/PHPC-544)).
https://jira.mongodb.org/browse/PHPC-593
https://jira.mongodb.org/browse/PHPC-594
https://jira.mongodb.org/browse/PHPC-595

PHPC-593, PHPC-594, PHPC-595: Range checks for WriteConcern, Binary, and Timestamp

---

tests/bson/bson-utcdatetime-002.phpt
tests/bson/bson-utcdatetime-003.phpt

https://jira.mongodb.org/browse/PHPC-414
This removes a SKIPIF from the 32-bit test but leaves the 64-bit test in place, since it tests construction from a 64-bit integer type instead of a string.

PHPC-414: Combine 32-bit and 64-bit UTCDateTime debug handler tests

---

src/bson.c
tests/bson/bson-toPHP_error-003.phpt
tests/bson/bson-toPHP_error-004.phpt
tests/bson/bug0531.phpt

* https://jira.mongodb.org/browse/PHPC-531
* https://jira.mongodb.org/browse/PHPC-616

PHPC-531, PHPC-616: Fix segfault and improve error reporting for corrupt BSON

---

src/bson.c
tests/bson/bson-toJSON_error-001.phpt
tests/bson/bson-toJSON_error-002.phpt
tests/bson/bson-toJSON_error-003.phpt

* https://jira.mongodb.org/browse/PHPC-613
* https://jira.mongodb.org/browse/PHPC-615

PHPC-613, PHPC-615: Improve toJSON() error handling

---

tests/standalone/command-aggregate-001.phpt

https://jira.mongodb.org/browse/DRIVERS-289

DRIVERS-289: Test iteration on live command cursor with empty first batch

---

config.m4

https://jira.mongodb.org/browse/PHPC-632
This ensures that libmongoc's automatic destructor is disabled and will avoid segfaults during abrupt FPM shutdowns for static builds. Those using the driver with system libmongoc will need to wait for [CDRIVER-1160](https://jira.mongodb.org/browse/CDRIVER-1160) to be released in order to resolve this issue.
This fixes #209 and #258 (for bundled libmongoc). It may also fix #212, #213, and #215.

PHPC-632: Define MONGOC_NO_AUTOMATIC_GLOBALS when bundling libmongoc

---

src/bson.c
tests/bulk/bug0667.phpt

https://jira.mongodb.org/browse/PHPC-667 and https://github.com/mongodb/mongo-php-driver/issues/281

PHPC-667: Fix check for existing "_id" field during BulkWrite::insert()

---

php_phongo.c
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/ReadPreference.c

https://jira.mongodb.org/browse/PHPC-609
This refactors existing code to take advantage of new functions in mongoc_uri_t's public API. There should be no functional changes.

PHPC-609: Apply RC/RP/WC to mongoc_uri_t instead of mongoc_client_t

---

src/MongoDB/Manager.c
tests/manager/manager-var-dump-001.phpt

https://jira.mongodb.org/browse/PHPC-600

PHPC-600: Use mongoc_client_get_server_descriptions() to get Manager's Servers

---

config.m4
config.w32
php_phongo.c

https://jira.mongodb.org/browse/PHPC-629

PHPC-629: Resolve mongoc-cursor-cursorid memory leaks

---

src/bson.c
tests/bson/bson-toPHP_error-004.phpt
tests/bson/bug0531.phpt

https://jira.mongodb.org/browse/PHPC-554

PHPC-554: Rephrase unsupported/corrupt BSON messages

---

phongo_compat.h
php_phongo.c
php_phongo.h
src/MongoDB/Server.c

https://jira.mongodb.org/browse/PHPC-606
Possible refactoring in the debug handler: serialize "last_is_master" first, and then copy the already-serialized "tags" field. Alternatively, we can decide to remove the duplicate, top-level "tags" field.

PHPC-606: Use mongoc_server_description_t public API in Server methods

---

php_phongo.c
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-677

PHPC-677: Keep pem_file valid for life of mongoc_client_t

---

php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-count-001.phpt
tests/bulk/bulkwrite-countable-001.phpt

https://jira.mongodb.org/browse/PHPC-680

PHPC-680: BulkWrite::count() should return number of operations

---

php_phongo.c
php_phongo.h
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/BulkWrite.c
src/MongoDB/Manager.c
src/MongoDB/Server.c
tests/bulk/bulkwrite-debug-001.phpt
tests/bulk/write-0002.phpt

* https://jira.mongodb.org/browse/PHPC-682
* https://jira.mongodb.org/browse/PHPC-684
I've grouped these issues into the same PR since PHPC-684 depends on PHPC-682's changes and the combined diff is still concise.
Combined with https://github.com/mongodb/mongo-php-driver/pull/311, this should resolve issues with depending on libmongoc's private API in BulkWrite.

PHPC-682, PHPC-684: BulkWrite debug handler improvements

---

src/MongoDB/WriteResult.c
tests/manager/manager-executeBulkWrite_error-007.phpt
tests/manager/manager-executeCommand_error-001.phpt
tests/manager/manager-executeQuery_error-001.phpt
tests/manager/manager-selectserver_error-001.phpt
tests/server/server-executeBulkWrite-002.phpt
tests/server/server-executeBulkWrite-003.phpt
tests/server/server-executeBulkWrite-004.phpt
tests/server/server-executeBulkWrite-005.phpt
tests/standalone/bug0655.phpt
tests/standalone/writeresult-isacknowledged-003.phpt

https://jira.mongodb.org/browse/PHPC-693

PHPC-693: Unacknowledged write results report null counts

---

php_phongo.c
php_phongo.h
php_phongo_classes.h
php_phongo_structs-5.h
php_phongo_structs-7.h
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/Server.c
tests/manager/manager-executeCommand-001.phpt
tests/manager/manager-executeQuery-001.phpt
tests/manager/manager-executeQuery-002.phpt
tests/readPreference/bug0146-001.phpt
tests/readPreference/bug0146-002.phpt
tests/server/server-executeCommand-001.phpt

https://jira.mongodb.org/browse/PHPC-688
This significantly alters the structure of the Cursor's debug output, since we not longer have access to private fields within mongoc_cursor_t.

PHPC-688: Change Cursor debug handler to use libmongoc public API

---

php_phongo.c
src/contrib/php-ssl.c
src/contrib/php-ssl.h

* https://jira.mongodb.org/browse/PHPC-698
* https://jira.mongodb.org/browse/PHPC-699

PHPC-698, PHPC-699: Check HAVE_OPENSSL_EXT before calling php-ssl.c functions

---

tests/cursor/cursor-isDead-002.phpt
tests/cursor/cursor-isDead-003.phpt
tests/cursor/cursor-isDead-004.phpt
tests/manager/manager-executeCommand-001.phpt
tests/manager/manager-executeQuery-001.phpt
tests/manager/manager-executeQuery-002.phpt
tests/readPreference/bug0146-002.phpt
tests/server/server-executeCommand-001.phpt

https://jira.mongodb.org/browse/PHPC-673
This bump includes the fix [CDRIVER-1221](https://jira.mongodb.org/browse/CDRIVER-1221), which entails changes to our `Cursor::isDead()` tests (among others where we dump cursors).

PHPC-673: Fix Cursor::isDead() tests for mongoc_cursor_is_alive()

---

php_phongo.c
tests/bson/bson-utcdatetime-int-size.phpt
tests/bson/bson-utcdatetime-todatetime-002.phpt
tests/bson/bug0631.phpt

https://jira.mongodb.org/browse/PHPC-631
This includes the patch from #267 and adds additional tests.

PHPC-631: Fix timelib_time.f assignment in UTCDateTime::toDateTime()

---

php_phongo.c
php_phongo.h
src/BSON/UTCDateTime.c

This function was only used by UTCDateTime::toDateTime(), so it does not need to be in php_phongo.c. Additionally, this commit removes the platform-specific spprintf patterns in favor of the portable PRId64 pattern.
This PR depends on https://github.com/mongodb/mongo-php-driver/pull/338.

Move php_phongo_new_datetime_from_utcdatetime() into UTCDateTime.c

---

phongo_compat.h
src/BSON/UTCDateTime.c
tests/bson/bson-utcdatetime-004.phpt
tests/bson/bson-utcdatetime-005.phpt
tests/bson/bson-utcdatetime-006.phpt
tests/bson/bson-utcdatetime_error-001.phpt

https://jira.mongodb.org/browse/PHPC-536

PHPC-536: UTCDateTime construction from DateTime or current time

---

src/MongoDB/Manager.c
tests/manager/manager-ctor-003.phpt

https://jira.mongodb.org/browse/PHPC-746

PHPC-746: Default Manager URI to "mongodb://127.0.0.1/"

---

src/BSON/Binary.c
src/BSON/Javascript.c
tests/bson/bson-binary-tostring-001.phpt
tests/bson/bson-javascript-tostring-001.phpt

https://jira.mongodb.org/browse/PHPC-729

PHPC-729: Implement __toString() for Javascript and Binary

---

src/BSON/Javascript.c
tests/bson/bson-javascript-getCode-001.phpt
tests/bson/bson-javascript-getScope-001.phpt

https://jira.mongodb.org/browse/PHPC-730

PHPC-730: Javascript::getCode() and Javascript::getScope()

---

config.m4
config.w32
php_phongo.c
php_phongo.h
php_phongo_classes.h
php_phongo_structs.h
src/BSON/Decimal128.c
src/bson.c
tests/bson/bson-binary-001.phpt
tests/bson/bson-decimal128-001.phpt
tests/bson/bson-decimal128-002.phpt
tests/bson/bson-decimal128-003.phpt
tests/bson/bson-decimal128-004.phpt
tests/bson/bson-decimal128-serialization-001.phpt
tests/bson/bson-decimal128-serialization_error-001.phpt
tests/bson/bson-decimal128-serialization_error-002.phpt
tests/bson/bson-decimal128-set_state-001.phpt
tests/bson/bson-decimal128-set_state_error-001.phpt
tests/bson/bson-decimal128-set_state_error-002.phpt
tests/bson/bson-decimal128_error-001.phpt
tests/bson/bson-encode-003.phpt
tests/bson/bson-encode-004.phpt
tests/bson/bson-toJSON-002.phpt
tests/bson/bson-toPHP-001.phpt
tests/bson/bson-toPHP-002.phpt
tests/bson/bson-toPHP-003.phpt

This PR incorporates several interdependent issues:
* https://jira.mongodb.org/browse/PHPC-629
* https://jira.mongodb.org/browse/PHPC-754
* https://jira.mongodb.org/browse/PHPC-755
* https://jira.mongodb.org/browse/PHPC-758

PHPC-629: Bump libbson and libmongoc to 1.4.0-beta1

---

src/BSON/UTCDateTime.c

I missed this in https://github.com/mongodb/mongo-php-driver/pull/364

UTCDateTime build fix for 32-bit Windows ZTS

---

src/BSON/Decimal128.c
src/BSON/ObjectID.c
tests/bson/bson-decimal128-serialization_error-002.phpt
tests/bson/bson-decimal128-set_state_error-002.phpt
tests/bson/bson-objectid-serialization_error-002.phpt
tests/bson/bson-objectid-set_state_error-002.phpt
tests/bson/bson-objectid_error-003.phpt

https://jira.mongodb.org/browse/PHPC-744

PHPC-744: Improve error messages for invalid Decimal128 and ObjectID strings

---

src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bson-timestamp-002.phpt
tests/bson/bson-timestamp-003.phpt
tests/bson/bson-timestamp-004.phpt
tests/bson/bson-timestamp-serialization-001.phpt
tests/bson/bson-timestamp-serialization-002.phpt
tests/bson/bson-timestamp-serialization_error-001.phpt
tests/bson/bson-timestamp-set_state-001.phpt
tests/bson/bson-timestamp-set_state-002.phpt
tests/bson/bson-timestamp-set_state_error-001.phpt
tests/bson/bson-timestamp-set_state_error-004.phpt
tests/bson/bson-utcdatetime-003.phpt
tests/bson/bson-utcdatetime-004.phpt
tests/bson/bson-utcdatetime-005.phpt
tests/bson/bson-utcdatetime-006.phpt
tests/bson/bson-utcdatetime-serialization-001.phpt
tests/bson/bson-utcdatetime-serialization-002.phpt
tests/bson/bson-utcdatetime-set_state-001.phpt
tests/bson/bson-utcdatetime-set_state-002.phpt

I've opted to make Timestamp either accept strings for both increment and timestamp, or an integer for both. You can not mix a string increment and an integer timestamp, or v.v.

PHPC-726: Allow cross-platform serialization of Timestamp and UTCDateTime

---

src/BSON/Timestamp.c
tests/bson/bson-timestamp-005.phpt

PHPC-731: Parse Timestamp argument as strings to accept large integers

---

php_phongo.c
php_phongo.h
php_phongo_structs.h
src/MongoDB/Manager.c
tests/connect/standalone-x509-auth-001.phpt
tests/connect/standalone-x509-auth-002.phpt
tests/manager/manager-debug-001.phpt
tests/manager/manager-debug-002.phpt

https://jira.mongodb.org/browse/PHPC-433
https://jira.mongodb.org/browse/PHPC-605
https://jira.mongodb.org/browse/PHPC-704
Depends on #361.

PHPC-433: Persist topology state between requests

---

config.w32

The ldap extensions' [config.w32](https://github.com/php/php-src/blob/php-7.0.10/ext/ldap/config.w32) uses `PHP_LDAP` as its search path, so we'll continue to start with `PHP_MONGODB` as a rule of thumb. Since we currently declare a dependency on the OpenSSL extension, it makes sense to also include it in our search path in case it was customized at build time.
Based on the openssl extension's [config.w32](https://github.com/php/php-src/blob/php-7.0.10/ext/openssl/config.w32), crypt32.lib is a system library and needs no extra search path.

Use both mongodb and openssl extension paths for CHECK_LIB

---

php_phongo.c
php_phongo.h
src/MongoDB/ReadPreference.c
tests/manager/manager-ctor_error-003.phpt
tests/readPreference/readpreference-ctor_error-001.phpt
tests/readPreference/readpreference-ctor_error-002.phpt

https://jira.mongodb.org/browse/PHPC-424
This adds common validation for read preference tag sets when specified through either the Manager constructor's URI options array or ReadPreference constructor.
An additional test case for a malformed tag set has been added to the Manager::__construct() error test for read preference options. Additionally, the ReadPreference::__construct() error test has been split up to test for mode and tagSet errors separately.
Note: we cannot test for the exceptions for bson_init_static() and mongoc_read_prefs_is_valid(), since those points will never be hit in normal operation.

PHPC-424: Validate that RP tag set is an array of documents

---

src/MongoDB/BulkWrite.c
src/bson.c

This updates a few cases where we were already passing string literals to the php_array macros. The "c" variant expands to `lit, sizeof(lit) - 1` instead of `lit, strlen(lit)`.

Use string literal php_array macros where possible

---

php_phongo.c
src/MongoDB/ReadConcern.c
src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c
tests/bulk/write-0002.phpt
tests/manager/manager-getreadconcern-001.phpt
tests/manager/manager-getreadpreference-001.phpt
tests/manager/manager-getwriteconcern-001.phpt
tests/readConcern/readconcern-ctor-001.phpt
tests/readPreference/bug0146-002.phpt
tests/readPreference/readpreference-ctor-001.phpt
tests/server/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/standalone/writeresult-isacknowledged-002.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/writeConcern/writeconcern-ctor-001.phpt
tests/writeConcern/writeconcern-debug-001.phpt
tests/writeConcern/writeconcern-debug-002.phpt
tests/writeResult/writeresult-debug-001.phpt

https://jira.mongodb.org/browse/PHPC-498

PHPC-498: ReadPreference, ReadConcern, and WriteConcern should serialize to BSON

---

src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-update_error-001.phpt

https://jira.mongodb.org/browse/PHPC-734
https://jira.mongodb.org/browse/PHPC-794
https://jira.mongodb.org/browse/PHPC-796
This migrates the `BulkWrite::update()` and `delete()` methods to use libmongoc's flexible options API ([CDRIVER-1525](https://jira.mongodb.org/browse/CDRIVER-1525)) and adds support for a collation option. Additionally, we now check for invalid arguments for a replace operation.

PHPC-796, PHPC-794, and PHPC-734: Flexible opts API and collation option for BulkWrite

---

tests/bulk/bulkwrite-delete_error-001.phpt

This should have been included with https://github.com/mongodb/mongo-php-driver/pull/419

PHPC-734: Test for BulkWrite::delete() collation option error

---

php_phongo.c
php_phongo.h
src/MongoDB/Manager.c
src/MongoDB/ReadConcern.c
src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c
tests/manager/manager-ctor-read_preference-001.phpt
tests/manager/manager-ctor-read_preference-003.phpt
tests/manager/manager-getreadpreference-001.phpt
tests/readConcern/readconcern-bsonserialize-001.phpt
tests/readConcern/readconcern-bsonserialize-002.phpt
tests/readConcern/readconcern-constants.phpt
tests/readConcern/readconcern-debug-001.phpt
tests/readPreference/readpreference-bsonserialize-001.phpt
tests/readPreference/readpreference-bsonserialize-002.phpt
tests/readPreference/readpreference-ctor-001.phpt
tests/readPreference/readpreference-debug-001.phpt
tests/writeConcern/writeconcern-bsonserialize-001.phpt
tests/writeConcern/writeconcern-bsonserialize-002.phpt
tests/writeConcern/writeconcern-debug-003.phpt

https://jira.mongodb.org/browse/PHPC-359
https://jira.mongodb.org/browse/PHPC-801

PHPC-359 and PHPC-801: RC, RP, and WC BSON serialization

---

src/MongoDB/BulkWrite.c

https://jira.mongodb.org/browse/PHPC-791

PHPC-791: Bump libbson and libmongoc to 1.5.0-rc3

---

config.m4
config.w32
php_phongo.c

https://jira.mongodb.org/browse/PHPC-718
Note: https://github.com/mongodb/mongo-php-driver/pull/454 (for [PHPC-459](https://jira.mongodb.org/browse/PHPC-459)) adds a dependency on the "json" extension.

PHPC-718: Define extension dependencies

---

src/bson.c

https://jira.mongodb.org/browse/PHPC-756

PHPC-756: Do not eval bson_error_t.message as boolean

---

THIRD_PARTY_NOTICES

https://jira.mongodb.org/browse/PHPC-799
This references the THIRD_PARTY_NOTICES files from libbson and libmongoc, which were added in CDRIVER-1557.

PHPC-799: Add THIRD_PARTY_NOTICES file

---

src/BSON/Regex.c
tests/bson/bson-regex-005.phpt
tests/bson/bson-regex-serialization-003.phpt
tests/bson/bson-regex-set_state-002.phpt

https://jira.mongodb.org/browse/PHPC-829
We do not test that MongoDB\BSON\fromJSON() alphabetizes the flags, as that will be handled by CDRIVER-1883.

PHPC-829: BSON Regex flags must be alphabetically ordered

---

src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bson-timestamp-serialization_error-004.phpt
tests/bson/bson-timestamp-set_state_error-004.phpt
tests/bson/bson-timestamp_error-005.phpt
tests/bson/bson-timestamp_error-006.phpt
tests/bson/bson-utcdatetime-007.phpt
tests/bson/bson-utcdatetime-serialization_error-002.phpt
tests/bson/bson-utcdatetime_error-003.phpt
tests/bson/bson-utcdatetime_error-004.phpt

https://jira.mongodb.org/browse/PHPC-790
https://jira.mongodb.org/browse/PHPC-804

PHPC-790: Accept integer and floats in Timestamp and UTCDateTime constructors

---

src/bson.c

Fixes a 32-bit build error introduced in 22a39d68f3661438be6d6820faf508a5bc98d084 for PHPC-313

Ensure php_phongo_bson_visit_int64() has TSRMLS vars if needed

---

phongo_compat.h
src/bson.c
tests/bson/bson-fromPHP-004.phpt

https://jira.mongodb.org/browse/PHPC-848
When a numeric array was encoded to BSON, the hash's apply counter was incremented and decremented irrespective of whether apply protection was enabled. This was not compatible with immutable arrays, which may be created by OPcache. We now consult ZEND_HASH_APPLY_PROTECTION() whenever an apply counter might be modified.
Previously, object_to_bson() incremented the apply counter when converting a MongoDB\BSON\Type instance. Associative arrays and other objects were not protected. This patch adds recursion checking for those types.
Since PHP7 already has macros for working with the apply counter, this patch adds equivalent macros for PHP 5.x.
Related issues:
* https://github.com/mongodb/mongo-php-library/issues/216
* …

PHPC-848: Consult ZEND_HASH_APPLY_PROTECTION() in PHP7

---

src/bson.c

This fixes a build error introduced in be58940cd9c1373dad97d0e4364e4b61881022b2.

Only fetch TSRMLS for 32-bit platforms in int64 visitor

---

tests/standalone/bug0487-002.phpt

The previous error message was based on PHP's stream handlers, which are no longer used in 1.2.x.

Update closed socket test for libmongoc stream handling

---

config.w32

https://jira.mongodb.org/browse/PHPC-872
This flag is primarily intended for Linux distributions with custom profiles (e.g. Fedora). d227207f970e590c3149979a675b17a0362145fa for PHPC-703 incorrectly assumed that libmongoc was enabling it by default on Windows.

PHPC-872: Do not use system crypto policy for OpenSSL on Windows

---

config.m4
config.w32

https://jira.mongodb.org/browse/PHPC-856
https://jira.mongodb.org/browse/PHPC-873

PHPC-856, PHPC-873: Fix build errors mixing bundled and system libraries

---

php_phongo.c
src/MongoDB/WriteResult.c
tests/replicaset/writeresult-getserver-002.phpt
tests/server/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/standalone/writeresult-isacknowledged-002.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/writeResult/writeresult-debug-001.phpt
tests/writeResult/writeresult-debug-002.phpt

https://jira.mongodb.org/browse/PHPC-635

PHPC-635: WriteResult debug handler should return objects

---

php_phongo.c
tests/functional/phpinfo-1.phpt
tests/functional/phpinfo-2.phpt

https://jira.mongodb.org/browse/PHPC-633
Supersedes https://github.com/mongodb/mongo-php-driver/pull/265

PHPC-633: Include libmongoc SSL, crypto, and SASL details in phpinfo()

---

src/bson.c
tests/bson/bson-fromPHP-005.phpt
tests/bson/bson-fromPHP-006.phpt

https://jira.mongodb.org/browse/PHPC-884
https://jira.mongodb.org/browse/PHPC-886
https://jira.mongodb.org/browse/PHPC-891

PHPC-884: Do not skip public property with empty string name during BSON encoding

---

phongo_compat.h

This fixes a build error from ADD_NEXT_INDEX_INT64 (added in 3a4da1c74c725d7b6acceadf1bb4091f63872f0b), where we referenced "val" instead of "value". That macro was based on ADD_INDEX_INT64 (added in 6bcba59cb57a92f091b29e4f11e1c99a96eaed95), which also incorrectly referenced "val"; however, that never resulted in a build error since a "val" was declared in the calling scope.

Ensure INT64 macros use their actual parameters

---

phongo_compat.h
src/BSON/Binary.c
src/BSON/Decimal128.c
src/BSON/Javascript.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bug0894-001.phpt

https://jira.mongodb.org/browse/PHPC-894
This addresses a memory leak if gc_possible_root() were to invoke the existing get_properties handlers.

PHPC-894: Implement get_gc handlers for BSON classes

---

CONTRIBUTING.md
config.w32

This fixes 906d0398fa035293bad5521060274d5a0a25c400 from #518. `config.w32` requires sources to be segregated by path.
Note: when I said I [verified the previous refactoring](https://github.com/mongodb/mongo-php-driver/pull/518#issuecomment-275204181), that was just building the configuration script and then executing it without compiling the final DLL:
```
buildconf --force
configure --disable-all --with-openssl --enable-cli --enable-json --enable-mongodb=shared
```
For this change, I am verifying that we can also build the DLL with `nmake`.

Fix source file enumeration in config.w32 

---

php_phongo.c
tests/manager/bug0913-001.phpt

https://jira.mongodb.org/browse/PHPC-913

PHPC-913: Child process should not re-use mongoc_client_t objects from parent

---

src/MongoDB/Cursor.c
tests/cursor/bug0924-001.phpt
tests/cursor/bug0924-002.phpt

https://jira.mongodb.org/browse/PHPC-924

PHPC-924: Avoid unnecessary BSON conversion in Cursor::setTypeMap()

---

src/bson.c
tests/bson/bug0923-001.phpt
tests/bson/bug0923-002.phpt

https://jira.mongodb.org/browse/PHPC-923
Fixes https://github.com/mongodb/mongo-php-driver/issues/529

PHPC-923: Use zend_string_release() to free class names

---

src/BSON/ObjectID.c

https://jira.mongodb.org/browse/PHPC-736

PHPC-736: Remove zend_str_tolower_dup() in ObjectID construction

---

src/bson.c
tests/bson/bson-toPHP_error-005.phpt
tests/bson/bson-toPHP_error-006.phpt

https://jira.mongodb.org/browse/PHPC-302
Previously, the undefined, DBPointer, and symbol types were ignored since they were known to libbson and no visitor function was defined.

PHPC-302: Throw exceptions for unsupported BSON types

---

php_phongo.c
php_phongo.h
php_phongo_structs.h
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/Server.c
src/MongoDB/WriteResult.c

https://jira.mongodb.org/browse/PHPC-932
This reverts changes introduced in PHPC-671, which are no longer necessary due to mongoc_client_t persistence (PHPC-433).

PHPC-932: Remove reference to Manager on Cursor, Server, and WriteResult

---

tests/cursor/bug0920-001.phpt

https://jira.mongodb.org/browse/PHPC-920

PHPC-920: Regression test for mongoc_cursor_destroy() crash

---

CONTRIBUTING.md
php_phongo.c
php_phongo.h

https://jira.mongodb.org/browse/PHPC-936
This removes the redundant MONGODB_VERSION constant renames the existing version and stability constants to be consistent with the format in PHP's extension skeleton: https://github.com/php/php-src/commit/dcfd753104085d8337b8a5f4a21ce3b629ad4651
Fixes: https://github.com/mongodb/mongo-php-driver/issues/562

PHPC-936: Define PHP_MONGODB_VERSION and STABILITY constants

---

src/contrib/php_array_api.h
tests/manager/bug0940-001.phpt
tests/manager/bug0940-002.phpt

https://jira.mongodb.org/browse/PHPC-940
This issue only manifests itself on PHP 7, since interned strings are tracked in the zval struct instead of the character pointer as in PHP 5.x.

PHPC-940: php_phongo_free_ssl_opt() attempts to free interned strings

---

config.m4
config.w32
php_phongo.c
php_phongo_classes.h
php_phongo_structs.h
src/MongoDB/Manager.c
src/MongoDB/Monitoring.h
src/MongoDB/Monitoring/CommandFailedEvent.c
src/MongoDB/Monitoring/CommandStartedEvent.c
src/MongoDB/Monitoring/CommandSubscriber.c
src/MongoDB/Monitoring/CommandSucceededEvent.c
src/MongoDB/Monitoring/Subscriber.c

Related to: https://github.com/mongodb/mongo-php-driver/pull/466

PHPC-349: Fixes and code cleanup

---

src/bson.c
tests/bson/bson-fromPHP_error-007.phpt

https://jira.mongodb.org/browse/PHPC-949
Depends on https://github.com/mongodb/mongo-php-driver/pull/575. Only the last commit is relevant to the fix.

PHPC-949: Fix leak if bsonSerialize() returns keys with null bytes

---

php_phongo.c
src/MongoDB/Manager.c
tests/connect/standalone-x509-extract_username-001.phpt
tests/connect/standalone-x509-extract_username-002.phpt
tests/manager/manager-ctor-auth_mechanism-001.phpt
tests/manager/manager-ctor-auth_mechanism-002.phpt

https://jira.mongodb.org/browse/PHPC-772
https://jira.mongodb.org/browse/PHPC-953
https://jira.mongodb.org/browse/PHPC-957
Note: we don't have functional tests for GSSAPI (Kerberos), so I am only testing that parsing of the array options does not throw an exception or leak memory. Leak testing is relevant because non-string values for "CANONICALIZE_HOST_NAME" are evaluated as a boolean and converted to the string "true" if true. As noted in [PHPC-772](https://jira.mongodb.org/browse/PHPC-772), functional testing can wait for [PHPC-886](https://jira.mongodb.org/browse/PHPC-866).

PHPC-772, PHPC-953, PHPC-957: Parse "authMechanism" and "authMechanismProperties" URI options and ignore "database"

---

tests/bulk/bulkwrite-update_error-002.phpt

https://jira.mongodb.org/browse/PHPC-579
CDRIVER-1341 implemented client-side detection of the invalid newObj argument.

PHPC-579: Regression test mixing update/replacement with BulkWrite::update()

---

php_phongo.c
tests/manager/manager-executeBulkWrite_error-008.phpt
tests/server/server-executeBulkWrite_error-001.phpt

https://jira.mongodb.org/browse/PHPC-628

PHPC-628: Throw InvalidArgumentException when executing empty BulkWrite

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-959

PHPC-959: mongoc_collection_find_with_opts() always returns a cursor

---

src/BSON/Binary.c
tests/bson/bson-binary-001.phpt
tests/bson/bson-binary-serialization_error-003.phpt
tests/bson/bson-binary-set_state_error-003.phpt
tests/bson/bson-binary_error-004.phpt
tests/bson/bson-toPHP-006.phpt

https://jira.mongodb.org/browse/PHPC-895

PHPC-895: Require 16-byte data length for Binary UUID subtypes 0x03 and 0x04

---

tests/cursor/cursor-tailable-001.phpt
tests/cursor/cursor-tailable-002.phpt
tests/cursor/cursor-tailable_error-001.phpt
tests/cursor/cursor-tailable_error-002.phpt

https://jira.mongodb.org/browse/PHPC-586
Note: iterating a tailable cursor with `foreach` is not possible because [`php_phongo_cursor_iterator_valid()`](https://github.com/mongodb/mongo-php-driver/blob/0c683809881ee9633fd61383855ff6b4ebf977d7/src/MongoDB/Cursor.c#L58) returns `false` if the current element is undefined. When [`php_phongo_cursor_iterator_move_forward()`](https://github.com/mongodb/mongo-php-driver/blob/0c683809881ee9633fd61383855ff6b4ebf977d7/src/MongoDB/Cursor.c#L102) advances the cursor, it clears the current element by calling [`php_phongo_cursor_free_current()`](https://github.com/mongodb/mongo-php-driver/blob/0c683809881ee9633fd61383855ff6b4ebf977d7/src/MongoDB/Cursor.c#L31) and will leave it undefined unless `mongoc_cursor_next()` returns `true` and we have a BSON …

PHPC-586: Regression tests for tailable cursor iteration

---

config.m4

https://jira.mongodb.org/browse/PHPC-964
Related to: https://github.com/mongodb/mongo-php-driver/issues/582 and https://github.com/mongodb/mongo-php-library/issues/366.

PHPC-964: Ensure SASL output variables are always defined

---

tests/bson/bug0974-001.phpt

Fixed in libbson 1.6.0 by CDRIVER-994.
https://jira.mongodb.org/browse/PHPC-974

PHPC-974: Regression test for array index gaps in JSON->BSON->PHP

---

php_phongo.h
php_phongo_structs.h
src/BSON/Binary.c
src/BSON/Decimal128.c
src/BSON/Javascript.c
src/BSON/ObjectID.c
src/BSON/Regex.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
tests/bson/bug0939-001.phpt

https://jira.mongodb.org/browse/PHPC-939

PHPC-939: Don't modify std props in BSON get_properties handlers

---

src/MongoDB/Monitoring/functions.c

https://jira.mongodb.org/browse/PHPC-982
This is based on #613 and #614. Only the last commit is relevant to PHPC-982. Please disregard the earlier commits.

PHPC-982: PHP 5 expects HashTable key length to include null byte

---

php_phongo.c
tests/manager/manager-ctor-read_preference-error-002.phpt
tests/manager/manager-ctor-read_preference-error-004.phpt

https://jira.mongodb.org/browse/PHPC-846
Note: Resolution of [CDRIVER-2232](https://jira.mongodb.org/browse/CDRIVER-2232) will decide if 64-bit integers are actually valid for `maxStalenessSeconds` (they appear to already be supported my libmongoc's read preference API, while the URI parsing restricts it to 32-bit values). We currently document the ReadPreference constructor argument as a "signed 32-bit integer".
If 64-bit integers are approved for `maxStalenessSeconds`, I will repurpose this issue to add support in both our URI options array and ReadPreference constructor.

PHPC-846: Throw if maxStalenessSeconds URI option is out of range

---

src/BSON/functions.c
tests/bson/bson-toCanonicalJSON_error-001.phpt
tests/bson/bson-toJSON_error-001.phpt
tests/bson/bson-toPHP_error-001.phpt
tests/bson/bson-toPHP_error-002.phpt
tests/bson/bson-toRelaxedJSON_error-001.phpt

https://jira.mongodb.org/browse/PHPC-977

PHPC-977: Bump libbson and libmongoc to 1.7.0

---

config.w32

https://jira.mongodb.org/browse/PHPC-994
This fixes macro redefinition warnings for HAVE_SOCKLEN_T, which were caused by CHECK_FUNC_IN_HEADER() injecting a definition. We can safely assume that Windows builds environments for PHP have socklen_t defined (as does libmongoc in its cmake config).
Fixes https://github.com/mongodb/mongo-php-driver/issues/629.

PHPC-994: Assume socklen_t is defined on Windows

---

src/bson-encode.c
tests/bulk/bulkwrite-delete_error-002.phpt
tests/bulk/bulkwrite-insert_error-002.phpt
tests/bulk/bulkwrite-update_error-004.phpt

https://jira.mongodb.org/browse/PHPC-1001
See: https://github.com/mongodb/mongo-php-driver/issues/635#issuecomment-323367576

PHPC-1001: Report field name for invalid UTF-8 and unsupported zval types

---

src/bson.c
tests/bson/bson-encode-004.phpt
tests/bson/bson-toPHP-004.phpt
tests/bson/bug0974-001.phpt
tests/functional/query-sort-004.phpt

https://jira.mongodb.org/browse/PHPC-1005
This will ensure that the array symtable is properly converted to an object proptable in PHP 7.2 (e.g. integer key 0 converts to string key "0").

PHPC-1005: Use convert_to_object() to create stdClass from array

---

src/bson-encode.c
tests/bson/bug1006-001.phpt

https://jira.mongodb.org/browse/PHPC-1006

PHPC-1006: Do not modify Persistable::bsonSerialize() retval

---

src/bson.c
tests/bson/bson-encode-004.phpt
tests/bson/bson-toPHP-004.phpt
tests/functional/query-sort-004.phpt

https://jira.mongodb.org/browse/PHPC-1005
This will ensure that the array symtable is properly converted to an object proptable in PHP 7.2 (e.g. integer key 0 converts to string key "0").
This is a backport of #642 to the v1.2 branch.

[backport] PHPC-1005: Use convert_to_object() to create stdClass from array

---

src/bson.c
tests/bson/bug1006-001.phpt

https://jira.mongodb.org/browse/PHPC-1006
This is a backport of #643 to the v1.2 branch.

[backport] PHPC-1006: Do not modify Persistable::bsonSerialize() retval

---

.travis.yml

Cherry-picked from https://github.com/mongodb/mongo-php-driver/pull/652
We can also use this PR as an indicator for when https://github.com/mongodb/mongo-php-driver/issues/649 might be resolved after Travis CI upgrades to PHP 7.2 RC1.

Test against PHP 7.2 on Travis CI

---

config.w32

https://jira.mongodb.org/browse/PHPC-1008
This adds support for OpenSSL 1.1.x when building for PHP 7.1.2+.
Previously, we did not specify a custom path_to_check for crypt32.lib (see 912987c37dc6689d5e27ab4e05c5241d29dc473f); however, SETUP_OPENSSL() does this for OpenSSL 1.0.x and lower, so we can add it back for consistency.

PHPC-1008: Use SETUP_OPENSSL() in config.w32 if available

---

bin/package.xml.in

https://jira.mongodb.org/browse/PHPC-996
Noticed that the 1.3.0beta2 still allowed PHP 5.4 in `package.xml`.

PHPC-996: Bump min PHP requirement in package.xml to 5.5

---

tests/connect/standalone-plain-0001.phpt
tests/connect/standalone-plain-0002.phpt

https://jira.mongodb.org/browse/PHPC-1046
@derickr: This is the same change I had you add in https://github.com/mongodb/mongo-php-driver/pull/672. I noticed this was failing since PHPC 1.3.0 when we bumped to libmongoc 1.8.0. The relevant change was [CDRIVER-2190](https://jira.mongodb.org/browse/CDRIVER-2190) from libmongoc 1.7.0 (which we never bundled with directly).
I'd like to fix it in 1.3.x as I noticed the failure after bumping the 1.8.2 in https://github.com/mongodb/mongo-php-driver/pull/674.

PHPC-1046: Use authSource URI option to specify $external

---

tests/connect/bug1045.phpt

https://jira.mongodb.org/browse/PHPC-1044
https://jira.mongodb.org/browse/PHPC-1045

PHPC-1044 and PHPC-1045: Bump libmongoc to 1.8.2 and fix auth segfault

---

CONTRIBUTING.md
php_phongo.c
php_phongo_structs.h
scripts/presets/replicaset-36.json
scripts/start-servers.php
scripts/ubuntu/mongo-orchestration-config.json
scripts/ubuntu/mongo-orchestration.sh
src/MongoDB/Command.c
tests/bulk/bulkwrite-update-arrayFilters-001.phpt
tests/command/cursor-tailable-001.phpt
tests/command/findAndModify-001.phpt
tests/command/update-001.phpt
tests/utils/basic.inc

Waiting on PHPC-1037 / PR #672

 PHPC-1029 Support maxTimeMS getMore option for tailable command cursors 

---

config.m4
scripts/presets/replicaset-dns.json
scripts/start-servers.php
tests/connect/bug1015.phpt

https://jira.mongodb.org/browse/PHPC-1015
We'll need to decide whether we want to always run this. Starting up a whole
replicaset for one test is a waste of resources really. It also requires that we add a line in our /etc/hosts files (with the IP address of the Vagrant host) for this to work.

PHPC-1015: Add test for DNS Initial Seedlist

---

Makefile.frag

@derickr: This is adopted from my shell script. I removed a line that deletes `/tmp/PHONGO-SERVERS.json` since `start-servers.php` overwrites the file anyway. The functional difference is that if you run tests with a bad `PHONGO-SERVERS.json` you'll likely get failures, while tests would otherwise be skipped if `PHONGO-SERVERS.json` is missing.

Reload VM and restart MO in make test-bootstrap

---

php_phongo.c
php_phongo.h
src/MongoDB/Manager.c
src/MongoDB/Server.c
tests/manager/manager-debug-001.phpt
tests/manager/manager-debug-002.phpt
tests/manager/manager-debug-003.phpt

I don't know how to write a test for this though, as this technically should never happen?

PHPC-1043: phongo_execute_query() may leak cursor struct on error

---

tests/apm/overview.phpt
tests/bulk/bulkwrite-insert_error-001.phpt
tests/bulk/bulkwrite-update_error-001.phpt
tests/bulk/bulkwrite-update_error-002.phpt
tests/manager/manager-ctor-read_preference-error-001.phpt
tests/manager/manager-ctor-read_preference-error-002.phpt
tests/manager/manager-ctor-read_preference-error-003.phpt
tests/manager/manager-ctor-write_concern-error-003.phpt
tests/manager/manager-ctor-write_concern-error-005.phpt
tests/manager/manager-ctor-write_concern-error-006.phpt
tests/manager/manager-executeCommand-004.phpt
tests/manager/manager-executeCommand_error-002.phpt
tests/server/server-executeCommand-006.phpt
tests/server/server-executeCommand_error-001.phpt

https://jira.mongodb.org/browse/PHPC-1037

Test fixes for libmongoc 1.9.0-dev (post rc1)

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1072
Previously, reply might leak if `phongo_execute_command()` returned due to an error (result=false).

PHPC-1072: mongoc_client_command_with_opts() reply must always be freed

---

php_phongo.c
php_phongo.h
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
src/MongoDB/Query.c
src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c
src/bson-encode.c
tests/bson/bson-timestamp_error-006.phpt
tests/manager/manager-executeCommand_error-002.phpt
tests/manager/manager-executeQuery_error-002.phpt
tests/query/query-ctor_error-001.phpt
tests/server/server-executeCommand_error-001.phpt
tests/server/server-executeQuery_error-001.phpt
tests/writeConcern/writeconcern-ctor_error-002.phpt

https://jira.mongodb.org/browse/PHPC-1070
https://jira.mongodb.org/browse/PHPC-1071
Adds a macro for accessing zval's class or type name, depending on whether it's an object type. This replaces existing ternary statements we had for some BSON exceptions. I've also gone through and updated exceptions where object types are entirely unexpected. Options that expect a BSON document (i.e. array or object) remain unchanged and do not use this macro, as any object type would be accepted.
IMO, this makes the exceptions more helpful and also makes PHPC more consistent with the invalid type exception messages in PHPLIB.

PHPC-1070 and PHPC-1071: Report class name for unexpected object values

---

config.m4
config.w32
php_phongo.c
php_phongo.h
php_phongo_classes.h
php_phongo_structs.h
src/MongoDB/Manager.c
src/MongoDB/Session.c
tests/session/session-001.phpt
tests/session/session-002.phpt
tests/session/session-003.phpt
tests/session/session-advanceClusterTime-001.phpt
tests/session/session-debug-001.phpt
tests/session/session-debug-002.phpt
tests/session/session-debug-003.phpt
tests/session/session-getClusterTime-001.phpt
tests/session/session-getLogicalSessionId-001.phpt

https://jira.mongodb.org/browse/PHPC-980
I reached a road block supporting options for `phongo_execute_query()` and ended up continuing that work in #707 while refactoring the option parsing for execute methods for [PHPC-1057](https://jira.mongodb.org/browse/PHPC-1057).
This PR is limited just to relevant session commits. All included spec tests should be passing.

PHPC-980: Sessions API

---

tests/retryable-writes/retryable-writes-001.phpt
tests/retryable-writes/retryable-writes-002.phpt
tests/retryable-writes/retryable-writes-003.phpt
tests/retryable-writes/retryable-writes-004.phpt
tests/retryable-writes/retryable-writes-005.phpt

https://jira.mongodb.org/browse/PHPC-986
PHPC did not require any code changes to support retryable writes, as existing URI option processing allows enabling of retryable writes in libmongoc. These tests utilize APM to assert that certain commands include or exclude a transaction ID.

PHPC-986: APM-based tests for retryable writes

---

src/MongoDB/Session.c
tests/causal-consistency/causal-consistency-001.phpt
tests/causal-consistency/causal-consistency-002.phpt
tests/causal-consistency/causal-consistency-003.phpt
tests/causal-consistency/causal-consistency-004.phpt
tests/causal-consistency/causal-consistency-005.phpt
tests/causal-consistency/causal-consistency-006.phpt
tests/causal-consistency/causal-consistency-007.phpt
tests/causal-consistency/causal-consistency-008.phpt
tests/causal-consistency/causal-consistency-009.phpt
tests/causal-consistency/causal-consistency-010.phpt
tests/session/session-003.phpt
tests/session/session-advanceOperationTime-001.phpt
tests/session/session-advanceOperationTime-002.phpt
tests/session/session-advanceOperationTime-003.phpt
tests/session/session-advanceOperationTime_error-001.phpt
tests/session/session-debug-001.phpt
tests/session/session-debug-002.phpt
tests/session/session-debug-003.phpt
tests/session/session-getOperationTime-001.phpt

https://jira.mongodb.org/browse/PHPC-987

PHPC-987: Causally consistent reads

---

Makefile.frag

This prunes the utils directory instead of depending on a whitelist, which would need to be more frequently updated.

Update Makefile target for cleaning test dirs

---

src/MongoDB/ReadConcern.c
tests/readConcern/readconcern-bsonserialize-001.phpt
tests/readConcern/readconcern-bsonserialize-002.phpt
tests/readConcern/readconcern-constants.phpt
tests/readConcern/readconcern-debug-001.phpt

https://jira.mongodb.org/browse/PHPC-1078

PHPC-1078: Create constant for available read concern level

---

Makefile.frag

The original modifications in #722 didn't actually prune the `utils` directory from the output of `find` (and input of `xargs rm`). This ensures that both the directory and its contents are omitted.
Additionally `-r` ensures that we never call `rm` with empty input, which would emit an error.

More improvements to test-clean make target

---

php_phongo.c
php_phongo.h
php_phongo_structs.h
src/MongoDB/Cursor.c
tests/cursor/bug1050-001.phpt
tests/cursor/bug1050-002.phpt

https://jira.mongodb.org/browse/PHPC-1050

PHPC-1050: Command cursor should not invoke getMore at execution

---

php_phongo.h
tests/bson/bson-binary-get_properties-001.phpt
tests/bson/bson-binary-get_properties-002.phpt
tests/bson/bson-dbpointer-get_properties-001.phpt
tests/bson/bson-dbpointer-get_properties-002.phpt
tests/bson/bson-decimal128-get_properties-001.phpt
tests/bson/bson-decimal128-get_properties-002.phpt
tests/bson/bson-javascript-get_properties-001.phpt
tests/bson/bson-javascript-get_properties-002.phpt
tests/bson/bson-objectid-get_properties-001.phpt
tests/bson/bson-objectid-get_properties-002.phpt
tests/bson/bson-regex-get_properties-001.phpt
tests/bson/bson-regex-get_properties-002.phpt
tests/bson/bson-symbol-get_properties-001.phpt
tests/bson/bson-symbol-get_properties-002.phpt
tests/bson/bson-timestamp-get_properties-001.phpt
tests/bson/bson-timestamp-get_properties-002.phpt
tests/bson/bson-utcdatetime-get_properties-001.phpt
tests/bson/bson-utcdatetime-get_properties-002.phpt

https://jira.mongodb.org/browse/PHPC-1092
This removes a call to `zend_hash_clean()` on successive calls to a BSON object's `get_properties` handler, which can lead to an infinite loop when iterating the object's properties with foreach on PHP 7.x.
For historical reference, the original call to `zend_hash_clean()` was introduced in ad1f3f049f5c101a8b4f89f13e6384bbefb6ef6c for #607 (PHPC-939).
Note: I've only added tests for BSON classes that have a custom `get_properties` handler and utilize the `PHONGO_GET_PROPERTY_HASH_INIT_PROPS()` macro. I do not recall why I originally added  `zend_clean_hash()`, but I assume I was trying to be strict about not inheriting hash state from previous calls.
While testing this, I was surprised to find that iterating the object with `foreach` actually …

PHPC-1092: Don't reset hash on successive get_properties calls

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1097

PHPC-1097: Report libmongoc compression in phpinfo

---

.travis.yml

dist: trusty is now the default container for travis containers 
os: linux is always true unless otherwise specified in the matrix
only need to specify sudo: false once to run containers
Note: if you need sudo: true for a single job in the matrix you can add it to that single matrix line
Note2: if you need a different dist for a single job in the matrix can add it to that single matrix line
Note3: if you need a different os for a single job in the matrix can add it to that single matrix line
no need for all the duplication

Simplify Matrix

---

src/MongoDB/Command.c
tests/command/cursor-tailable-001.phpt

https://jira.mongodb.org/browse/PHPC-1029
Using $changeStream in an aggregation pipeline implies a tailable/awaitData cursor. Unlike Query, Command does not take these options.
I noticed this while updating docs for the Command constructor.

PHPC-1029: Remove unused Command options in test

---

php_phongo.c
php_phongo_structs.h
src/MongoDB/Command.c
tests/command/cursor-batchsize-001.phpt
tests/command/cursor-batchsize-002.phpt

https://jira.mongodb.org/browse/PHPC-1109

PHPC-1109: Support batchSize getMore option for command cursors

---

CONTRIBUTING.md

Per https://github.com/mongodb/mongo-php-driver/pull/751#discussion_r166977410.

Allow -dev state for non-stable release versions

---

tests/manager/manager-executeCommand_error-003.phpt

https://jira.mongodb.org/browse/PHPC-355

PHPC-355: Add test for ConnectionTimeoutException

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1090
The first commit addresses an issue I noticed with:
* https://github.com/mongodb/mongo-php-driver/commit/1ad6d75b5c47da1095d7647896f66f673019a4b7#diff-c06c6e1c9374aecabcf544157f9d0c26R151
* https://github.com/mongodb/mongo-php-driver/commit/395719ad47527fd239aef02cd73528521730dbac#diff-c06c6e1c9374aecabcf544157f9d0c26R152
The second commit addresses a concern that was in the description for [PHPC-1090](https://jira.mongodb.org/browse/PHPC-1090), which I didn't pick up on while reviewing #768.

PHPC-1090: phongo_exception_from_mongoc_domain fixes

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1144

PHPC-1144: Use server-side error code for BulkWriteException

---

php_phongo.c
tests/manager/manager-executeWriteCommand_error-002.phpt
tests/manager/manager-executeWriteCommand_error-003.phpt

https://jira.mongodb.org/browse/PHPC-578

PHPC-578: Expose result document for failed commands

---

php_phongo.c
tests/bulk/bulkwrite_error-002.phpt

https://jira.mongodb.org/browse/PHPC-1148

PHPC-1148: Throw InvalidArgumentException if BulkWrite is executed multiple times

---

scripts/build/autotools/CheckSSL.m4

https://jira.mongodb.org/browse/PHPC-1156
@kvwalker — as I don't have a Mac, could you test this patch by running ``./configure --with-mongodb-ssl`` and see if it picks Secure Transport please? Before the patch it should (try to) pick OpenSSL.

PHPC-1156: Prefer Secure Transport over OpenSSL with --with-mongodb-ssl on Darwin

---

tests/command/cursor-tailable-001.phpt

This makes the test more robust, since 100ms may not be long enough for the change to appear on some runs. I'll note that 500ms is also what @kvwalker decided to use in PHPLIB's [WatchFunctionalTest](https://github.com/mongodb/mongo-php-library/blob/master/tests/Operation/WatchFunctionalTest.php).

Use longer maxAwaitTimeMS in changeStream test

---

php_phongo.c
php_phongo_structs.h
src/MongoDB/Cursor.c
tests/cursor/bug1151-001.phpt
tests/cursor/bug1151-002.phpt
tests/cursor/bug1151-003.phpt
tests/cursor/bug1151-004.phpt
tests/manager/manager-executeCommand-001.phpt
tests/manager/manager-executeQuery-001.phpt
tests/manager/manager-executeQuery-002.phpt
tests/readPreference/bug0146-001.phpt
tests/readPreference/bug0146-002.phpt
tests/server/server-executeCommand-001.phpt

https://jira.mongodb.org/browse/PHPC-1151
Although Cursors no longer store a reference to client objects, this is similar to what is still done for ReadPreference objects (see: https://github.com/mongodb/mongo-php-driver/commit/78839bde83d3df0d5775485a383d2e67e8a0e969).

 PHPC-1151: Maintain Session reference on Cursor

---

tests/standalone/bug0357.phpt

This fixes a typo introduced in 4967eff7561fec1b5b9219120b8d35601ec85568.

Fix variable name in test

---

php_phongo.c
php_phongo.h

https://jira.mongodb.org/browse/PHPC-578
This fixes an inadvertent side effect of 4b70d9b, which caused test failures for [standalone/executiontimeoutexception-002.phpt](https://github.com/mongodb/mongo-php-driver/blob/master/tests/standalone/executiontimeoutexception-002.phpt).
@kvwalker: Before you review this, please see if that test fails or is skipped on your local environment. I imagine it might have been skipped for some reason (it certainly is on Travis, as the MongoDB servers there don't start with test command enabled).

PHPC-578: phongo_execute_command() should still throw ExecutionTimeoutException

---

.travis.scripts/mo.sh
.travis.yml
tests/apm/overview.phpt
tests/command/cursor-tailable-001.phpt
tests/cursor/bug1050-001.phpt
tests/cursor/bug1050-002.phpt
tests/cursor/cursor-tailable-003.phpt
tests/cursor/cursor-tailable_error-002.phpt
tests/cursorid/cursorid-002.phpt
tests/manager/manager-executeBulkWrite-011.phpt
tests/manager/manager-executeBulkWrite_error-001.phpt
tests/manager/manager-executeBulkWrite_error-002.phpt
tests/manager/manager-executeBulkWrite_error-008.phpt
tests/manager/manager-executeReadWriteCommand-001.phpt
tests/server/server-executeBulkWrite_error-001.phpt
tests/server/server-executeReadWriteCommand-001.phpt
tests/server/server-getTags-001.phpt
tests/standalone/manager-as-singleton.phpt
tests/writeResult/writeresult-getupsertedids-002.phpt
tests/writeResult/writeresult-getwriteerrors-001.phpt
tests/writeResult/writeresult-getwriteerrors-002.phpt

https://jira.mongodb.org/browse/PHPC-1159

PHPC-1159: Test on specific server versions in Travis CI

---

tests/replicaset/writeresult-getserver-002.phpt

bulkwrite_error-002.phpt already covers this case.
Furthermore, this was never the correct exception class. The class in 1.4 and previous versions is is BulkWriteException, which just so happens to be an instance of RuntimeException and satisfy `throws()`; however, https://github.com/mongodb/mongo-php-driver/pull/797 changes the class to InvalidArgumentException in 1.5.

Do not re-execute BulkWrite in WriteResult::getServer() test

---

php_bson.h
src/BSON/functions.c
src/MongoDB/Cursor.c
src/bson-encode.c
src/bson.c
tests/bson/bson-toPHP-007.phpt
tests/bson/typemap-002.phpt
tests/bson/typemap-003.phpt
tests/bson/typemap-004.phpt
tests/bson/typemap-005.phpt
tests/bson/typemap-006.phpt
tests/bson/typemap-007.phpt
tests/bson/typemap-008.phpt
tests/cursor/cursor-setTypeMap_error-003.phpt
tests/cursor/cursor-setTypeMap_error-004.phpt

First step of implementing the fieldPath syntax. It doesn't do wild cards yet, or typemaps for scalar types.

PHPC-314: Implement type map syntax for documents within field paths

---

src/MongoDB/Cursor.c
tests/cursor/bug1162-001.phpt

https://jira.mongodb.org/browse/PHPC-1162
This fixes a segfault while dumping the cursor between iterations with IteratorIterator.

PHPC-1162: Add reference to currentDocument in debug info

---

tests/manager/manager-executeWriteCommand_error-003.phpt

This is to fix errors on [Travis Build 2640](https://travis-ci.org/mongodb/mongo-php-driver/builds/367684798), which appear to be due to differences in responses between server versions.

PHPC-1159: Only run executeWriteCommand_error-003 on mongo version 3.4 or greater

---

php_phongo.c
php_phongo.h
src/MongoDB/Cursor.c
tests/cursor/bug1152-001.phpt
tests/cursor/bug1152-002.phpt
tests/cursor/cursor-session-001.phpt
tests/cursor/cursor-session-002.phpt
tests/cursor/cursor-session-003.phpt
tests/cursor/cursor-session-004.phpt
tests/manager/manager-executeCommand-001.phpt
tests/server/server-executeCommand-001.phpt

https://jira.mongodb.org/browse/PHPC-1152
https://jira.mongodb.org/browse/PHPC-1161
Tests for this patch depend on #811, although I've included a temporary commit with the patch (sans the full patch and tests in #811) to give this PR's own tests a chance at passing.

PHPC-1152, PHPC-1161: Emulate implicit sessions for command cursors

---

tests/causal-consistency/causal-consistency-010.phpt

https://jira.mongodb.org/browse/PHPC-1163
Missed this in https://github.com/mongodb/mongo-php-driver/pull/814. Although Travis is using 3.6 now, I believe it still doesn't use replica sets and therefore skipped this.

PHPC-1163: Ignore exception in causal consistency test

---

bin/prep-release.php

https://jira.mongodb.org/browse/PHPC-1075

PHPC-1075: Remove libbson/libmongoc m4 files from release tarball

---

phongo_compat.c
phongo_compat.h
src/bson-encode.c
tests/bson/bson-fromPHP_error-001.phpt
tests/bson/bson-timestamp_error-006.phpt
tests/bson/bson-utcdatetime_error-004.phpt
tests/bulk/bulkwrite-delete_error-001.phpt
tests/bulk/bulkwrite-update_error-003.phpt
tests/query/query-ctor_error-001.phpt
tests/query/query-ctor_error-002.phpt
tests/writeConcern/writeconcern-ctor_error-002.phpt

http://jira.mongodb.org/browse/PHPC-1166
http://jira.mongodb.org/browse/PHPC-1175
And fixed some annoying test case changes too.

 PHPC-1166: Update zend array recursion protection for PHP 7.3 

---

phongo_compat.h

http://jira.mongodb.org/browse/PHPC-1166
This fixes a build failure introduced by 197f3f7a8a73391cbe489bc900b9f1f1d47d3341 in #835.

PHPC-1166: Don't assume true is defined in phongo_compat.h

---

.gitmodules
bin/prep-release.php
config.m4
scripts/autotools/libbson/CheckHeaders.m4
scripts/autotools/libbson/Versions.m4
scripts/autotools/libmongoc/FindDependencies.m4
src/MongoDB/Cursor.c
tests/manager/bug1163-001.phpt

https://jira.mongodb.org/browse/PHPC-1174
This consolidates CFLAGS for bundled libraries, adds a new "common/" build path, and defines new constants as needed.

PHPC-1174: Bump libbson and libmongoc to 1.10.0-dev

---

phongo_compat.c

https://jira.mongodb.org/browse/PHPC-1166
See:
* http://forums.codeguru.com/showthread.php?253065-Inline-function-Unresolved-external&p=767447#post767447
* https://stackoverflow.com/q/953710/162228
This should resolve Windows build issues I noticed in #836: https://ci.appveyor.com/project/derickr/mongo-php-driver/build/master.207

PHPC-1166: Remove inline hint to fix linking issues on Windows

---

config.m4
config.w32
scripts/autotools/libbson/Versions.m4

https://jira.mongodb.org/browse/PHPC-1174
This should address the [changes](https://github.com/mongodb/mongo-c-driver/compare/b824883...1.10.0) between our last submodule bump and 1.10. Also includes changes to `config.w32` for Windows builds.

PHPC-1174: Upgrade bundled libmongoc to 1.10.0

---

scripts/autotools/libmongoc/CheckSasl.m4

https://jira.mongodb.org/browse/PHPC-1185
https://jira.mongodb.org/browse/PHPC-1142
Reverts support for building with GSS framework on macOS or krb5-gssapi, as libmongoc doesn't support those. Additionally, this fixes an issue with the check for `sasl_client_done`.

PHPC-1185: Revert GSSAPI support and fix sasl_client_done check

---

src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-update-arrayFilters-001.phpt
tests/bulk/bulkwrite-update_error-003.phpt
tests/command/findAndModify-001.phpt
tests/command/update-001.phpt

https://jira.mongodb.org/browse/PHPC-1195
Note: this is waiting on [CDRIVER-2661](https://jira.mongodb.org/browse/CDRIVER-2661). Once that is merged, this PR can be updated to bump the libmongoc submodule to 1.10-dev (assuming the issue is also backported to  the `r1.10` branch).

PHPC-1195: BulkWrite::update() should append arrayFilters as array

---

config.m4

https://jira.mongodb.org/browse/PHPC-1197
This will require some modifications when merging an equivalent change to the master branch.
To test, ensure that you don't have zlib packages available so that the bundled version is picked up.

PHPC-1197: Check for unistd.h when compiling bundled zLib

---

tests/apm/monitoring-commandFailed-003.phpt
tests/apm/overview.phpt
tests/bulk/write-0001.phpt
tests/bulk/write-0002.phpt
tests/command/cursor-tailable-001.phpt
tests/manager/manager-executeWriteCommand_error-002.phpt
tests/manager/manager-executeWriteCommand_error-003.phpt

Various fixes for test failures encountered whilst running against 4.0.0-rc5 in both standalone and replica set modes.
Note: I punted on updating tests that still relied on replica set configurations used by the MO Vagrant enivironment. This includes expectations for particular hosts, ports, number of replica set members, and replica set tags.

Test suite compatibility with server 4.0.0-rc5

---

scripts/presets/replicaset-30.json
scripts/presets/standalone-30.json
scripts/start-servers.php

Improves error reporting for failures in `start-servers.php`.
Also fixes an issue that prevented 3.0 servers from starting successfully after `bind_ip` was added in https://github.com/mongodb/mongo-php-driver/commit/0f2e38730bc68f700fa4cc69543b44fe0ca5f12f (#850). See [SERVER-35705](https://jira.mongodb.org/browse/SERVER-35705) for more info.

Improve error reporting in start-servers.php and fix 3.0 servers

---

tests/command/cursor-tailable-001.phpt
tests/cursor/bug1050-001.phpt
tests/cursor/bug1050-002.phpt

Per [Open A Change Stream](https://docs.mongodb.com/manual/changeStreams/#open-a-change-stream):
> You can only open a change stream against replica sets or sharded clusters. For a sharded cluster, you must issue the open change stream operation against the mongos.
>
> The replica set or the sharded cluster must use replica set protocol version 1 (pv1) and WiredTiger storage engine (can be encrypted).

$changeStream requires WiredTiger storage engine

---

scripts/autotools/libmongoc/CheckSSL.m4
scripts/autotools/libmongoc/CheckSasl.m4

The checks for ICU were already as expected, but both SASL and SSL needed improvements.
I also added ``configure: checking whether {x} is available`` for the SSL checks so that it is more clear which section checks for what in configure output (the dual checks for OpenSSL and LibreSSL confused me at first).

PHPC-1221: Accept "yes" and no value for non-binary PHP_ARG_WITH() options

---

php_phongo.c
src/MongoDB/Exception/RuntimeException.c
tests/apm/overview.phpt
tests/exception/bulkwriteexception-haserrorlabel-001.phpt
tests/exception/bulkwriteexception-haserrorlabel_error-001.phpt
tests/exception/commandexception-haserrorlabel-001.phpt
tests/exception/commandexception-haserrorlabel_error-001.phpt
tests/exception/runtimeexception-haserrorlabel-001.phpt
tests/exception/runtimeexception-haserrorlabel_error-001.phpt
tests/session/transaction-integration-002.phpt

Before we can merge this, we need to branch 1.5 from 1.6 of course. Just wanted your opinion on it. The second commit in this PR we can safely drop. I did the work so I can audit, but am now unsure whether it's wise to get rid of that older API that doesn't take a reply_t as well.

PHPC-1222: Implement accessor for error labels on exception classes

---

tests/session/transaction-integration-001.phpt

`transaction-integration-002.phpt` rightfully catches CommandException, but it looks like that was missed in the first test.

Catch CommandException before calling getResultDocument()

---

scripts/autotools/libmongoc/CheckSSL.m4

I've taking @DaveRandom 's patch from #875 and added the conditional check for OpenSSL < 1.1 from @jmikola's comment on that. I did switch the order of the checking, to check for >= 1.1 before checking for < 1.1. I've tested this locally with 1. pkg-config available, 2. pkg-config unavailable and OpenSSL 1.0.2, and 3. pkg-config unavailable and OpenSSL 1.1.

 PHPC-1241: OpenSSL 1.1 not found if pkg-config is not available 

---

tests/session/transaction-integration_error-001.phpt

This is just a test - not sure which more to add. Documentation still to follow.

PHPC-1227: Add test for disallowed per-op read/write concerns in transactions

---

tests/session/transaction-integration_error-002.phpt
tests/session/transaction-integration_error-003.phpt
tests/session/transaction-integration_error-004.phpt

Added tests for ``executeReadCommand``, ``executeWriteCommand`` and ``executeReadWriteCommand`` too.

PHPC-1227: Add more tests for disallowed per-op read/write concerns in transactions

---

php_phongo.c
tests/manager/manager-ctor-wireversion.phpt

I'm also converting this error to a ConnectionException instead of a RuntimeException

PHPC-1225: Add test to catch unsupported server wire protocol versions

---

tests/cursor/cursor-getmore-005.phpt
tests/cursor/cursor-getmore-006.phpt
tests/cursor/cursor-getmore-007.phpt
tests/cursor/cursor-getmore-008.phpt
tests/utils/basic.inc
tests/utils/skipif.php
tests/utils/tools.php

These tests could not have worked since we moved from a Wire Protocol getMore OP to the OP_COMMAND style of calling ``getMore``. Beats me how we didn't manage to detect this.
The second commit isn't strictly necessary, but it updates the code to be able to throw a ``ConnectionException`` if getMore fails.
Previously, the ``getMore`` tests use a failPoint for the getMore OP, where the driver would then (through ``libmongoc``) throw a ``ConnectionException``.  With the shift to the command-based failPoint, ``libmongoc``/the driver now converted that to a ``ServerException``. This second commit restores that behaviour. Alternatively, we can just update the test to check for a ``ServerException`` instead.

 PHPC-1179: Reimplement tests that start servers with Mongo Orchestration 

---

src/bson.c
tests/bson/bug1266.phpt

https://jira.mongodb.org/browse/PHPC-1266

PHPC-1266: Empty deeply nested BSON document causes unallocated memory writes

---

scripts/autotools/libbson/FindDependencies.m4

The [AC_CHECK_FUNC](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Generic-Functions.html) macro has only the following form:
```m4
AC_CHECK_FUNC(function, [action-if-found], [action-if-not-found])
````
In most cases adding more arguments to macro call don't cause errors, but it also doesn't have any functionality either, so spotting such typos is not obvious at first glance.
The second argument of the macro `[]`, can be also left out.

Fix AC_CHECK_FUNC macro call syntax for rand_r

---

.travis.scripts/mo.sh
.travis.scripts/setup_mo.sh
.travis.yml
scripts/presets/standalone-ssl.json
scripts/presets/travis/standalone/standalone-ssl.json

https://jira.mongodb.org/browse/PHPC-1180

PHPC-1180: Fix STANDALONE_SSL build failures on Travis

---

.evergreen/run-tests.sh
.travis.scripts/setup_mo.sh
tests/manager/manager-ctor-wireversion.phpt

https://jira.mongodb.org/browse/PHPC-1180
Cert validation failures were causing these tests to be skipped. This restores weak cert validation to allow those tests to run. This does not appear to conflict with the few tests we have that utilize strict validation (see: [this JIRA comment](https://jira.mongodb.org/browse/PHPC-1180?focusedCommentId=1992393&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1992393)), since those tests override the URI option we're specifying here.
Ultimately, we'll address the problem with not catching skipped tests in [PHPC-1343](https://jira.mongodb.org/browse/PHPC-1343).

PHPC-1180: Ensure STANDALONE_SSL tests run

---

tests/manager/manager-executeBulkWrite_error-006.phpt

https://jira.mongodb.org/browse/PHPC-1370
Allow an optional suffix since MongoDB 4.1.x uses a more verbose error message.

PHPC-1370: Relax assertion for unknown modifier error

---

.evergreen/config.yml

ARM64 hosts currently do not have the PHP toolchain installed. This can be reverted once the toolchain is restored (see: [PHPC-1372](https://jira.mongodb.org/browse/PHPC-1372)).

Temporarily disable ARM64 hosts in Evergreen

---

php_phongo.c
php_phongo.h
src/MongoDB/Session.c
tests/manager/manager-executeQuery_error-003.phpt

https://jira.mongodb.org/browse/PHPC-1387
This allows executeQuery() to throw a CommandException, which exposes the error document.
In 1.6+, it will also ensure that error labels are set on any RuntimeException thrown during cursor iteration, which is relevant for transactions.

PHPC-1387: Consider error document for cursor exceptions

---

config.m4

https://jira.mongodb.org/browse/PHPC-1378

PHPC-1378: Omit CFLAGS/LDFLAGS in client metadata to avoid platform truncation

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1387
This fixes a few things related to 04b1cc3e14f667080359c2707d2407136f314263 (#983).

PHPC-1387: 1.6.0-dev code fixes after merging v1.5 branch

---

src/MongoDB/Session.c

https://jira.mongodb.org/projects/PHPC/issues/PHPC-1393
Manually verified the leak when running `make test TESTS=tests/session/session-startTransaction_error-004.phpt TEST_PHP_ARGS=-m`. This patch resolves it.

PHPC-1393: Free server description in sharded cluster check

---

.evergreen/config.yml

In addition to adding MongoDB 4.2, I've also added PHP 7.3 as that was missing from the build matrix.
I've split the storage engine test to test MMAPv1 with MongoDB 4.0 and the InMemory and WiredTiger storage engines with MongoDB 4.2. I believe it's not necessary to also test the other storage engines with MongoDB 4.0, but I can add it if deemed necessary.

PHPC-1399: Test MongoDB 4.2 in Evergreen

---

.appveyor.yml

https://jira.mongodb.org/browse/PHPC-1390
Split off from #1002. Since we only test PHP 7.1 on 64-bit architectures, I've done the same for PHP 7.2. PHP 7.3 is tested on both x64 and x86 architectures.

PHPC-1390: Add PHP 7.3 on AppVeyor

---

.travis.yml
tests/cursor/cursor-tailable-001.phpt
tests/cursor/cursor-tailable-002.phpt
tests/cursor/cursor-tailable_error-001.phpt
tests/cursor/cursor-tailable_error-002.phpt

Until we can get PHP 7.4 on evergreen, we'll use travis-ci to ensure the extension compiles and tests pass.
This PR also runs a single job as smoke test to avoid using excessive travis-ci build resources. Other versions and topologies will only be tested if this initial smoke test succeeds. This helps save build resources.

Test against PHP 7.4 on travis-ci

---

src/MongoDB/Session.c
tests/session/session-startTransaction_error-002.phpt
tests/session/session_error-001.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1382
I chose to duplicate the checks in place for the `maxAwaitTimeMS` option on cursors and check for negative and overflowing values, along with a sanity check that the user actually gave us an int for the option.
@jmikola docs are still missing for this PR. While I have my PHP VCS account set up, I'd rather go through the process of writing/publishing docs on php.net with you before adding code there.

 PHPC-1382: Allow applications to set maxTimeMS for commitTransaction

---

src/MongoDB/BulkWrite.c
src/MongoDB/Session.c
tests/bulk/bulkwrite-update-003.phpt
tests/session/session-startTransaction_error-002.phpt
tests/session/session_error-001.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1355
This PR changes update document checks in `\MongoDB\Driver\BulkWrite` to ensure updates with pipelines are treated as updates and not replacements. The detection logic for this is a direct copy from libmongoc since the function is not exposed to users of libmongoc. Even though we're duplicating logic, I don't think exposing the function to the outside is a good idea.

PHPC-1355: Add the ability to specify a pipeline to an update command

---

tests/bson/bson-objectid-getTimestamp-002.phpt

https://jira.mongodb.org/browse/PHPC-1254
ObjectID generation is done completely in libmongoc, which implemented the ObjectID spec with 1.14.0 (introduced in #972). This PR adds the timestamp tests from the test plan in the [ObjectID spec](https://github.com/mongodb/specifications/blob/master/source/objectid.rst).

PHPC-1254: Implement test plan for ObjectID spec

---

php_phongo.c
tests/connect/bug1045.phpt
tests/manager/manager-ctor-auth_mechanism-001.phpt
tests/manager/manager-ctor-auth_mechanism-002.phpt
tests/manager/manager-ctor-auth_mechanism-error-001.phpt

https://jira.mongodb.org/browse/PHPC-1346
Since libmongoc does validation in `mongoc_uri_parse`, passing a username as `option` in `MongoDB\Driver\Manager::construct` effectively bypasses sanity checks on the authentication options. Since the check can't be done in `mongoc_uri_set_username` because the authentication options may change later, we have to replicate the sanity checks from `mongoc_uri_finalize_auth` here.

PHPC-1346: Do not allow empty string for username

---

php_phongo.c
tests/manager/manager-ctor-tls-error-001.phpt
tests/manager/manager-ctor-tls-error-002.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1288
Supersedes #948. This PR also contains a fix for an issue related to #1012. Setting TLS options after parsing the connection string bypasses validation, e.g. checking that the `tlsInsecure` option is not combined with the `tlsAllowInvalidCertificates` or `tlsAllowInvalidHostnames` options. This is now done after applying TLS options to the `mongoc_uri_t` object.

PHPC-1288: Implement Unified URI Options

---

src/MongoDB/Session.c
tests/session/session-startTransaction_error-003.phpt
tests/session/session-startTransaction_error-005.phpt
tests/utils/skipif.php
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1431
https://jira.mongodb.org/browse/PHPC-1435

PHPC-1431, PHPC-1435: Fix Session::startTransaction() param and arginfo

---

src/MongoDB/Cursor.c
tests/cursor/bug1419-001.phpt

https://jira.mongodb.org/browse/PHPC-1419

PHPC-1419: Expose error labels from getMore responses

---

config.m4

https://jira.mongodb.org/browse/PHPC-1428

PHPC-1428: pkg-config requires libbson and libmongoc 1.15.1

---

php_phongo.c
src/MongoDB/BulkWrite.c
src/MongoDB/Command.c
src/MongoDB/Query.c

https://jira.mongodb.org/browse/PHPC-966
I've gone through the structs in `phongo_structs.h` and initialised all scalar fields that weren't initialised. Pointers were left untouched.

PHPC-966: Explicitly initialize fields for internal class structs

---

tests/manager/manager-ctor-server.phpt

https://jira.mongodb.org/browse/PHPC-1343

PHPC-1343: Add test to catch inaccessible server when running tests

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1418
@jmikola: looking at the [diff that introduced PHP 7.3](https://github.com/10gen/mongo-php-toolchain/pull/1/files#diff-a0e5b2ada9d7aee94a81a64d53055dde), I see that PHP 7.0 was removed. However, Evergreen build stages covering PHP 7.0 still complete successfully, so I'm not quite sure what's going on here. Do you know what's going on here, or where I could check to find out?

PHPC-1418: Test PHP 7.3 in Evergreen

---

tests/session/session-startTransaction_error-006.phpt
tests/session/session-startTransaction_error-007.phpt

https://jira.mongodb.org/browse/PHPC-1391
The exeption itself is caused by libmongoc not allowing transactions. This commit only adds tests to protect against regressions.

PHPC-1391: Prohibit starting a transaction for maxWireVersion < 7

---

php_phongo.c
src/MongoDB/Exception/RuntimeException.c
src/MongoDB/Manager.c
src/bson-encode.c

https://jira.mongodb.org/browse/PHPC-870
While strictly speaking the only loop that needs updating us in bson-encode.c (the only one that calls `php_phongo_bson_append`, I thought it was sensible to use indirect macros wherever we check the type of the ZVAL at the current iterator position.

PHPC-870: Use ZEND_HASH_FOREACH indirect macros where applicable

---

src/MongoDB/BulkWrite.c
src/MongoDB/Command.c
src/MongoDB/Query.c

https://jira.mongodb.org/browse/PHPC-1073

PHPC-1073: Remove superfluous calls to php_array_exists

---

src/BSON/ObjectId.c
src/MongoDB/ReadConcern.c
src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c
tests/readConcern/readconcern-serialization-001.phpt
tests/readPreference/readpreference-serialization-001.phpt
tests/writeConcern/writeconcern-bsonserialize-001.phpt
tests/writeConcern/writeconcern-bsonserialize-002.phpt
tests/writeConcern/writeconcern-debug-003.phpt
tests/writeConcern/writeconcern-serialization-001.phpt
tests/writeConcern/writeconcern-var_export-001.phpt

https://jira.mongodb.org/browse/PHPC-1281

PHPC-1281: Serialization support for ReadConcern, ReadPreference, and WriteConcern

---

php_phongo.c
tests/manager/manager-ctor_error-004.phpt

https://jira.mongodb.org/browse/PHPC-1347
Since libmongoc rejects an URI with an empty `replicaSet` URI option, there is different behaviour depending on whether an empty replica set name is passed via the URI string or via the URI options array. The first causes an exception:
> Failed to parse MongoDB URI: 'mongodb://localhost:3000/?replicaSet='. Value for URI option "replicaset" cannot be empty string.
The latter lets users create the manager, but causes a connection exception on server selection:
> Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set)
This PR changes this and checks the `replicaSet` option when it is passed via URI options array, also throwing an exception when the option is explicitly given …

PHPC-1347: Do not allow empty string for replicaSet

---

tests/utils/tools.php

Something I noticed while testing [PHPC-1274](https://jira.mongodb.org/browse/PHPC-1274).

Fix undefined var if throws() fails to catch

---

.evergreen/config.yml
CONTRIBUTING.md
php_phongo.c
src/MongoDB/Manager.c
tests/connect/bug0720.phpt
tests/connect/standalone-ssl-no_verify-001.phpt
tests/connect/standalone-ssl-no_verify-002.phpt
tests/connect/standalone-ssl-verify_cert-001.phpt
tests/connect/standalone-ssl-verify_cert-002.phpt
tests/connect/standalone-ssl-verify_cert-error-001.phpt
tests/connect/standalone-ssl-verify_cert-error-002.phpt
tests/manager/bug0572.phpt
tests/manager/bug0851-002.phpt
tests/manager/bug0940-001.phpt
tests/manager/bug0940-002.phpt
tests/manager/manager-ctor-ssl-deprecated-001.phpt
tests/manager/manager-ctor-ssl-deprecated-002.phpt
tests/manager/manager-set-uri-options-002.phpt
tests/manager/manager-set-uri-options-003.phpt
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-1430
Contrary to what's in the ticket, this PR adds a deprecation notice for the `context` driver option as well, as per the documentation ([source](https://www.php.net/manual/en/mongodb-driver-manager.construct.php)):
> This option [context] is supported for backwards compatibility, but should be considered deprecated.
We can then formally deprecate this in 1.7.0.

PHPC-1430: Deprecate obsolete driver options

---

php_phongo.c
src/BSON/Javascript.c
src/MongoDB/Command.c
src/MongoDB/Monitoring/CommandFailedEvent.c
src/MongoDB/Monitoring/CommandStartedEvent.c
src/MongoDB/Monitoring/CommandSucceededEvent.c
src/MongoDB/Query.c
src/MongoDB/ReadPreference.c
src/MongoDB/Session.c
src/MongoDB/WriteResult.c

https://jira.mongodb.org/browse/PHPC-348
Note: there are three occurrences of `php_phongo_bson_to_zval_ex` in `Cursor.c` ([1](https://github.com/mongodb/mongo-php-driver/blob/987fa38d7f0631bae407f122664e706b6593712f/src/MongoDB/Cursor.c#L126), [2](https://github.com/mongodb/mongo-php-driver/blob/987fa38d7f0631bae407f122664e706b6593712f/src/MongoDB/Cursor.c#L167), [3](https://github.com/mongodb/mongo-php-driver/blob/987fa38d7f0631bae407f122664e706b6593712f/src/MongoDB/Cursor.c#L255)) where I wasn't sure if freeing the result was a good idea.
When used in the `debug_info` functions, I thought it was best to add `null` values and continue assembling the output, but we may want to return without processing any further properties. I'm not quite sure what the preferred course of action is.

PHPC-348: Check for errors after calling bson_to_zval()

---

src/MongoDB/Cursor.c

https://jira.mongodb.org/browse/PHPC-348
Follow-up to #1034, this frees cursor items when BSON conversion fails.

PHPC-348: Free cursor item on invalid BSON

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1372
Evergreen build: https://evergreen.mongodb.com/version/5dc1633361837d7f5d6ecfd0
Currently only tests PHP 7.3 on MongoDB 4.2 and newer, as other versions aren't available.

PHPC-1372: Re-enable ARM64 builds in Evergreen matrix

---

php_phongo.c
php_phongo.h
src/MongoDB/Manager.c

https://jira.mongodb.org/browse/PHPC-1472
@jmikola: I'm not sure what a good way to test this is, as it can only come up when receiving invalid data from the server. Do you have an idea how to verify this indeed works as expected?

PHPC-1472: Prevent multiple exceptions from being thrown while dumping manager

---

src/MongoDB/CursorId.c
tests/cursorid/cursorid-serialization-001.phpt

https://jira.mongodb.org/browse/PHPC-1459
Note that serialising an object will always have the identifier as string for portability between 32-bit and 64-bit platforms. This is consistent with the serialisation handling for `MongoDB\BSON\Int64`.

PHPC-1459: Add serialization support for CursorId

---

tests/bson/bson-utcdatetime-int-size-001.phpt
tests/bson/bson-utcdatetime-int-size-002.phpt

https://jira.mongodb.org/browse/PHPC-1492
UTCDateTime timestamps are always printed as strings.

PHPC-1492: Remove unnecessary EXPECTF patterns

---

php_phongo.c
tests/manager/manager-ctor-ssl-003.phpt

https://jira.mongodb.org/browse/PHPC-1446
The test assumes that the server isn't configured for SSL, which works in our test environment but may not always work. We also need to skip if the URI explicitly enables SSL as we can then no longer test that it's implicitly enabled.

PHPC-1446: Implicitly enable TLS when any TLS-related driver option is set

---

config.m4
config.w32

https://jira.mongodb.org/browse/PHPC-1445

PHPC-1445: Make find commands for collecting sources portable

---

php_phongo.h
src/BSON/Javascript.c

https://jira.mongodb.org/browse/PHPC-1471
This was brought up in the review for #1034. Calling `Z_ADDREF` is unnecessary if we only call `zval_ptr_dtor` when the result actually needs to be destroyed.

PHPC-1471: Clean up reference handling in Javascript scope serialisation

---

.appveyor.yml
config.w32

https://jira.mongodb.org/browse/PHPC-1504
This also includes the commit from #1067 for [PHPC-1503](https://jira.mongodb.org/browse/PHPC-1503).

PHPC-1504: Add PHP 7.4 to AppVeyor build matrix

---

src/MongoDB/ReadPreference.c
tests/readPreference/readpreference-constants.phpt
tests/readPreference/readpreference-getModeString-001.phpt

https://jira.mongodb.org/browse/PHPC-1491

PHPC-1491: Add ReadPreference::getModeString

---

src/MongoDB/Session.c
tests/session/session-constants.phpt
tests/session/session-getTransactionState-001.phpt

https://jira.mongodb.org/browse/PHPC-1438
Contains the libmongoc update from #1060.
I've decided against exposing the `MONGOC_TRANSACTION_` constants directly since we're trying to get rid of that for read preference. I've also opted against introducing constants for those strings for now, but we may consider doing that to allow users to use constants instead of having to write out the strings.

PHPC-1438: Expose session state

---

tests/manager/manager-ctor-ssl-003.phpt

https://jira.mongodb.org/browse/PHPC-1446
`manager-ctor-server.phpt` is intended to be the only test that requires a live server and omits a SKIPIF, as it's intended to alert us if there's some issue with starting the server in our CI test suites. This test only requires that the URI omits an `ssl` or `tls` option, but should require a live server.

PHPC-1446: Require live server for implicit TLS test

---

.travis.scripts/debug-core.sh

This avoids an issue when "php" in the path is just a forwarding shim.
Related to #1076

Set PHP_BINARY from runtime constant

---

phongo_compat.h
php_phongo.c
src/BSON/Binary.c
src/BSON/DBPointer.c
src/BSON/Decimal128.c
src/BSON/Int64.c
src/BSON/Javascript.c
src/BSON/ObjectId.c
src/BSON/Regex.c
src/BSON/Symbol.c
src/BSON/Timestamp.c
src/BSON/UTCDateTime.c
src/MongoDB/BulkWrite.c
src/MongoDB/Cursor.c
src/MongoDB/ReadPreference.c
src/MongoDB/Session.c
src/bson.c

As per the suggestion in https://github.com/mongodb/mongo-php-driver/pull/1071#discussion_r364075950, this PR fixes pre-existing code style errors that were missed in previous PRs.
Note: a few changes in PHP 5 compatible code had to be excluded manually. Since this code will be dropped after the next release anyways, I didn't investigate any further.

Run clang-format on existing sources

---

php_phongo.c
php_phongo.h
php_phongo_structs.h
src/MongoDB/Cursor.c
src/MongoDB/Manager.c
src/MongoDB/Server.c
src/MongoDB/Session.c
tests/cursor/bug1274-001.phpt
tests/cursor/bug1274-002.phpt
tests/cursor/bug1274-003.phpt
tests/session/bug1274-001.phpt
tests/session/bug1274-002.phpt

https://jira.mongodb.org/browse/PHPC-1274
This PR will supersede both https://github.com/mongodb/mongo-php-driver/pull/941 and https://github.com/mongodb/mongo-php-driver/pull/1027

PHPC-1274: Do not allow forked children to affect parent resources

---

tests/session/bug1274-002.phpt

https://jira.mongodb.org/browse/PHPC-1526

PHPC-1526 Exclude sharded RS env in session forking test

---

config.m4

https://jira.mongodb.org/browse/PHPC-1497
The new `--with-system-libs` configure switch replaces `--with-libmongoc` and `--with-libbson`, since they both needed to have the same value. Passing `--with-system-libs=yes` will always compile against system libraries, regardless of the `--with-libmongoc` and `--with-libbson` options. When one of these two options is used, a message is printed alerting the user that the settings are deprecated and they should use `--with-system-libs` instead.
Since neither libmongoc nor libbson option took a path where to find the libraries, it is better to use this compound switch. However, if downstream packages need to supply custom paths for libbson or libmongoc, we may opt to keep the individual options instead.  Ping @remicollet and @oerdnj for feedback …

PHPC-1497: Introduce new configure switch to use system libraries

---

php_phongo.c
tests/clientEncryption/clientEncryption-ctor-error-002.phpt
tests/manager/manager-createClientEncryption-001.phpt
tests/manager/manager-createClientEncryption-error-001.phpt
tests/manager/manager-createClientEncryption-error-002.phpt
tests/manager/manager-ctor-auto_encryption-error-003.phpt

https://jira.mongodb.org/browse/PHPC-1545

PHPC-1545: Require object or array type for "kmsProviders" option

---

.appveyor/build_task.cmd
CONTRIBUTING.md
config.m4
config.w32

https://jira.mongodb.org/browse/PHPC-1520
https://jira.mongodb.org/browse/PHPC-1546
Note: I wasn't able to test this locally, as I don't have a Windows build environment on my laptop. I'll see if I can validate the absence of warnings from AppVeyor logs; otherwise, I'll double-check Friday when I'm back in the office.

PHPC-1546, PHPC-1520: Enable SASL/FLE for Windows builds and define KMS_MSG_STATIC for bundled libmongocrypt

---

tests/clientEncryption/clientEncryption-decrypt-001.phpt
tests/clientEncryption/clientEncryption-encrypt-001.phpt

This fixes build failures on Evergreen due to key vault queries using a read concern which isn't available on MMAPv1.

PHPC-1499: Skip encryption tests on MMAPv1 storage engine

---

php_phongo.c
tests/manager/manager-ctor-driver-metadata-001.phpt
tests/manager/manager-ctor_error-005.phpt

https://jira.mongodb.org/browse/PHPC-1494
This adds a new "driver" driver option, which can be used to pass custom driver metadata to be used in the server handshake.

PHPC-1494: Add client metadata support for wrapping libraries

---

php_phongo.c
tests/manager/manager-ctor-auth_mechanism-error-001.phpt
tests/manager/manager-ctor-auth_source-001.phpt

https://jira.mongodb.org/browse/PHPC-1591
Note that the suggested test in the ticket was not added as the C driver currently does not pass that test.

PHPC-1591: Add tests for allowed cases when authSource is given but username is not

---

config.w32

Depends on AppVeyor build fixes from #1128. Only the last commit pertains to this PR.
This fixes a typo in the path to libongoc's KMS sources from #1105

Fix path name for libmongoc KMS sources in config.w32

---

php_phongo.c
scripts/autotools/libmongoc/CheckCompression.m4

https://jira.mongodb.org/browse/PHPC-1313

PHPC-1313: Support Zstandard compression

---

tests/manager/manager-ctor-directconnection-001.phpt
tests/manager/manager-ctor-directconnection-error-001.phpt
tests/manager/manager-ctor-directconnection-error-002.phpt

https://jira.mongodb.org/browse/PHPC-1554
No code changes were needed as [`php_phongo_apply_options_to_uri`](https://github.com/mongodb/mongo-php-driver/blob/89b29ede8e276468db244eb752cb60c50edd926e/php_phongo.c#L1484) already handles boolean options in the URI.

PHPC-1554: Tests for directConnection URI option

---

src/MongoDB/ReadPreference.c
src/MongoDB/WriteConcern.c
tests/writeConcern/writeconcern-ctor_error-005.phpt
tests/writeConcern/writeconcern-serialization_error-001.phpt

https://jira.mongodb.org/browse/PHPC-1629
This PR adds `is_valid` checks for read preference and write preference initialisation. While adding this, I noticed that the initialisation logic for write concern did not check for an invalid combination of unacknowledged writes and journaling, leading to a rather unhelpful "Write concern is not valid" message. This has been rectified, with the `mongoc_write_concern_is_valid` check there as a last resort should we miss any checks added in libmongoc.

PHPC-1629: Call libmongoc is_valid functions before completing WriteConcern and ReadPreference initialization

---

.evergreen/config.yml
tests/functional/phpinfo-2.phpt

Add MongoDB 4.4 to all build variants and ensures that selective tests (e.g. OCSP) test against 4.4 and latest. See also https://jira.mongodb.org/browse/PHPC-1635.

Add MongoDB 4.4 to tested server versions

---

src/MongoDB/Manager.c
tests/manager/manager-executeCommand-006.phpt

https://jira.mongodb.org/browse/PHPC-1639
~I've fixed this in 1.8 for the time being, but can re-target this PR on 1.7 for a July patch release. I've implemented this in 1.8 for the time being, since merging up from 1.7 to 1.8 would cause additional work due to the removal of `TSRMLS` macros in function signatures.~

PHPC-1639: Manager::executeCommand should not inherit read preference

---

CONTRIBUTING.md

https://jira.mongodb.org/browse/PHPC-1660
Related to #1147

PHPC-1660: Always refer to explicit version in PECL example for non-stable release notes

---

config.m4

https://jira.mongodb.org/browse/PHPC-479
Output:
```
$ ./configure --with-mongodb-system-libs=yes
[...]
Build configuration:
CFLAGS                                           : -g -O2
Extra CFLAGS                                     :  
Developers flags (slow)                          : 
Code Coverage flags (extra slow)                 : 
libmongoc                                        : System (1.16.2)
libbson                                          : System (1.16.2)
libmongocrypt                                    : None
LDFLAGS                                          : 
EXTRA_LDFLAGS                                    : 
MONGODB_SHARED_LIBADD                            : -Wl,-rpath,/usr/local/Cellar/mongo-c-driver/1.16.2/lib -L/usr/local/Cellar/mongo-c-driver/1.16.2/lib …
```

PHPC-479: Print library version for libmongoc, libbson, and libmongocrypt

---

php_phongo.c
php_phongo_structs.h
src/MongoDB/BulkWrite.c
tests/bulk/bulkwrite-debug-001.phpt
tests/bulk/bulkwrite-debug-002.phpt
tests/bulk/write-0001.phpt
tests/bulk/write-0002.phpt

PHPC-1167
This solution is similar to the cursor solution implemented for PHPC-1151. The bulk write keeps a copy of the session object to ensure it won't go out of scope directly after executing the bulk write. Since we don't have a use-after-free (since the session is not accessed after the bulk write has been executed), there are no tests to guard against regressions.

PHPC-1167: Avoid dangling session pointer in bulk writes

---

php_phongo.c
tests/exception/bulkwriteexception-haserrorlabel-002.phpt

https://jira.mongodb.org/browse/PHPC-1683
Also adds additional type and error checking to phongo_exception_append_error_labels.

PHPC-1683: Collect WCE error labels in libmongoc bulk write replies

---

src/MongoDB/Session.c

https://jira.mongodb.org/browse/PHPC-1687
No test changes, as the fix can be verified with:
```
TEST_PHP_ARGS=-m make test TESTS=tests/session/session-commitTransaction-001.phpt
```
Also confirmed that this fixes the original bug report in #1163.

PHPC-1687: Always free reply from commit_transaction

---

scripts/autotools/libmongoc/FindDependencies.m4

PHPC-1703. Closes #1168.
@NattyNarwhal pointed out that the check was reversed, and after a bit of critical thinking, I agree.
@jwoehr this should fix your issue. If you want to you can check out the head branch for this PR (or apply the patch manually) and retry compilation.

PHPC-1703: Fix wrong assignment of MONGOC_HAVE_SS_FAMILY

---

config.w32

PHPC-1704
In PHP 8, PHP 7.3.25+, and PHP 7.4.13+, ADD_EXTENSION_DEP can correctly check for the date and standard extensions. On older versions, we have to continue to assume that these extensions are in fact installed.
Note: I'll hold off on merging this until the release candidates for 7.3.25 and 7.4.13 are available, which they should be in a couple of days. Then I can confirm that these checks work as they should.

PHPC-1704: Check for standard and date extensions on Windows builds

---

scripts/autotools/CheckHost.m4
scripts/autotools/libmongoc/CheckResolv.m4

On AIX, the resolver functions are in libc, so trying libresolv
will cause the checks to fail. The behaviour should be instead
like AC_SEARCH_LIBS.
This hardcodes a check not to use libresolv on AIX. Better than
nothing, but it may not compensate for other systems without a
libresolv.
Fixes  #1171

Don't try linking against libresolv on AIX

---

src/MongoDB/ReadPreference.c
tests/manager/bug1701-001.phpt
tests/readPreference/bug1698-001.phpt

PHPC-1700
This fixes a memory leak in `php_phongo_readpreference_init_from_hash` that is caused by not properly separating zvals before modifying read preference tags. The issue can be observed when `MongoDB\Driver\ReadPreference::__set_state` errors after preparing tag sets (e.g. because tags were combined with a primary mode). Contrary to the original issue, this problem does not affect other instances where the underlying logic from `php_phongo_read_preference_prep_tagsets` is used, as the same test (tags with primary read preference) does not leak in the ReadPreference constructor.
This PR also adds a regression test for PHPC-1701 that also assumed the same issue would apply when preparing properties for authentication mechanisms. This test does not leak since all involved zvals are …

PHPC-1700: Fix memory leak when read preference is invalid

---

src/MongoDB/Cursor.c
tests/cursor/bug1713-001.phpt

PHPC-1713: Ensure Cursor::current returns null on invalid positions

---

php_phongo.c
php_phongo.h

https://jira.mongodb.org/browse/PHPC-1722
https://jira.mongodb.org/browse/PHPC-1366
https://jira.mongodb.org/browse/PHPC-1367
This ensures persistent clients in all threads are freed, not just those in the main thread. Doing so also required that we call mongoc_cleanup and bson_mem_restore_vtable in the final GSHUTDOWN (tracked by an atomic counter).
This also moves the vtable to a local variable in MINIT and swaps the order of mongoc_init and bson_mem_set_vtable (and the corresponding teardown functions) so that PHP's allocators will be used for all of libmongoc.

PHPC-1722: Destroy persistent clients in GSHUTDOWN

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1737
Also includes a second commit improving the comments for request-scoped HashTables.
I manually tested that `zend_hash_graceful_destroy` causes a segfault for `keyVaultClient` tests, so we can be certain that `zend_hash_graceful_reverse_destroy` is doing its job.

PHPC-1737: Use zend_hash_graceful_reverse_destroy for persistent client HashTable

---

.gitignore
php_phongo.c
tests/cursor/bug1529-001.phpt

PHPC-1529
Fixing this in master to take advantage of the new disableClientPersistence option for tests. The test was a bit tricky to write, but I managed to verify that the keyVaultClient is reset by triggering a reset on the client (by running a query in the fork), then trying to iterate a cursor that was previously opened on the keyVaultClient. With the additional call to `php_phongo_client_reset_once` removed, this test fails as expected.

PHPC-1529: Reset libmongocrypt key vault client after forking

---

src/MongoDB/Cursor.c
tests/cursor/cursor-iterator-003.phpt

PHPC-1748 Fix wrong return value of Cursor::key when iterator is not valid

---

phongo_compat.h

With clang 12, build failures appear due to an implicit fallthrough:
```
src/bson-encode.c:314:3: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
case IS_OBJECT: {
^
src/bson-encode.c:314:3: note: insert '__attribute__((fallthrough));' to silence this warning
case IS_OBJECT: {
^
__attribute__((fallthrough)); 
src/bson-encode.c:314:3: note: insert 'break;' to avoid fall-through
case IS_OBJECT: {
^
break; 
1 error generated.
```

Fix build failures with clang 12

---

php_phongo.c

https://jira.mongodb.org/browse/PHPC-1720

PHPC-1720: Move mongoc_client_set_error_api after check for null client pointer

---

.evergreen/compile-unix.sh
.evergreen/config.yml

This PR changes the evergreen build config to no longer set a specific patch version for PHP, instead only setting the minor version to be used (e.g. "7.4"). This reduces the workload associated with updating the PHP toolchain, since we no longer need to update the evergreen config when the toolchain brings new patch releases for PHP. The path to PHP binaries is now also prepended to the `PATH` environment variable.
The script will attempt to fetch the latest patch version for the requested PHP version (by using the version sort functionality of `sort`) and error if none was found. The logic will need adjusting if we want to start testing against thread-safe versions of PHP.
These changes will be ported to the PHPLIB evergreen config once they've been merged here.

Automatically detect PHP patch version

---

.evergreen/config.yml
.evergreen/run-tests.sh

I discovered this by pure accident. run-tests.php supports writing a junit output file, which we can attach on Evergreen to get a better overview over passing/failing tests.

Write test results to junit log file

---

php_phongo.c
tests/manager/manager-ctor-driver-metadata-001.phpt

PHPC-1774
@jmikola testing this is notoriously difficult, as I can't add the expected value of `PHP_VERSION` into the `EXPECTF` block. If you have any suggestion how to prevent regressions against this, please let me know.

PHPC-1774 Fix truncation of PHP_VERSION constant in handshake metadata

---

.evergreen/config.yml
.evergreen/orchestration/configs/replica_sets/basic-ssl.json
.evergreen/orchestration/configs/replica_sets/basic.json
tests/server/server-executeQuery-008.phpt
tests/server/server-getTags-002.phpt

While changing test setup to rely on drivers-evergreen-tools, I missed that the `AUTH` variable needs to be "auth" for drivers-evergreen-tools while "yes" was used for our own scripts. This PR updates the build config and fixes a test that can be flaky due to potential elections in the replica set.

Fix running auth tests

---

.github/workflows/tests.yml
src/MongoDB/BulkWrite.c

https://jira.mongodb.org/browse/PHPC-1793
zend_ce_countable was introduced in PHP 7.2 (see: php/php-src@27e7aea4124ffdecb6d40a2f5723e413a7b40562) and spl_ce_Countable was removed in PHP 8.1 (see: php/php-src@4f4c031f62e28ed53869a57264535a8739a010e9).

PHPC-1793: Use zend_ce_countable for PHP 8.1+ compat

---

.evergreen/compile-unix.sh
.evergreen/compile-windows.sh
.evergreen/compile.sh
.evergreen/config.yml
.evergreen/run-ocsp-responder.sh
.evergreen/run-tests.sh

PHPC-1795 Remove xtrace from build scripts

---

.evergreen/config.yml
tests/manager/manager-executeBulkWrite_error-004.phpt
tests/manager/manager-executeQuery_error-003.phpt

PHPC-1848
This also updates the config file to use a `latest-stable` alias to avoid having to update multiple build variants when it changes.

PHPC-1848: Add 5.0 to the server testing matrix

---

php_phongo.h

https://jira.mongodb.org/browse/PHPC-1513

PHPC-1513: Remove php_phongo_cursor_to_zval

---

php_phongo.c
src/bson-encode.c

https://jira.mongodb.org/browse/PHPC-1721

PHPC-1721: Fix argument order for some ecalloc function calls

---

.appveyor.yml

Note: I expect these to fail for reasons explained in https://github.com/mongodb/mongo-php-driver/pull/1229#issuecomment-866419799.

Bump PHP versions tested by AppVeyor

---

src/phongo_apm.c
tests/server/server-executeQuery-008.phpt

This should fix zSeries build failures introduced by 324182a8e6c840297dad02a9bb6a37919f0d2b53 (#1213)
Patch build with zSeries hosts: https://spruce.mongodb.com/version/60d641ced1fe074ffa5b2877/tasks

PHPC-1870: Include config.h after php.h to avoid redef of WORDS_BIGENDIAN

---

.evergreen/config.yml
bin/package.xml.in
config.m4

PHPC-1685
While we're only removing the (now deprecated) `SetUpTearDownTrait` at this time, more significant changes will happen once we drop PHP 7.1, as this allows us to start introducing argument types.

PHPC-1685 Drop support for PHP 7.0

---

src/MongoDB/Session.c
tests/session/session-debug-001.phpt
tests/session/session-debug-002.phpt
tests/session/session-debug-003.phpt
tests/session/session-debug-004.phpt
tests/session/session-debug-005.phpt
tests/session/session-debug-006.phpt

https://jira.mongodb.org/browse/PHPC-1474
https://jira.mongodb.org/browse/PHPC-1879

PHPC-1474 and PHPC-1879: Expose transaction information in debug info for session and fix Session::getTransactionOptions() leak

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1782
https://jira.mongodb.org/browse/PHPC-1877

PHPC-1782 and PHPC-1877: Do not test MongoDB 5.0 on zseries and power8

---

.evergreen/config.yml

This updates the list of tested libmongoc versions to include 1.18.0 (lowest supported), 1.18-dev (upcoming stable), and 1.19-dev (latest dev) on evergreen. Github Actions continues to only test with the bundled version.

Update list of tested libmongoc versions

---

php_phongo.h

From UPGRADING.INTERNALS 
```
f. Non-serializable classes should be indicated using the
ZEND_ACC_NOT_SERIALIZABLE (@not-serializable in stubs) rather than the
zend_class_(un)serialize_deny handlers which are removed.
```

PHPC-1922 Update PHONGO_CE_DISABLE_SERIALIZATION for PHP 8.1

---

src/MongoDB/ServerDescription.c
tests/server/server-getServerDescription-001.phpt
tests/serverDescription/serverDescription-constants.phpt
tests/serverDescription/serverDescription-debug-001.phpt
tests/serverDescription/serverDescription-getType-001.phpt
tests/serverDescription/serverDescription-var_export-001.phpt

https://jira.mongodb.org/browse/PHPC-1925

PHPC-1925: Change ServerDescription::getType() to return a string

---

src/MongoDB/CursorId.c

https://jira.mongodb.org/browse/PHPC-1930

PHPC-1930: Removed disabled __wakeup() function in CursorId

---

tests/utils/tools.php

The original implementation of raises() in c6a793d466ef1dda46ce33bbd5e2d77e914249bb apparently referenced an undeclared $exceptionname variable several times. That was later addressed 804f383aea602c2bf3698169d893fc3cd2f10782 but that commit neglected to fix this reference.
This change avoids a possible message where the actual exception is printed twice:
```
ALMOST: Got Exception - expected Exception
```
Given the [error handler](https://www.php.net/set_error_handler) implementation here, we should always except an [ErrorException](https://www.php.net/manual/en/class.errorexception.php).

Fix message for catching wrong exception in raises()

---

tests/utils/skipif.php

https://jira.mongodb.org/browse/PHPC-1975

PHPC-1975: Disable SKIPIF caching for skip_if_not_clean on PHP 8.1

---

tests/session/session-004.phpt

https://jira.mongodb.org/browse/PHPC-1875
skip_if_not_replica_set will be more portable once we start testing on load balancers, which will back sharded clusters.

PHPC-1875: Skip snapshot error test on sharded clusters

---

php_phongo.c
src/BSON/UTCDateTime.c

https://jira.mongodb.org/projects/PHPC/issues/PHPC-1982
https://jira.mongodb.org/projects/PHPC/issues/PHPC-1983

PHPC-1982, PHPC-1983: Fix some Windows build warnings

---

.evergreen/compile-unix.sh
.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-1994
Also updates versions in the libmongoc-version axis.
Patch build: https://evergreen.mongodb.com/version/61817ad632f4176849ae7849
Note: libmongoc 1.20 (master) fails due to [PHPC-1997](https://jira.mongodb.org/browse/PHPC-1997). We'll address that in the next PHPC release.

PHPC-1994: Fix Evergreen testing for custom libmongoc versions

---

src/BSON/Binary.c
src/BSON/BinaryInterface.c
src/BSON/DBPointer.c
src/BSON/Decimal128.c
src/BSON/Decimal128Interface.c
src/BSON/Int64.c
src/BSON/Javascript.c
src/BSON/JavascriptInterface.c
src/BSON/ObjectId.c
src/BSON/ObjectIdInterface.c
src/BSON/Regex.c
src/BSON/RegexInterface.c
src/BSON/Symbol.c
src/BSON/Timestamp.c
src/BSON/TimestampInterface.c
src/BSON/UTCDateTime.c
src/BSON/UTCDateTimeInterface.c
src/BSON/Undefined.c
src/MongoDB/CursorId.c
tests/session/session-advanceOperationTime-003.phpt
tests/session/session-advanceOperationTime_error-001.phpt

https://jira.mongodb.org/browse/PHPC-2004
https://jira.mongodb.org/browse/PHPC-2007
See https://externals.io/message/116308#116318 for context. There is a subtle BC break here, as userland classes implementing our BSON interfaces will now need to explicitly specify a string return type on PHP versions before 8.1 (where it's added automatically). AFAICT, the only way to avoid the BC break entirely would be to continue to omit return type info and let PHP 8.1+ add the return type info and Stringable implementation automatically; however, that's not a permanent solution as PHP 8.2 will start raising warnings for the automatic behavior (https://github.com/php/php-src/commit/86379b6710f972e0d4a11c89ce28d5768d9824d3).
For that reason, I'm inclined to explicitly add return type info and …

PHPC-2004 and PHPC-2007: Specify __toString() return type and implement Stringable

---

src/BSON/BinaryInterface.c
src/BSON/Decimal128Interface.c
src/BSON/JavascriptInterface.c
src/BSON/ObjectIdInterface.c
src/BSON/RegexInterface.c
src/BSON/TimestampInterface.c
src/BSON/UTCDateTimeInterface.c
tests/session/session-advanceOperationTime-003.phpt
tests/session/session-advanceOperationTime_error-001.phpt

https://jira.mongodb.org/browse/PHPC-2004
This should avoid the BC break introduced in 6c82ec8b52fad33c3e9444ae8bd2c27a729c4688. PHP 8.1 will automatically add return type info for Stringable, which means the ReturnTypeWillChange attribute should not be necessary on userland classes.

PHPC-2004: Use tentative return types for BSON interface toString methods

---

tests/replicaset/writeresult-getserver-002.phpt

https://jira.mongodb.org/browse/PHPC-2008
MO should now grant the necessary roles as of 10gen/mongo-orchestration@4e1ab405fe880ab278617b980476c6e1dacdd5cf.

PHPC-2008: Re-enable writeresult-getserver-002 for replicaset-auth

---

.appveyor.yml
tests/standalone/executiontimeoutexception-001.phpt
tests/standalone/executiontimeoutexception-002.phpt

https://jira.mongodb.org/browse/PHPC-2027

PHPC-2027: Add PHP 8.1 to AppVeyor and bump older versions

---

php_phongo.c
src/MongoDB/Manager.c
tests/apm/commandStartedEvent-002.phpt
tests/apm/serverClosedEvent-001.phpt
tests/apm/topologyClosedEvent-001.phpt
tests/server/server-getLatency-002.phpt

https://jira.mongodb.org/browse/PHPC-2023
https://jira.mongodb.org/browse/PHPC-2030

PHPC-2023 and PHPC-2030: Allow observation of events dispatched during client destruction

---

src/BSON/UTCDateTime.c

https://jira.mongodb.org/browse/PHPC-2042
This dates back to 29a372916c5a5b7544006dd69a54fa3f373d56e6 but should no longer be necessary as of 6eaa91b87bbf5760a9bf6a6a13f911274da02253, which switched gettimeofday() to the libbson compat function.

PHPC-2042: Remove conditional win32/time.h include

---

.evergreen/config.yml
tests/connect/bug0720.phpt
tests/connect/standalone-ssl-no_verify-001.phpt
tests/connect/standalone-ssl-no_verify-002.phpt
tests/connect/standalone-ssl-no_verify-003.phpt
tests/connect/standalone-ssl-verify_cert-001.phpt
tests/connect/standalone-ssl-verify_cert-002.phpt
tests/connect/standalone-ssl-verify_cert-003.phpt
tests/manager/bug0572.phpt
tests/manager/manager-set-uri-options-002.phpt

https://jira.mongodb.org/browse/PHPC-2047
Upstream changes in drivers-evergreen-tools now require passing LOAD_BALANCER to run-orchestration.sh. Additionally, service ID mocking is no longer required as of server version 5.1.

PHPC-2047: Update load balancer testing config

---

.evergreen/config.yml

https://jira.mongodb.org/browse/PHPC-2086
Complete patch build: https://spruce.mongodb.com/version/62acbccd0305b944a333e249/tasks

PHPC-2086: Test against MongoDB 6.0 in Evergreen and revise matrices

---

.evergreen/config.yml

PHPC-2118
Corresponding patch build: https://spruce.mongodb.com/version/62f35f4c3627e01ee6a79032/tasks

PHPC-2118: Test load-balanced on debian11

---

tests/bson/bson-decimal128-001.phpt
tests/bson/bson-decimal128-002.phpt
tests/bson/bson-decimal128-003.phpt
tests/bson/bson-decimal128-004.phpt
tests/bson/bson-decimal128-clone-001.phpt
tests/bson/bson-decimal128-clone-002.phpt
tests/bson/bson-decimal128-get_properties-001.phpt
tests/bson/bson-decimal128-get_properties-002.phpt
tests/bson/bson-decimal128-jsonserialize-001.phpt
tests/bson/bson-decimal128-jsonserialize-002.phpt
tests/bson/bson-decimal128-set_state-001.phpt
tests/bson/bson-decimal128-set_state_error-001.phpt
tests/bson/bson-decimal128-set_state_error-002.phpt
tests/bson/bson-decimal128_error-001.phpt

Since Decimal128 is always available in current versions of the extension, these SKIPIFs should be removed.
[PHPC-1945](https://jira.mongodb.org/browse/PHPC-1945)

PHPC-1945: Remove class_exists checks from SKIPIF blocks in Decimal128 tests

---

src/BSON/Decimal128.stub.php
src/BSON/Decimal128_arginfo.h
src/MongoDB/BulkWrite.stub.php
src/MongoDB/BulkWrite_arginfo.h
src/MongoDB/ClientEncryption.stub.php
src/MongoDB/ClientEncryption_arginfo.h
src/MongoDB/Command.stub.php
src/MongoDB/Command_arginfo.h
src/MongoDB/Manager.stub.php
src/MongoDB/Manager_arginfo.h
src/MongoDB/Query.stub.php
src/MongoDB/Query_arginfo.h
src/MongoDB/Server.stub.php
src/MongoDB/Server_arginfo.h
src/MongoDB/Session.stub.php
src/MongoDB/Session_arginfo.h

PHPC-2124
While reviewing code for the docs, I realised that these stubs don't correspond to the actual ZPP info, which takes precedence as it enforces parsing rules.

PHPC-2124: Ensure that null is still accepted for optional parameters

---

src/MongoDB/Monitoring/CommandFailedEvent.stub.php
src/MongoDB/Monitoring/CommandFailedEvent_arginfo.h
src/MongoDB/Monitoring/ServerHeartbeatFailedEvent.stub.php
src/MongoDB/Monitoring/ServerHeartbeatFailedEvent_arginfo.h
src/MongoDB/WriteConcern.stub.php
src/MongoDB/WriteConcern_arginfo.h

PHPC-2015
This fixes some return types mentioned in https://github.com/alcaeus/doc-en/pull/3

PHPC-2015: Fix wrong return types in stubs

---

.evergreen/config.yml
tests/utils/tools.php

https://jira.mongodb.org/browse/PHPC-2131
Note: I opened this against the v1.14 branch to ensure it gets tested with `crypt_shared`, since that's when [PHPC-2045](https://jira.mongodb.org/browse/PHPC-2045) was implemented.
Patch build: https://spruce.mongodb.com/version/630e26002a60ed23408418e7/tasks

PHPC-2131: Ensure CRYPT_SHARED_LIB_PATH is exported for tests

---

.evergreen/config.yml
.evergreen/run-tests.sh

https://jira.mongodb.org/browse/PHPC-2135
This PR also includes quite a bit of shell script cleanup based on my conversation with @rcsanchez97 in [#driver-devs](https://mongodb.slack.com/archives/C72LB5RPV/p1661962557817589).
Full patch build: https://spruce.mongodb.com/version/630faa1d0305b97199243780/tasks

PHPC-2135: Test with consistent version of crypt_shared

---

tests/server/server-executeBulkWrite-005.phpt

PHPC-2121
In an effort to reach a green CI, I decided to skip this failing test since it's tracked as failing-on-waterfall.
---
As an aside, this sent me down a deep rabbit hole trying to figure out why I couldn't get the test to properly skip. The culprit is the SKIPIF caching introduced in PHP 8.1 (as noticed by @jmikola before - see #1301 and https://github.com/php/php-src/pull/8076). Until we properly fix this, `skip_if_not_clean` has to be the last SKIPIF check. In a case of not optimising early enough, I added the `skip_if_server_version` check to the bottom, which caused `run-tests.php` to truncate its output due to `nocache` appearing before.

PHPC-2121: Skip failing test

---

tests/utils/skipif.php

PHPC-2064
Replaces #1301
As is, using any logic in a `SKIPIF` block after a previous call to `skip_if_not_clean` leads to the tests not being skipped. This is due to PHP 8.1+ reading the `nocache` output and discarding any subsequent output. To resolve this, we can change `disable_skipif_caching` to register a shutdown function that disables caching by printing `nocache` to `STDOUT`. While this can lead to skip messages containing an extra `nocache` at the end, I believe this is preferable to `SKIPIF` logic being ignored. I also believe it's not worth adding any logic to not print anything if a previous check resulted in `skip ...` being printed.

PHPC-2064: Use register_shutdown_function to disable caching of skipif results

---

tests/readConcern/readconcern-bsonserialize-001.phpt
tests/readConcern/readconcern-bsonserialize-002.phpt
tests/readConcern/readconcern-ctor-001.phpt
tests/readConcern/readconcern-debug-001.phpt
tests/readConcern/readconcern-getlevel-001.phpt
tests/readConcern/readconcern-serialization-001.phpt
tests/readConcern/readconcern-serialization-002.phpt
tests/readConcern/readconcern-set_state-001.phpt
tests/readConcern/readconcern-var_export-001.phpt

https://jira.mongodb.org/browse/PHPC-1929
Related to https://jira.mongodb.org/browse/PHPC-1761

PHPC-1929: ReadConcern tests need not exhaustively test each constant

---

src/MongoDB/WriteResult.c
tests/manager/manager-executeBulkWrite-012.phpt
tests/server/server-executeBulkWrite-002.phpt
tests/server/server-executeBulkWrite-003.phpt
tests/server/server-executeBulkWrite-005.phpt
tests/server/server-executeBulkWrite-006.phpt
tests/writeResult/writeresult-getdeletedcount-002.phpt
tests/writeResult/writeresult-getinsertedcount-002.phpt
tests/writeResult/writeresult-getmatchedcount-002.phpt
tests/writeResult/writeresult-getmodifiedcount-002.phpt
tests/writeResult/writeresult-getupsertedcount-002.phpt

PHPC-2141
With this change, we're deprecating calling the various `get<field>Count` methods on unacknowledged write results. In 2.0, this will throw an exception, as is already done in the PHP library. For fields missing in the response, we no longer return `null`, but rather `0` to make the method signature more compatible. In 2.0, the return value of these methods will change from `int|null` to `int`.

PHPC-2141: Emit deprecation notice for WriteResult getters with unacknowledged writes

---

.appveyor.yml

This PR updates PHP versions to the latest stable version and adds PHP 8.2.0RC4 to the build matrix.
The default image has been changed to Visual Studio 2019 and the matrix configuration inverted; this is to simplify the configuration when adding new PHP versions.

PHPC-2154: Test PHP 8.2 on Appveyor

---

src/BSON/Javascript.c
src/BSON/functions.c
src/MongoDB/BulkWrite.c
src/MongoDB/ClientEncryption.c
src/MongoDB/Command.c
src/MongoDB/Cursor.c
src/MongoDB/Monitoring/CommandFailedEvent.c
src/MongoDB/Monitoring/CommandStartedEvent.c
src/MongoDB/Monitoring/CommandSucceededEvent.c
src/MongoDB/Monitoring/ServerHeartbeatSucceededEvent.c
src/MongoDB/Query.c
src/MongoDB/ReadPreference.c
src/MongoDB/Server.c
src/MongoDB/ServerDescription.c
src/MongoDB/Session.c
src/MongoDB/WriteConcernError.c
src/MongoDB/WriteError.c
src/MongoDB/WriteResult.c
src/phongo_bson.c
src/phongo_bson.h
src/phongo_error.c

PHPC-2146
Best reviewed commit by commit. This PR introduces some refactorings that I made while prototyping raw BSON support. No functional changes are introduced as part of this PR. This improves the following:
* `php_phongo_bson_to_zval` and `php_phongo_bson_to_zval_ex` now take a `const bson_t*` instead of `char*` and `int`. Previously, the function would create a new BSON reader to create a `bson_t`, which is unnecessary as we start out with a `bson_t` to begin with. `php_phongo_bson_data_to_zval` and `php_phongo_bson_data_to_zval_ex` were added to accept a `char*` before passing this on to `php_phongo_bson_to_zval_ex`.
* The `php_phongo_bson_typemap` was updated to no longer contain a `php_phongo_bson_typemap_types` and `zend_class_entry*` for each type. Instead, a new …

PHPC-2146: Refactor typemap struct and BSON encoding/decoding of zvals

---

src/MongoDB/Monitoring/CommandFailedEvent.c
src/MongoDB/Monitoring/CommandStartedEvent.c
src/MongoDB/Monitoring/CommandSucceededEvent.c
src/phongo_structs.h

https://jira.mongodb.org/browse/PHPC-2168
The buffer for snprintf is slightly larger than necessary (21 bytes), but this is consistent with the buffer size we use elsewhere.

PHPC-2168: Use consistent int types for APM fields and snprintf

---

CONTRIBUTING.md

Push "Package X.Y.Z" and "Back to -dev" commits separately to ensure Windows build artifacts are created for the tag.
Add instructions for creating a maintenance branch after releasing a new minor version.

Revise release instructions

---

src/MongoDB/WriteResult.c
src/MongoDB/WriteResult.stub.php
src/MongoDB/WriteResult_arginfo.h
tests/exception/bulkwriteexception-getwriteresult-001.phpt
tests/manager/manager-executeBulkWrite_error-005.phpt
tests/replicaset/writeresult-getserver-002.phpt
tests/server/server-executeBulkWrite-001.phpt
tests/standalone/writeresult-isacknowledged-001.phpt
tests/standalone/writeresult-isacknowledged-002.phpt
tests/standalone/writeresult-isacknowledged-003.phpt
tests/writeResult/writeresult-debug-001.phpt
tests/writeResult/writeresult-debug-002.phpt
tests/writeResult/writeresult-getErrorReplies-001.phpt

PHPC-2165
Includes an update to libmongoc 1.24-dev
I only added a simple test for `getErrorReplies` as this will be comprehensively tested by the unified spec tests in PHPLIB.

PHPC-2165: Expose server error replies in BulkWriteResult

---

.evergreen/config.yml
.evergreen/run-ocsp-responder.sh

https://jira.mongodb.org/browse/PHPC-2164
Patch build: https://spruce.mongodb.com/version/639ade0530661509ea18f337/tasks

PHPC-2164: Refactor run-ocsp-responder.sh to use activate-ocspvenv.sh

---

tests/manager/manager-ctor-ssl-002.phpt
tests/manager/manager-startSession_error-002.phpt
tests/session/session-001.phpt
tests/session/session-002.phpt
tests/session/session-003.phpt
tests/standalone/manager-as-singleton.phpt

Also cleans up some `create_test_manager()` calls in related tests.

Cross-reference prose tests in session test descriptions

---

tests/cursor/bug1529-001.phpt
tests/manager/manager-ctor-auto_encryption-001.phpt
tests/manager/manager-ctor-auto_encryption-002.phpt
tests/manager/manager-getencryptedfieldsmap-001.phpt

PHPC-2156
Until the fix was backported to 6.0, we need to skip certain tests that fail due to extra log output generated by crypt_shared. This also affects older builds, as drivers-evergreen-tools downloads crypt_shared 6.0 for those versions that don't ship with it.

PHPC-2156: Work around crypt_shared log output

---

src/libmongocrypt-compat/mongocrypt-export.h
src/libmongocrypt-compat/mongocrypt/mongocrypt.h

https://jira.mongodb.org/browse/PHPC-2195

PHPC-2195: Use less ambiguous path in mongocrypt.h compat include

---

src/phongo_client.c

Upgraded to MacOS 13.3 recently and building the driver exposed this failure. Not sure why this didn't appear earlier as `strict-prototypes` was part of our developer build flags for a long time already.
```
src/phongo_client.c:78:44: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
const char* php_phongo_crypt_shared_version()
```

Add missing void arg to fix MacOS builds

---

.github/workflows/tests.yml

This pulls cmb69/setup-php-sdk@26487290af8a51fa8ce948f9c4ee18e2fa54529e, which migrates deprecated set-output commands to use $GITHUB_OUTPUT
----
Per [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/):
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
We may want to backport this to older branches to avoid any trouble if we need to create a patch release down the line.

Bump cmb69/setup-php-sdk to 0.7

---

tests/session/session-debug-001.phpt
tests/session/session-debug-002.phpt
tests/session/session-debug-003.phpt
tests/session/session-debug-005.phpt
tests/session/session-debug-006.phpt
tests/session/session-debug-007.phpt

PHPC-2208
A short investigation has led me to conclude that `%c` should definitely match the end-of-line character, as run-tests.php replaces it with a `.` in the regular expression, which is then matched using the `PCRE_DOTALL` modifier. However, since trying to figure this out is inconsequential and the previous fix (applied in #974 to work around PHPC-1345) doesn't work in this case, I replaced the sequence of `%c` with a single `%a` across the tests. While this may match more or fewer than 16 characters unlike the previous solution, as the debug output also contains `string(16)` any binary data that isn't 16 characters long would fail the checks based on that part, apart from being improbable due to the verification employed for BSON subtype 0x04 (UUID).

PHPC-2208: Fix fragile assertion on session IDs

---

.evergreen/config.yml

PHPC-2163: Use PHP 8.2 as latest-stable in edge versions

---

config.m4

https://github.com/mongodb/mongo-c-driver/pull/1252 updated the bundled zlib version to 1.2.13, but this was missed when updating the build scripts. This PR fixes this to ensure that the correct library is used on systems that come without zlib.

Use new bundled zlib version

---

src/phongo_bson.c
tests/bson/bson-packedarray-toPHP-004.phpt

PHPC-2222
While PHPC-2219 may make changes to what can be handled as a root document, serialising a `PackedArray` instance through toPHP with a type map that specifies a BSON root type should always yield a `PackedArray` instance, no matter how absurd the use case may seem.

PHPC-2222: Ensure packed arrays return PackedArray instances when converted to BSON

---

CONTRIBUTING.md

For contributing, I had to search for the `mongodb.so` file and find a way to validate the extension was correctly compiled.

Show how to verify installation after building from source

---

.github/workflows/arginfo-files.yml
.github/workflows/clang-format.yml

This fixes warnings about node 12 actions being deprecated.
Note: the tests workflow was updated in #1380, but other workflows were not changed.

Update actions/checkout to v3

---

src/MongoDB/ClientEncryption.c
src/MongoDB/ClientEncryption.stub.php
src/MongoDB/ClientEncryption_arginfo.h
tests/clientEncryption/clientEncryption-constants.phpt
tests/clientEncryption/clientEncryption-encryptExpression-001.phpt
tests/clientEncryption/clientEncryption-encryptExpression_error-001.phpt
tests/clientEncryption/clientEncryption-encryptExpression_error-002.phpt
tests/clientEncryption/clientEncryption-encrypt_error-001.phpt

https://jira.mongodb.org/browse/PHPC-2197

PHPC-2197: Support queryable encryption range indexes

---

scripts/autotools/libmongoc/CheckResolv.m4
scripts/autotools/libmongoc/PlatformFlags.m4

https://jira.mongodb.org/browse/PHPC-2133
Verified locally with an Atlas SRV connection string. I installed FreeBSD 13.2 in a virtual machine and compiled the driver for PHP 8.0 both with and without this patch.
I _think_ the patch might also apply to OpenBSD, where resolve functions exist in libc, but I'm not confident enough to enable that and would rather wait for an actual bug report to come our way before I expend the effort to test it myself.

PHPC-2133: Fix building with SRV support on FreeBSD

---

tests/bson/bson-int64-compare-001.phpt
tests/bson/bson-int64-compare-002.phpt
tests/bson/bson-int64-compare-003.phpt
tests/bson/bson-int64-compare-004.phpt

This adds more comparison tests for `MongoDB\BSON\Int64` to ensure correct behaviour.

Expand comparison tests for Int64 to cover scalars

---

scripts/autotools/libmongoc/CheckCompression.m4

https://jira.mongodb.org/browse/PHPC-2236
This introduces several configure options:
```
--with-mongodb-snappy=[auto/yes/no]
--with-mongodb-zlib=[auto/yes/system/bundled/no]
--with-mongodb-zstd=[auto/yes/no]
```
The "auto", "yes", and "no" options behave like existing options: "auto" attempts to use a library but allows it to not be found; "yes" requires a library and errors if it's not found; "no" disables a library.
The "system" and "bundled" options for zlib function like "yes", but for using the system library or bundled zlib sources in libmongoc, respectively. Since bundled sources are always available, configuring zlib with "auto", "yes", or "bundled" should never fail.

PHPC-2236: Allow compression libraries to be configured at build time

---

.evergreen/config.yml

PHPLIB-1098
This PR changes the evergreen configuration to only build on supported hosts.
This includes:
- Drop testing on Ubuntu 18.04
- Drop testing on RHEL 7.0
- Add Ubuntu 22.04 and 20.04
- Add RHEL 9.0 and 7.6
RHEL 7.1 and 7.2 are kept to keep testing on the Z and Power architectures. Once the toolchain is available, RHEL 8.0 will take their place.

PHPLIB-1098: Update evergreen build hosts

---

.evergreen/config.yml

PHPLIB-1098
This follows up work in #1442 and removes RHEL 7.1 and 7.2 in favour of RHEL 8.
I've ran a previous patch for these changes: https://spruce.mongodb.com/version/64a65e1be3c331bdcdd56781/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that the zseries builds take a long time due to limited build system availability.

PHPLIB-1098: Test on RHEL 8.x

---

src/BSON/Document.c
src/BSON/Document.stub.php
src/BSON/Document_arginfo.h
src/BSON/PackedArray.c
src/BSON/PackedArray.stub.php
src/BSON/PackedArray_arginfo.h
src/BSON/Persistable.stub.php
src/BSON/Persistable_arginfo.h
src/BSON/Serializable.stub.php
src/BSON/Serializable_arginfo.h
src/MongoDB/ReadConcern.stub.php
src/MongoDB/ReadConcern_arginfo.h
src/MongoDB/ReadPreference.stub.php
src/MongoDB/ReadPreference_arginfo.h
src/MongoDB/ServerApi.stub.php
src/MongoDB/ServerApi_arginfo.h
src/MongoDB/WriteConcern.stub.php
src/MongoDB/WriteConcern_arginfo.h
src/phongo_bson_encode.c
src/phongo_compat.h
tests/bson/bson-document-fromPHP-003.phpt
tests/bson/bson-fromPHP-001.phpt
tests/bson/bson-fromPHP_error-001.phpt
tests/bson/bson-fromPHP_error-005.phpt

PHPC-1000
This PR allows implementations of `MongoDB\BSON\Serializable` to return instances of `MongoDB\BSON\Document` and `MongoDB\BSON\PackedArray`. This allows for an easier implementation of the `Serializable` in PHPLIB classes.
The first commit fixes the tentative return type for `Serializable::bsonSerialize`: while the original type was `array|object`, the code actually rejected any object that was not an instance of `stdClass`. I've also tested the impact on this change: on PHP < 8.1 there is no change as tentative return types are only reported in PHP 8.1+. In those versions, users that have a wider return type (e.g. the original `array|object` type or `object` in general), will see a deprecation message that the return types should be compatible. There is no hard break until we …

PHPC-1000: Allow bsonSerialize to return BSON structure

---

src/BSON/Iterator.c
src/phongo_compat.h

PHPC-2269
Adding to v1.17 only as we'd be backporting a number of compat macros from PHP itself, in addition to `ZVAL_OBJ_COPY`. Waiting on #1450 to be merged so I don't have to bother fixing the PHP 7.2 build.

PHPC-2269: Add internal iterator logic for MongoDB\BSON\Iterator

---

bin/package.xml.in

https://jira.mongodb.org/browse/PHPC-2230
This was omitted in 2ab1e4ba2e6b3126e7acbd7025f3a2727aaa48d2

PHPC-2230: Require PHP 7.4 in package.xml template

---

.github/workflows/arginfo-files.yml

PHPLIB-2284
With this change, arginfo files will be regenerated using the latest version of the script. This helps identify changes to arginfo files as a result of the generation script changing, even when the underlying stub file hasn't changed.

PHPLIB-2284: Force regeneration of arginfo files in workflow

---

scripts/autotools/libmongoc/CheckSSL.m4

PHPC-2280
On MacOS, the driver is compiled using Secure Transport when the `--with-mongodb-ssl` switch is set to `auto`. While this works fine in a CLI context it causes segmentation faults when using the driver in php-fpm, which usually is compiled using OpenSSL. To work around this issue, we now prefer OpenSSL on all platforms, and only check for Secure Transport on MacOS if no OpenSSL installation was found. To continue using Secure Transport on MacOS, users should specify `--with-mongodb-ssl=darwin`.

PHPC-2280: Prefer OpenSSL on MacOS over Secure Transport

---

src/phongo_bson_encode.c

PHPC-2282: Remove trace-level logs during BSON encoding

---

config.m4

https://jira.mongodb.org/browse/PHPC-2287
This dev flag was originally introduced in b83ab98376c81c49c62098fc39af6b05be3c89ff, but did not account for conflicts within headers of earlier PHP versions.

PHPC-2287: Require PHP 8.1.8+ for -Wstrict-prototypes dev flag

---

src/BSON/Document.c
src/BSON/Document.stub.php
src/BSON/Document_arginfo.h
src/BSON/PackedArray.c
src/BSON/PackedArray.stub.php
src/BSON/PackedArray_arginfo.h
src/phongo_compat.h
tests/bson/bson-document-array-access-001.phpt
tests/bson/bson-document-array-access-002.phpt
tests/bson/bson-document-array-access_error-001.phpt
tests/bson/bson-document-array-access_error-002.phpt
tests/bson/bson-document-array-access_error-003.phpt
tests/bson/bson-document-array-access_error-004.phpt
tests/bson/bson-document-get-001.phpt
tests/bson/bson-document-property-access-001.phpt
tests/bson/bson-document-property-access_error-001.phpt
tests/bson/bson-packedarray-array-access-001.phpt
tests/bson/bson-packedarray-array-access-002.phpt
tests/bson/bson-packedarray-array-access_error-001.phpt
tests/bson/bson-packedarray-array-access_error-002.phpt
tests/bson/bson-packedarray-array-access_error-003.phpt
tests/bson/bson-packedarray-array-access_error-004.phpt
tests/bson/bson-packedarray-fromPHP_error-001.phpt
tests/bson/bson-packedarray-get-001.phpt

PHPC-2245, PHPC-2246
This adds array access for `MongoDB\BSON\PackedArray` instances, as well as array and property access to `MongoDB\BSON\Document` instances.
Note that the stubs currently don't implement the `ArrayAccess` interface, as the internal functionality does not require it and it would lead to us having to implement the various `offset...` methods defined in the interface. If implementing the interface is preferable to communicate the fact that such array access is possible, we can do so. The same applies to magic methods for property access in `MongoDB\BSON\Document`.

PHPC-2245, PHPC-2246: Add array and property accessors to BSON types

---

config.m4

https://jira.mongodb.org/browse/PHPC-2275
Typically, PHP_VERSION and PHP_VERSION_ID are only defined when building the extension statically with PHP, since those variables are defined in php-src's own configure.ac. The variables are not defined when using phpize for a shared build.
The PHP Docker images for Alpine happen to define PHP_VERSION in their shell, but not PHP_VERSION_ID, which resulted in an "sh: out of range" error attempting to check the version. The shell-defined PHP_VERSION is also not necessarily the value we'd get from php-config (edge case where someone installs a different PHP version on top of an existing image).
This changes the logic to always rely on php-config to derive these values, as is done in various other extensions (e.g. xdebug, parallel). The awk one-liner …

PHPC-2275: Always consult php-config for PHP version check in config.m4

---

.github/workflows/tests.yml
.github/workflows/windows-release-build.yml
.github/workflows/windows-tests.yml
.github/workflows/windows/prepare-build/action.yml

PHPC-2296
Note: PHP version in arginfo-files was left at PHP 8.2 on purpose until PHP 8.3 is considered stable.

PHPC-2296: Test on PHP 8.3

---

bin/prep-release.php

Discovered while testing #1483 and building a PECL package.

PHPC-2262: Add utf8proc directory to PECL package

---

src/BSON/Document.stub.php
src/BSON/Document_arginfo.h
src/BSON/PackedArray.stub.php
src/BSON/PackedArray_arginfo.h

PHPC-2328
I believe this change is safe enough to go in a patch release. Keeping parameter names consistent with the interface allows people to rely on named arguments, even though they are unlikely to do so for these classes. Also, static analysis tools like Psalm check parameter names and report errors if they mismatch.

PHPC-2328: Use correct parameter name for classes implementing ArrayAccess

---

.github/workflows/windows-release-build.yml

https://jira.mongodb.org/browse/PHPC-2335

PHPC-2335: Replace hub with gh in Windows release workflow

---

php_phongo.c

PHPC-2337
Fixes #1501.
This adds a call to `mongoc_log_trace_disable()` in the extension's `MINIT` function. Since we always compile with trace-level logging (which is emitted when the `mongodb.debug` setting is enabled), libmongoc starts out with trace logging enabled. While we disable trace logging in `phongo_log_sync_handlers()`, this function is not called if `mongodb.debug` is not set, thus leaving trace logging enabled and causing significant overhead due to message preparation.
Now, trace logging starts out as disabled and will be enabled when `phongo_log_sync_handlers()` is called, either due to adding a log subscriber to a manager or due to the INI setting being enabled and us storing a file handle the debug log gets written to.
I've confirmed that the performance increases again …

PHPC-2337: Fix performance regression due to trace logging

---

.evergreen/compile-unix.sh

This PR adds a call to update-submodule-sources.php when compiling against a different version of libmongoc than the bundled one. This helps avoid "symbol not found" errors when compiling with libmongoc latest with new files not included in the bundled stable release.

Update submodule sources when building driver

---

.github/workflows/windows-release-build.yml
.github/workflows/windows-tests.yml

https://jira.mongodb.org/browse/PHPC-2365

PHPC-2365: Update GitHub actions to use Node 20

---

phongo_version.h

Note: this PR is mainly here to try out a new release workflow with new branch protections in mind. It is not a blueprint for future releases.
This PR must not be merged using a squash merge, as it needs to retain the "Package 1.18.1" commit, which is the base for the release tag.

Prepare 1.18.1 release

---

.github/workflows/windows-tests.yml

Since Windows tests often suffer from long startup times of the MongoDB daemon, the failure of a single job cancels the entire workflow. Disabling `fail-fast` will prevent this and help get at least some test coverage without restarting all builds.

Disable fail-fast for Windows Tests

---

config.m4
scripts/autotools/CheckCompiler.m4
scripts/autotools/PlatformFlags.m4
src/libmongocrypt-compat/mongocrypt/mongocrypt.h

https://jira.mongodb.org/browse/PHPC-2382
Prefer PHP_VERSION_ID for static builds, and fall back to invoking php-config otherwise.
mongocrypt.h previously used a path relative to the PHPC project root, which is not compatible with static builds. The current path is relative to src/, which is explicitly defined as an include path in config.m4.
Related: https://github.com/mongodb/mongo-php-driver/issues/1549

PHPC-2382: Allow static builds with php-src

---

.github/workflows/package-release.yml
.github/workflows/release.yml

With significant changes being introduced to the release tooling in the shared repository, we should rely on a tagged version of those release tools.

Use stable version of release tooling

---

.github/workflows/package-release.yml
.github/workflows/release.yml

Reverts mongodb/mongo-php-driver#1568. v2 uses a different setup process to fetch credentials which wouldn't work with our setup. I'll be migrating to v2 separately and have created PHPC-2391 to track this.

Revert "Bump mongodb-labs/drivers-github-tools from 1 to 2"

---

.github/workflows/package-release.yml
.github/workflows/release.yml

PHPC-2391
This PR updates drivers-github-tools to v2 and makes the necessary adjustments. Alongside with those changes, this now removes the old fixed token in favour of generating a temporary token for the mongodb-dbx-release-bot app. The release commit and tags will be attributed to this bot in future, as it will be for other drivers.
I've tested these changes in my fork and applied the same configuration here. Note that once this PR is merged and we remove the old configuration, releases for 1.18 **will no longer work**!

PHPC-2391: Update drivers tools to v2

---

.gitignore
CONTRIBUTING.md
sbom.json
scripts/update-sbom.sh

PHPC-2380
This PR introduces the "SBOM lite" file necessary to generate a full SBOM when releasing a new version. The SBOM file is generated from a list of [purls](https://github.com/package-url/purl-spec) using the silkbomb tool. The script to update the tooling is added, along with updated instructions for updating submodules.

PHPC-2380: Add SBOM file and tooling to update it

---

src/MongoDB/ClientEncryption.c
src/MongoDB/ClientEncryption.stub.php
src/MongoDB/ClientEncryption_arginfo.h
tests/clientEncryption/clientEncryption-constants.phpt
tests/clientEncryption/clientEncryption-encryptExpression-001.phpt
tests/clientEncryption/clientEncryption-encryptExpression_error-002.phpt

https://jira.mongodb.org/browse/PHPC-2401
Depends on https://github.com/mongodb/mongo-php-driver/pull/1582

PHPC-2401: Support QEv2 range protocol

---

.github/workflows/release.yml

This PR adds logic to automatically merge up changes to the next release branch. This is necessary as the pull request for the merge-up action will always have a conflict due to the version already having changed in the next branch.
If the branch detection logic finds a newer branch to merge to (which it always should as we're releasing from version branches), it runs a `git merge --strategy=ours` in this next branch, then pushes those changes before pushing the release branch. By pushing the next branch before the release branch, the merge-up action discovers that there are no commits to be merged from the release branch into the next branch and will not create a merge-up pull request.
Note that if the release branch contains changes that have not been merged up yet, those changes will …

Manually merge up version bump commits

---

tests/ocsp-failure.phpt

https://jira.mongodb.org/browse/PHPC-2254
libmongoc 1.28 now includes the topology type in the server selection error message.
This makes the expected error message consistent with other tests.

PHPC-2254: Relax server selection timeout error message pattern

---

.github/workflows/release.yml

This PR leverages the new [full-report action](https://github.com/mongodb-labs/drivers-github-tools?tab=readme-ov-file#full-report) to generate all necessary SSDLC reports.

Use full-report convenience action for SSDLC reports

---

.evergreen/config.yml
.evergreen/config/generated/test/require-api-version-5.0.yml
.evergreen/config/generated/test/require-api-version-6.0.yml
.evergreen/config/generated/test/require-api-version-7.0.yml
.evergreen/config/generated/test/require-api-version-latest.yml
.evergreen/config/generated/test/require-api-version-rapid.yml
.evergreen/config/templates/test/require-api-version.yml

This PR adds evergreen aliases for GitHub commit checks and git tags. It also serves as a test to see if evergreen creates the correct patch definition for a pull request.

Add tag checks aliases

---

.evergreen/compile-unix.sh

The `calc_release_version` script needs to be invoked from the libmongoc root directory, otherwise it will fail to compute a valid version, which in turn makes some of our tests fail.

Fix version computation for libmongoc development versions

---

src/MongoDB/Exception/SSLConnectionException.stub.php
src/MongoDB/Exception/SSLConnectionException_arginfo.h
src/MongoDB/Exception/WriteException.stub.php
src/MongoDB/Exception/WriteException_arginfo.h

PHPC-2349, PHPC-2411: Deprecate unused exception classes

---

src/BSON/UTCDateTime.c
src/BSON/UTCDateTime.stub.php
src/BSON/UTCDateTime_arginfo.h
tests/bson/bson-utcdatetime-todatetimeimmutable-001.phpt
tests/bson/bson-utcdatetime-todatetimeimmutable-002.phpt

Fix PHPC-2286
Create a distinct method than `UTCDateTime::toDateTime` to avoid any ambiguity on the returned class.
Read why you should [Stop Using DateTime](https://www.nikolaposa.in.rs/blog/2019/07/01/stop-using-datetime/)

PHPC-2286 Implement `UTCDateTime::toDateTimeImmutable`

---

tests/bson/bson-utcdatetime-serialization_error-002.phpt
tests/bson/bson-utcdatetime-serialization_error-004.phpt
tests/bson/bson-utcdatetime-set_state_error-002.phpt
tests/bson/bson-utcdatetime_error-003.phpt

Fix [PHPC-1957](https://jira.mongodb.org/browse/PHPC-1957)
Test cases from @jmikola's [comment](https://jira.mongodb.org/browse/CDRIVER-1377?focusedCommentId=1323383&focusedId=1323383&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1323383).
I don't think we need to replicate all the tests for the C driver: https://github.com/mongodb/libbson/commit/877c4652bc032e960b712d7829fa1b8fe47c5552#diff-f659e15d1c412b12aedd35fd33872db3e54e03fa9e69927ba905924613c6c66dR211-R263

PHPC-1957 Add tests for out-of-range `UTCDateTime` values

---

.github/workflows/package-release.yml
.github/workflows/tests.yml
.github/workflows/windows-tests.yml
src/MongoDB/Monitoring/ServerHeartbeatSucceededEvent.c
src/phongo_structs.h
tests/apm/serverHeartbeatSucceededEvent-001.phpt

This PR makes several changes, all related to how we start MongoDB on Windows. Since the previous method of starting MongoDB would often time out, the Windows workflow now uses drivers-evergreen-tools to start clusters. This should be more reliable and as a side effect uses the same configs we use for our Linux testing. As part of this change, I have also re-organised the windows workflows so that tests for a given variant (i.e. the combination of PHP version, architecture, and thread safety) start immediately after the corresponding build has completed, not only after all builds have completed. This yields faster test results.
During testing, I discovered an issue in the tests for `ServerHeartbeatFailedEvent`, where an expected integer return was actually returned as an `Int64` instance …

Use drivers-evergreen-tools for Windows testing

---

src/BSON/Int64.c
tests/bson/bson-int64-compare-005.phpt

PHPC-2420
Previously, we deferred to `zend_std_compare_objects` when comparing a single `Int64` instance with a long or double. By default, this will attempt to cast values to long or double, then comparing it. On 32-bit platforms, this cast truncates any value outside of the 32-bit range and yields a warning about this truncation. This means that we were not able to properly compare such values, even when we technically would easily be able to (as only the value of `ZEND_LONG` is limited to 32 bits, but `int64_t` is still available).
This PR changes this logic to specifically handle comparisons between to `Int64` instances as well as a single `Int64` instance with a long or double. Only if the instance is being compared with anything else will we attempt to cast the value. This removes …

PHPC-2420: Compare Int64 instances without casting

---

src/BSON/UTCDateTime.c
tests/bson/bson-utcdatetime-todatetime-003.phpt

PHPC-2429
When using negative milliseconds, the `DateTime` instance created by `toDateTime` is broken with negative milliseconds. Directly initialising the instance with a decimal timestamp fixes this issue.

PHPC-2429: Fix UTCDateTime with negative timestamps

---

composer.json

PHPC-2420
Note: pie support is experimental. No support will be given for installation issues with pie. The integration with pie is mainly done to be able test pie itself.
This is an initial version of a composer.json file to be used with [pie](https://github.com/php/pie). Once this PR has been merged to master, we can add the extension to packagist; after tagging a release we can install the extension using pie.

PHPC-2420: Initial composer.json for pie support

---

tests/clientEncryption/clientEncryption-encryptExpression-001.phpt
tests/clientEncryption/clientEncryption-encryptExpression_error-002.phpt

PHPC-2403
With `sparsity` and `trimFactor` now optional, we can remove them from the tests (see https://github.com/mongodb/mongo-php-driver/pull/1583#discussion_r1638671510 for context).

PHPC-2403: Remove optional sparsity and trimFactor options

---

.github/workflows/arginfo-files.yml
.github/workflows/clang-format.yml

This PR removes the matrix strategy, as using it will include the PHP version in the name of the job, making it more difficult to have required check across branches. By setting it as an env var, we can avoid duplication as well have a consistent name for the checks after changing the PHP requirement in #1631.

Update GitHub Actions job names

---

tests/manager/manager-executeBulkWrite-011.phpt

On MongoDB latest, the error message is different as the validation is handled by the execution planner. The additional `%S` ensures that tests pass on upcoming versions of MongoDB as well.

Fix exception message expectation on MongoDB latest
